#!/usr/bin/env python3
from __future__ import annotations
import json, sys
from pathlib import Path
root=Path(sys.argv[1] if len(sys.argv)>1 else '.').resolve()

def req(cond,msg):
    if not cond: raise SystemExit('ERROR: '+msg)

config=(root/'backend/app/config.py').read_text()
client=(root/'backend/app/client_contracts.py').read_text()
main=(root/'backend/app/main.py').read_text()
poly=(root/'backend/app/polyglot.py').read_text()
neural=(root/'backend/neural-runtime/service.py').read_text()
compose=(root/'backend/docker-compose.example.yml').read_text()
docker=(root/'backend/neural-runtime/Dockerfile').read_text()
requirements=(root/'backend/neural-runtime/requirements.txt').read_text()
plugin=(root/'wordpress/sustainable-catalyst-workspace/sustainable-catalyst-workspace.php').read_text()
klass=(root/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace.php').read_text()
req('service_version: str = "3.23.0"' in config,'backend version is not 3.23.0')
req('"workspaceVersion": "3.23.0"' in client,'typed client backend contract is not 3.23.0')
req('SERVICE_VERSION = "3.23.0"' in neural,'neural runtime version is not 3.23.0')
for op in ['workspace.neural.checkpoint-inspect','workspace.neural.resume-linear','workspace.neural.resume-mlp']:
    req(op in neural and op in poly,f'neural operation missing: {op}')
req('CHECKPOINT_SCHEMA = "sc-workspace-neural-checkpoint-artifact/1.0"' in neural,'checkpoint artifact schema missing')
req('CHECKPOINT_STATE_SCHEMA = "sc-workspace-neural-checkpoint-state/1.0"' in neural,'checkpoint state schema missing')
req('CHECKPOINT_FORMAT = "sc-workspace-neural-portable-checkpoint/1.0"' in neural,'checkpoint format missing')
req('CHECKPOINT_RESUME_POLICY = "same-dataset-only"' in neural,'resume policy missing')
req('"checkpointPersistenceEnabled": True' in neural,'checkpoint persistence not enabled in neural runtime')
req('"resumeTrainingEnabled": True' in neural,'resume training not enabled in neural runtime')
req('_state_encode' in neural and '_state_decode' in neural,'portable state codec missing')
req('zlib.compress' in neural and 'base64.b64encode' in neural,'portable checkpoint compression/encoding missing')
req('model.load_state_dict' in neural and 'optimizer.load_state_dict' in neural,'model/optimizer restoration missing')
req('parentCheckpointFingerprint' in neural and 'lineageDepth' in neural,'checkpoint lineage fields missing')
req('trainingCompatibilityFingerprint' in neural and 'trainingDatasetFingerprint' in neural,'checkpoint compatibility fingerprints missing')
req('"checkpointPath"' in neural and '"stateDictBase64"' in neural,'raw checkpoint/state blocks are not preserved')
req('torch.save(' not in neural and 'torch.load(' not in neural,'raw torch serialization unexpectedly enabled')
req('"neuralRuntimeBoundedOperations": 14' in main,'Workspace neural operation count is not 14')
req('"neuralTrainingCheckpointPersistenceEnabled": True' in main,'Workspace checkpoint capability flag missing')
req('"neuralTrainingResumeEnabled": True' in main,'Workspace resume capability flag missing')
req('application/vnd.sc.workspace.neural-checkpoint+json' in poly,'Workspace checkpoint artifact media type missing')
req('workspaceCheckpointArtifactId' in poly and 'parentCheckpointFingerprint' in poly,'polyglot checkpoint receipt lineage missing')
req('outputId":"neural-checkpoint"' in poly,'execution-run checkpoint output missing')
req('SC_WORKSPACE_NEURAL_MAX_CHECKPOINT_COMPRESSED_BYTES' in compose,'Compose checkpoint compressed limit missing')
req('SC_WORKSPACE_NEURAL_MAX_CHECKPOINT_JSON_BYTES' in compose,'Compose checkpoint JSON limit missing')
req('USER 65532:65532' in docker,'numeric runtime UID changed unexpectedly')
req('read_only: true' in compose and 'no-new-privileges:true' in compose,'container hardening changed unexpectedly')
req('numpy==2.2.6' in requirements and 'torch==2.10.0' in requirements,'neural dependency pins changed unexpectedly')
req(' * Version: 3.23.0' in plugin,'WordPress plugin header is not 3.23.0')
req("define('SC_WORKSPACE_VERSION', '3.23.0');" in plugin,'SC_WORKSPACE_VERSION is not 3.23.0')
for rel in ['assets/js/workspace-v3.23.0.js','assets/css/workspace-v3.23.0.css','assets/js/sc-workspace-typed-client-v32300.js']:
    req((root/'wordpress/sustainable-catalyst-workspace'/rel).is_file(),f'missing stable package asset {rel}')
req('assets/js/workspace-v3.23.0.js' in klass,'WordPress enqueue does not use v3.23.0 JS shell')
req('assets/css/workspace-v3.23.0.css' in klass,'WordPress enqueue does not use v3.23.0 CSS shell')
req('sc-workspace-typed-client-v32300.js' in klass,'WordPress enqueue does not use v3.23.0 typed client')
manifest=root/'release-manifest-v3.23.0.json'; req(manifest.is_file(),'release manifest missing')
d=json.loads(manifest.read_text())
req(d.get('version')=='3.23.0','manifest version mismatch')
req(d.get('backendVersion')=='3.23.0','manifest backend mismatch')
req(d.get('databaseMigrationRequired') is False,'unexpected DB migration')
req(d.get('rollbackBaseline')=='3.22.0.2','rollback baseline mismatch')
n=d.get('neuralRuntime') or {}
req(n.get('operations')==14,'manifest neural operation count mismatch')
req(n.get('checkpointPersistenceEnabled') is True,'manifest checkpoint persistence mismatch')
req(n.get('resumeTrainingEnabled') is True,'manifest resume mismatch')
req(n.get('modelAndOptimizerStateRestored') is True,'manifest optimizer state restoration missing')
req(n.get('parentCheckpointLineage') is True,'manifest parent lineage missing')
req(n.get('rawTorchSerializationAccepted') is False,'manifest raw torch serialization boundary changed')
req(n.get('acceleratorExecutionEnabled') is False,'accelerator unexpectedly enabled')
req((root/'backend/tests/test_neural_checkpoint_resume_v32300.py').is_file(),'v3.23 checkpoint regression tests missing')
print('PASS: Workspace v3.23.0 checkpoint, resume, and neural artifact lineage validation')
