#!/usr/bin/env python3
from __future__ import annotations
import json, sys
from pathlib import Path
root=Path(sys.argv[1] if len(sys.argv)>1 else '.').resolve()

def req(cond,msg):
    if not cond: raise SystemExit('ERROR: '+msg)

config=(root/'backend/app/config.py').read_text()
client=(root/'backend/app/client_contracts.py').read_text()
poly=(root/'backend/app/polyglot.py').read_text()
neural=(root/'backend/neural-runtime/service.py').read_text()
docker=(root/'backend/neural-runtime/Dockerfile').read_text()
compose=(root/'backend/docker-compose.example.yml').read_text()
requirements=(root/'backend/neural-runtime/requirements.txt').read_text()
plugin=(root/'wordpress/sustainable-catalyst-workspace/sustainable-catalyst-workspace.php').read_text()
klass=(root/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace.php').read_text()
req('service_version: str = "3.22.0.2"' in config,'backend version is not 3.22.0.2')
req('"workspaceVersion": "3.22.0.2"' in client,'typed client backend contract is not 3.22.0.2')
req('SERVICE_VERSION = "3.22.0.2"' in neural,'neural runtime version is not 3.22.0.2')
req('import torch._dynamo as _torch_dynamo' in neural,'torch._dynamo preload missing')
req('OPTIMIZER_RUNTIME_WARM = _warm_optimizer_runtime()' in neural,'optimizer warmup missing')
req('os.environ["TORCHINDUCTOR_CACHE_DIR"] = "/tmp/torchinductor"' in neural,'service cache pin missing')
req('os.environ["XDG_CACHE_HOME"] = "/tmp/.cache"' in neural,'service XDG cache pin missing')
req('os.environ["USER"] = "scworkspace"' in neural,'service USER identity pin missing')
req('USER 65532:65532' in docker,'numeric runtime UID changed unexpectedly')
req('TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor' in docker,'Docker cache pin missing')
req('XDG_CACHE_HOME=/tmp/.cache' in docker,'Docker XDG cache pin missing')
req('TORCHINDUCTOR_CACHE_DIR: /tmp/torchinductor' in compose,'Compose cache pin missing')
req('read_only: true' in compose and 'no-new-privileges:true' in compose,'container hardening changed unexpectedly')
req('numpy==2.2.6' in requirements,'NumPy pin missing')
req('torch==2.10.0' in requirements,'PyTorch pin changed unexpectedly')
req('workspace.neural.train-linear' in poly and 'workspace.neural.train-mlp' in poly,'training operations missing')
req(' * Version: 3.22.0.2' in plugin,'WordPress plugin header is not 3.22.0.2')
req("define('SC_WORKSPACE_VERSION', '3.22.0.2');" in plugin,'SC_WORKSPACE_VERSION is not 3.22.0.2')
for rel in ['assets/js/workspace-v3.22.0.2.js','assets/css/workspace-v3.22.0.2.css','assets/js/sc-workspace-typed-client-v322002.js']:
    req((root/'wordpress/sustainable-catalyst-workspace'/rel).is_file(),f'missing stable package asset {rel}')
req('assets/js/workspace-v3.22.0.2.js' in klass,'WordPress enqueue does not use v3.22.0.2 JS shell')
req('assets/css/workspace-v3.22.0.2.css' in klass,'WordPress enqueue does not use v3.22.0.2 CSS shell')
req('sc-workspace-typed-client-v322002.js' in klass,'WordPress enqueue does not use v3.22.0.2 typed client')
manifest=root/'release-manifest-v3.22.0.2.json'; req(manifest.is_file(),'release manifest missing')
d=json.loads(manifest.read_text())
req(d.get('version')=='3.22.0.2','manifest version mismatch')
req(d.get('backendVersion')=='3.22.0.2','manifest backend mismatch')
req(d.get('databaseMigrationRequired') is False,'unexpected DB migration')
n=d.get('neuralRuntime') or {}
req(n.get('operations')==11,'manifest neural operation count mismatch')
req(n.get('runtimeUid')=='65532:65532','manifest runtime UID mismatch')
req(n.get('runtimeIdentity')=='scworkspace','manifest runtime identity mismatch')
req(n.get('runtimeHome')=='/tmp','manifest runtime home mismatch')
req(n.get('torchInductorCacheDir')=='/tmp/torchinductor','manifest torch cache mismatch')
req(n.get('xdgCacheHome')=='/tmp/.cache','manifest XDG cache mismatch')
req(n.get('checkpointPersistenceEnabled') is False,'checkpoint persistence unexpectedly enabled')
req(n.get('resumeTrainingEnabled') is False,'resume unexpectedly enabled')
req(n.get('acceleratorExecutionEnabled') is False,'accelerator unexpectedly enabled')
print('PASS: Workspace v3.22.0.2 hardened neural runtime identity/cache repair validation')
