const assert=require('assert');
const api=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-research-templates-v1.js');
assert.equal(api.SCHEMA,'sc-workspace-research-template-library/1.0');
const builtins=api.builtins();
assert.equal(builtins.length,8);
assert(builtins.find(t=>t.title==='Literature Review'));
const plan=api.plan(builtins.find(t=>t.title==='Literature Review'),{projectTitle:'Climate Literature Review',includeWorkflow:true,includeNotebook:true,includeStarterObjects:true});
assert.equal(plan.projectTitle,'Climate Literature Review');
assert(plan.workflow.steps.length>=6);
assert(plan.notebook.sections.includes('Evidence Matrix'));
assert(plan.starterObjects.length>=1);
assert.equal(plan.governance.copiesProjectContent,false);
const run={templateId:'evidence-review',title:'Custom Review',steps:[{key:'one',title:'One',description:'First',mode:'research',status:'complete',note:'SECRET NOTE',objectIds:['object-1'],completedAt:'2026-01-01T00:00:00Z'},{key:'two',title:'Two',description:'Second',mode:'analysis',status:'in-progress',note:'SECRET 2',objectIds:['object-2']}]};
const nb={title:'Private Notebook',sections:[{title:'Scope',blocks:[{content:'SECRET CONTENT'}]},{title:'Evidence',blocks:[]}]};
const custom=api.templateFromWorkflow(run,nb,'Reusable Review');
const raw=JSON.stringify(custom);
assert(!raw.includes('SECRET NOTE'));
assert(!raw.includes('SECRET CONTENT'));
assert(!raw.includes('object-1'));
assert(!raw.includes('completedAt'));
assert.equal(custom.steps[0].title,'One');
assert.deepEqual(custom.notebook.sections,['Scope','Evidence']);
let library=api.normalizeLibrary({customTemplates:[]});
const added=api.addCustom(library,custom);assert(added.ok);library=added.library;assert.equal(library.customTemplates.length,1);
const pkg=api.exportPackage(library);const verified=api.verifyPackage(pkg);assert(verified.ok);assert.equal(verified.library.customTemplates.length,1);
pkg.library.customTemplates[0].title='Tampered';assert.equal(api.verifyPackage(pkg).ok,false);
const g=api.governance();assert(g.explicitInstantiationRequired);assert.equal(g.copiesEvidence,false);assert.equal(g.automaticAi,false);assert(g.blankProjectsRemainSupported);
console.log('PASS - v0.49.0 research templates runtime');
