'use strict';
const assert=require('assert');
const exp=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-experience-v1.js');
assert.equal(exp.EXPERIENCE_SCHEMA,'sc-workspace-experience/1.0');
assert.equal(exp.PREF_SCHEMA,'sc-workspace-experience-preferences/1.0');
assert.equal(exp.STORAGE_KEY,'sc_workspace_experience_v0500');
assert.deepEqual(exp.normalizePreferences({density:'compact'}),{schema:exp.PREF_SCHEMA,density:'compact',commandHints:true});
assert.deepEqual(exp.normalizePreferences({density:'anything'}),{schema:exp.PREF_SCHEMA,density:'comfortable',commandHints:true});
assert.equal(exp.routeForShortcut('1'),'start');
assert.equal(exp.routeForShortcut('5'),'exchange');
assert.equal(exp.routeForShortcut('0'),null);
assert.ok(exp.commands('notebook').some(c=>c.id==='notebook'));
assert.ok(exp.commands('import').some(c=>c.id==='interoperability'));
assert.ok(exp.commands('').length>=17);
assert.equal(exp.terminology().length,6);
const gov=exp.governanceState();
assert.equal(gov.schemaMigration,false);
assert.equal(gov.canonicalDataMutation,false);
assert.equal(gov.automaticProjectCreation,false);
assert.equal(gov.automaticAi,false);
assert.equal(gov.editorialHeaderRulePx,4);
console.log('PASS - v0.50.0 Workspace Experience Consolidation runtime');
