import json,unittest
from pathlib import Path
R=Path(__file__).resolve().parents[1];P=R/'wordpress/sustainable-catalyst-workspace';MAN=json.loads((R/'release-manifest-v1.6.0.json').read_text());OLD=json.loads((R/'history/release-manifest-v1.5.0.json').read_text());REG=json.loads((R/'registry/workspace-product-record-v1.6.0.json').read_text());MAIN=(P/'sustainable-catalyst-workspace.php').read_text();PHP=(P/'includes/class-sc-workspace.php').read_text();APP=(P/'assets/js/workspace-v1.6.0.js').read_text();DEP=(P/'includes/class-sc-workspace-deployment.php').read_text();REGPHP=(P/'includes/class-sc-workspace-registry.php').read_text()
class WorkbenchDecisionRoundtrip(unittest.TestCase):
 def test_01_lineage(self): self.assertEqual((MAN['version'],MAN['previous_version'],MAN['release_name']),('1.6.0','1.5.0','Workbench & Decision Studio Round-Trip Workflows'))
 def test_02_registry(self): self.assertEqual((REG['public_version'],REG['previous_version']),('1.6.0','1.5.0'));self.assertIn("BACKUP_KEY = 'sc_workspace_registry_backup_v160'",REGPHP);self.assertIn('LEGACY_PENDING_KEY_V150',REGPHP)
 def test_03_schema_freeze(self): self.assertEqual((MAN['storage_schema_version'],MAN['project_schema'],MAN['export_schema']),(35,'sc-workspace-project/20.0','sc-workspace-project-export/20.0'));self.assertEqual((MAN['storage_schema_version'],MAN['project_schema'],MAN['export_schema']),(OLD['storage_schema_version'],OLD['project_schema'],OLD['export_schema']))
 def test_04_only_route(self): self.assertEqual(set(MAN['rest_routes'])-set(OLD['rest_routes']),{'/wp-json/sc-workspace/v1/workbench-decision-roundtrip-contract'});self.assertIn("'/workbench-decision-roundtrip-contract'",PHP)
 def test_05_workflows(self): self.assertEqual(len(MAN['tool_roundtrip_integration']['workbench_workflows']),6);self.assertEqual(len(MAN['tool_roundtrip_integration']['decision_studio_workflows']),6);self.assertIn('simulation',MAN['tool_roundtrip_integration']['workbench_workflows']);self.assertIn('scenario-comparison',MAN['tool_roundtrip_integration']['decision_studio_workflows'])
 def test_06_families(self): self.assertEqual(MAN['tool_roundtrip_integration']['workbench_materialization']['transformed-dataset'],'dataset');self.assertEqual(MAN['tool_roundtrip_integration']['decision_studio_materialization']['recommendation'],'decision')
 def test_07_boundaries(self):
  g=MAN['tool_roundtrip_integration'];self.assertTrue(g['explicit_context_selection']);self.assertTrue(g['destination_match_required']);self.assertTrue(g['traceability_edges_from_selected_context']);self.assertFalse(g['automatic_context_upload']);self.assertFalse(g['automatic_return_commit']);self.assertFalse(g['automatic_ai']);self.assertFalse(g['behavioral_telemetry'])
 def test_08_ui(self): self.assertIn('WORKBENCH / DECISION STUDIO ROUND TRIP',PHP);self.assertIn('Open tool with IDs',PHP);self.assertIn('Import returned work',PHP)
 def test_09_runtime(self): self.assertIn('data-release-stage="workbench-decision-roundtrip"',PHP);self.assertIn('workspace-v1.6.0.js',PHP);self.assertIn('sc-workspace-workbench-decision-roundtrip-v1',PHP);self.assertIn('Explicit Workbench round trip',APP);self.assertIn('Explicit Decision Studio round trip',APP)
 def test_10_deployment(self): self.assertIn("PREVIOUS_RELEASE = '1.5.0'",DEP);self.assertIn("ROLLBACK_RELEASE = '1.5.0'",DEP);self.assertIn('class-sc-workspace-workbench-decision-roundtrip.php',DEP)
 def test_11_identity(self): self.assertIn('Version: 1.6.0',MAIN);self.assertIn("SC_WORKSPACE_VERSION', '1.6.0'",MAIN)
if __name__=='__main__':unittest.main()
