import json, unittest
from pathlib import Path
R=Path(__file__).resolve().parents[1]
MAN=json.loads((R/'release-manifest-v0.75.0.json').read_text()); REG=json.loads((R/'registry/workspace-product-record-v0.75.0.json').read_text())
MAIN=(R/'wordpress/sustainable-catalyst-workspace/sustainable-catalyst-workspace.php').read_text(); PHP=(R/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace.php').read_text(); REGPHP=(R/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace-registry.php').read_text(); HELP=(R/'wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-institutional-validation-v1.js').read_text(); IRP=(R/'wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-institutional-research-packages-ui-v1.js').read_text(); APP=(R/'wordpress/sustainable-catalyst-workspace/assets/js/workspace-v2.0.3.js').read_text(); CSS=(R/'wordpress/sustainable-catalyst-workspace/assets/css/workspace-v2.0.3.css').read_text()
class InstitutionalValidationContract(unittest.TestCase):
 def test_01_lineage(self): self.assertEqual((MAN['version'],MAN['previous_version'],MAN['release_name']),('0.75.0','0.74.0','Institutional Package & Handoff Validation')); self.assertIn('Version: 2.0.3',MAIN)
 def test_02_schema_stable(self): self.assertEqual(MAN['storage_schema_version'],35); self.assertEqual(MAN['project_schema'],'sc-workspace-project/20.0'); self.assertEqual(MAN['export_schema'],'sc-workspace-project-export/20.0'); self.assertFalse(MAN['schema_migration_required'])
 def test_03_contract(self): self.assertIn("'/institutional-validation-contract'",PHP); self.assertIn('institutional_validation_contract',PHP); self.assertIn('/wp-json/sc-workspace/v1/institutional-validation-contract',MAN['rest_routes'])
 def test_04_package_scope_and_disclosure(self): self.assertIn('researchPackageAssessment',HELP); self.assertIn('Disclosure scope',HELP); self.assertIn('Disclosure counts',HELP); self.assertTrue(MAN['institutional_package_handoff_validation']['package_scope_exact_match_required'])
 def test_05_recipient_purpose(self): self.assertTrue(MAN['institutional_package_handoff_validation']['recipient_required']); self.assertTrue(MAN['institutional_package_handoff_validation']['purpose_required']); self.assertIn('data-scw-irp-institution required',PHP); self.assertIn('data-scw-irp-purpose required',PHP)
 def test_06_stale_revision(self): self.assertIn('Source project changed after',HELP); self.assertTrue(MAN['institutional_package_handoff_validation']['source_revision_staleness_detected']); self.assertIn('historical snapshot',IRP)
 def test_07_sha256_handoff(self): self.assertIn('handoffPackageAssessment',HELP); self.assertIn("algorithm==='SHA-256'",HELP); self.assertTrue(MAN['institutional_package_handoff_validation']['promotion_package_sha256_required']); self.assertIn('packageAssessment',APP)
 def test_08_receipt_validation(self): self.assertIn('receiptAssessment',HELP); self.assertIn('duplicateReceiptBlocked:true',HELP); self.assertIn('requiresUnverifiedAcknowledgement',APP); self.assertTrue(MAN['institutional_package_handoff_validation']['duplicate_receipt_blocked'])
 def test_09_boundaries(self):
  h=MAN['institutional_package_handoff_validation']; self.assertTrue(h['source_workspace_retains_independent_copy']); self.assertFalse(h['automatic_upload']); self.assertFalse(h['automatic_institutional_ingestion']); self.assertFalse(h['automatic_source_mutation']); self.assertFalse(h['organization_permissions_in_workspace'])
 def test_10_not_score(self): self.assertEqual(MAN['institutional_package_handoff_validation']['readiness_model'],'explainable-checklist-no-score'); self.assertIn('not readiness or quality scores',PHP)
 def test_11_privacy_report(self): self.assertIn('projectContentIncluded:false',HELP); self.assertIn('recipientLabelIncluded:false',HELP); self.assertIn('data-scw-iv-export',PHP)
 def test_12_assets(self): self.assertIn("'sc-workspace-v203'",PHP); self.assertIn('workspace-v2.0.3.js',PHP); self.assertIn('workspace-v2.0.3.css',PHP); self.assertIn('sc-workspace-institutional-validation-v1',PHP); self.assertIn('sc-workspace-institutional-validation-ui-v1',PHP); self.assertIn('/* v0.75.0 — Institutional Package & Handoff Validation */',CSS)
 def test_13_registry_history(self): self.assertEqual((REG['public_version'],REG['previous_version'],REG['release_name']),('0.75.0','0.74.0','Institutional Package & Handoff Validation')); self.assertIn("BACKUP_KEY = 'sc_workspace_registry_backup_v203'",REGPHP); self.assertIn('LEGACY_PENDING_KEY_V0740',REGPHP); self.assertTrue((R/'history/release-manifest-v0.74.0.json').exists()); self.assertTrue((R/'history/workspace-product-record-v0.74.0.json').exists())
 def test_14_artifacts(self):
  for f in ['schemas/sc-workspace-institutional-transfer-validation-v1.schema.json','schemas/sc-workspace-institutional-validation-report-v1.schema.json','schemas/sc-workspace-institutional-handoff-validation-policy-v1.schema.json','docs/INSTITUTIONAL_PACKAGE_HANDOFF_VALIDATION_V0750.md']: self.assertTrue((R/f).exists(),f)
if __name__=='__main__': unittest.main()
