'use strict';
const assert=require('assert');
const perf=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-scale-performance-v1.js');
const ik=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-integrated-knowledge-v1.js');
assert.strictEqual(perf.SCHEMA,'sc-workspace-scale-performance/1.0');
assert.strictEqual(perf.BUDGETS.renderWindow,120);
const state=perf.stressFixture({projects:20,objectsPerProject:80,notebooksPerProject:4,blocksPerNotebook:40});
const before=JSON.stringify(state);
perf.clearCache();
const first=perf.deriveIntegrated(state,ik), stats1=perf.cacheStats();
const second=perf.deriveIntegrated(state,ik), stats2=perf.cacheStats();
assert.strictEqual(first,second); assert.strictEqual(stats1.misses,1); assert.ok(stats2.hits>=1);
assert.strictEqual(JSON.stringify(state),before,'derived indexing must not mutate canonical fixture');
const windowed=perf.windowed(new Array(1000).fill(0).map((_,i)=>i));
assert.strictEqual(windowed.visible,120); assert.strictEqual(windowed.total,1000); assert.strictEqual(windowed.hasMore,true); assert.strictEqual(windowed.nextLimit,240);
const p=perf.profile(state,{raw:JSON.stringify(state),integratedEntries:first.length,quotaBytes:1024*1024*1024});
assert.strictEqual(p.schema,'sc-workspace-scale-profile/1.0'); assert.strictEqual(p.governance.canonicalMutation,false);
const crowded=perf.stressFixture({projects:121,objectsPerProject:101,notebooksPerProject:0,blocksPerNotebook:0});
const crowdedProfile=perf.profile(crowded,{raw:JSON.stringify(crowded),integratedEntries:0,quotaBytes:1024*1024*1024});
assert.ok(crowdedProfile.attention.includes('project-count')); assert.ok(crowdedProfile.attention.includes('object-count'));
const storageCritical=perf.pressure(33*1024*1024,40*1024*1024); assert.strictEqual(storageCritical.level,'critical');
state.projects[0].updatedAt='2026-08-10T01:00:00.000Z'; perf.deriveIntegrated(state,ik); assert.strictEqual(perf.cacheStats().misses,2,'project revision change invalidates derived cache');
const contract=perf.contract(); assert.strictEqual(contract.governance.noAutomaticDeletion,true); assert.strictEqual(contract.governance.noAutomaticCompaction,true);
console.log('PASS - Workspace v0.58.0 scale performance runtime');
