import json, unittest
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
MAN=json.loads((ROOT/'release-manifest-v0.66.0.json').read_text());REG=json.loads((ROOT/'registry/workspace-product-record-v0.66.0.json').read_text())
MAIN=(ROOT/'wordpress/sustainable-catalyst-workspace/sustainable-catalyst-workspace.php').read_text();PHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace.php').read_text();REGPHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace-registry.php').read_text();JS=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/workspace-v0.66.0.js').read_text();INTER=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-interchange-v2.js').read_text();CSS=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/css/workspace-v0.66.0.css').read_text()
class WorkspaceImportInterchange(unittest.TestCase):
 def test_01_lineage(self): self.assertEqual((MAN['version'],MAN['previous_version'],MAN['release_name']),('0.66.0','0.65.0','Import, Export & Backward-Compatibility Hardening'));self.assertIn('Version: 1.7.0',MAIN)
 def test_02_schema_stable(self): self.assertEqual((MAN['storage_schema_version'],MAN['project_schema'],MAN['export_schema']),(35,'sc-workspace-project/20.0','sc-workspace-project-export/20.0'));self.assertFalse(MAN['schema_migration_required']);self.assertTrue(MAN['migration']['schema_stable']);prev=json.loads((ROOT/'history/release-manifest-v0.46.1.json').read_text());self.assertTrue(prev['migration']['interchange_only_release']);self.assertFalse(prev['migration']['interchange_project_schema_change']);self.assertFalse(MAN['migration']['canonical_data_rewrite'])
 def test_03_contract_v2(self): self.assertIn('/wp-json/sc-workspace/v1/interoperability-contract',MAN['rest_routes']);self.assertIn("'schema' => 'sc-workspace-interoperability-contract/2.0'",PHP);self.assertIn("'interchange_export_schema' => 'sc-workspace-interchange/2.0'",PHP)
 def test_04_schemas(self):
  self.assertEqual(MAN['interchange_profile_schema'],'sc-workspace-interchange-profile/1.0');self.assertEqual(MAN['interchange_bundle_schema'],'sc-workspace-interchange/2.0');self.assertEqual(MAN['interchange_import_report_schema'],'sc-workspace-interchange-import-report/1.0')
  for n in ('sc-workspace-interchange-profile-v1.schema.json','sc-workspace-interchange-bundle-v2.schema.json','sc-workspace-interchange-import-report-v1.schema.json'): json.loads((ROOT/'schemas'/n).read_text())
 def test_05_profiles(self): self.assertEqual(MAN['interchange_v2']['profiles'],['workspace-json','obsidian-markdown','notion-csv','zotero-csl-json','portable-project']);self.assertIn('obsidian-markdown',INTER);self.assertIn('notion-csv',INTER);self.assertIn('zotero-csl-json',INTER)
 def test_06_runtime(self):
  for token in ('function workspaceJson','function obsidianMarkdown','function notionCsv','function zoteroCslJson','function detectProfile','function importDescriptors','function importReport','function exportProject'): self.assertIn(token,INTER)
 def test_07_ui(self): self.assertIn('data-scw-interoperability-export-profile',PHP);self.assertIn('Obsidian-ready Markdown',PHP);self.assertIn('Notion-style CSV',PHP);self.assertIn('Zotero / CSL JSON',PHP);self.assertIn('interoperabilityExportProfile',JS)
 def test_08_import_boundary(self): self.assertTrue(MAN['interchange_v2']['staged_review_required']);self.assertFalse(MAN['interchange_v2']['automatic_overwrite']);self.assertFalse(MAN['interchange_v2']['automatic_trust_elevation']);self.assertIn('Commit staged import',PHP);self.assertIn("sourceType:'imported'",JS)
 def test_09_external_boundary(self): self.assertFalse(MAN['interchange_v2']['external_network_lookup']);self.assertFalse(MAN['interchange_v2']['automatic_ai']);self.assertFalse(MAN['interchange_v2']['server_import_pipeline']);self.assertIn("'external_network_lookup' => false",PHP)
 def test_10_project_package_copy(self): self.assertEqual(MAN['interchange_v2']['portable_project_mode'],'import-as-new-local-copy');self.assertIn("profile==='portable-project'",JS);self.assertIn('portableProjectPackage(project',JS)
 def test_11_visual_alignment(self): self.assertEqual(MAN['governance']['editorial_header_rule_px'],4);self.assertIn('.scw-editorial-header-bar{height:4px',CSS);self.assertNotIn('.scw-editorial-header-bar{height:12px',CSS)
 def test_12_v045_retained(self): prev=json.loads((ROOT/'history/release-manifest-v0.45.0.json').read_text());self.assertTrue(prev['migration']['composition_studio_only_release']);self.assertIn('sc-workspace-composition-studio-v1.js',PHP);self.assertIn('function compositionApi()',JS)
 def test_13_registry(self): self.assertEqual((REG['public_version'],REG['previous_version']),('0.66.0','0.65.0'));self.assertIn("BACKUP_KEY = 'sc_workspace_registry_backup_v170'",REGPHP);self.assertIn('LEGACY_PENDING_KEY_V0460',REGPHP);self.assertIn('LEGACY_PENDING_KEY_V0450',REGPHP)
if __name__=='__main__': unittest.main()
