import json, unittest
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
MAN=json.loads((ROOT/'release-manifest-v0.45.0.json').read_text());REG=json.loads((ROOT/'registry/workspace-product-record-v0.45.0.json').read_text())
MAIN=(ROOT/'wordpress/sustainable-catalyst-workspace/sustainable-catalyst-workspace.php').read_text();PHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace.php').read_text();REGPHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace-registry.php').read_text();JS=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/workspace-v0.45.0.js').read_text();COMP=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-composition-studio-v1.js').read_text();CSS=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/css/workspace-v0.45.0.css').read_text()
class CompositionStudio(unittest.TestCase):
 def test_01_lineage(self): self.assertEqual((MAN['version'],MAN['previous_version'],MAN['release_name']),('0.45.0','0.44.0','Document & Research Composition Studio'));self.assertIn('Version: 0.45.0',MAIN)
 def test_02_schema_stable(self): self.assertEqual((MAN['storage_schema_version'],MAN['project_schema'],MAN['export_schema']),(35,'sc-workspace-project/20.0','sc-workspace-project-export/20.0'));self.assertTrue(MAN['migration']['schema_stable']);self.assertTrue(MAN['migration']['composition_studio_only_release']);self.assertFalse(MAN['migration']['composition_studio_project_schema_change']);self.assertFalse(MAN['migration']['canonical_data_rewrite'])
 def test_03_contract(self): self.assertIn('/wp-json/sc-workspace/v1/composition-studio-contract',MAN['rest_routes']);self.assertIn("'/composition-studio-contract'",PHP);self.assertIn('public function composition_studio_contract()',PHP)
 def test_04_schemas(self):
  self.assertEqual(MAN['composition_section_schema'],'sc-workspace-composition-section/1.0');self.assertEqual(MAN['composition_draft_schema'],'sc-workspace-composition-draft/1.0');self.assertEqual(MAN['composition_library_schema'],'sc-workspace-composition-library/1.0');self.assertEqual(MAN['composition_export_schema'],'sc-workspace-composition-export/1.0')
  for n in ('sc-workspace-composition-section-v1.schema.json','sc-workspace-composition-draft-v1.schema.json','sc-workspace-composition-library-v1.schema.json','sc-workspace-composition-export-v1.schema.json'): json.loads((ROOT/'schemas'/n).read_text())
 def test_05_runtime(self):
  for x in ('function sourceRef','function normalizeSection','function normalizeDraft','function addSource','function addCitation','function trace','function markdown','function documentPayload','function fingerprint','function exportPackage'): self.assertIn(x,COMP)
 def test_06_canonical_refs_no_copy(self): self.assertFalse(MAN['composition_studio']['copies_canonical_source_records']);self.assertIn('canonical pointers, not copies of source content',PHP);self.assertIn('Canonical research pointer attached',JS)
 def test_07_explicit_materialization(self): self.assertEqual(MAN['composition_studio']['materialization'],'explicit-workspace-document');self.assertFalse(MAN['composition_studio']['automatic_document_creation']);self.assertIn('data-scw-composition-materialize',PHP);self.assertIn("objectTemplate('document'",JS);self.assertIn('Composition materialized as Workspace Document',JS)
 def test_08_citation_boundary(self): self.assertEqual(MAN['composition_studio']['citation_source'],'citation-library-explicit-reference-selection');self.assertFalse(MAN['composition_studio']['citation_inference']);self.assertIn('data-scw-composition-attach-reference',PHP);self.assertIn('referenceLibrary.references.find',JS)
 def test_09_portable(self): self.assertTrue(MAN['composition_studio']['portable_export_import']);self.assertIn("STORAGE_KEY='sc_workspace_composition_library_v1'",COMP);self.assertIn('function fingerprint',COMP);self.assertIn('imported copy',JS)
 def test_10_governance(self):
  g=MAN['governance'];self.assertTrue(g['composition_studio_browser_local']);self.assertFalse(g['composition_studio_mutates_projects_automatically']);self.assertTrue(g['composition_studio_explicit_document_materialization']);self.assertFalse(g['composition_studio_copies_canonical_source_records']);self.assertFalse(g['composition_studio_citation_inference']);self.assertFalse(g['composition_studio_automatic_ai']);self.assertFalse(g['composition_studio_automatic_document_creation']);self.assertFalse(g['composition_studio_source_mutation']);self.assertTrue(g['composition_studio_authored_text_user_controlled']);self.assertTrue(g['composition_studio_traceability_visible'])
 def test_11_v044_retained(self): prev=json.loads((ROOT/'history/release-manifest-v0.44.0.json').read_text());self.assertTrue(prev['migration']['citation_library_only_release']);self.assertIn('sc-workspace-reference-library-v1.js',PHP);self.assertIn('function referenceLibraryApi()',JS)
 def test_12_registry(self): self.assertEqual((REG['public_version'],REG['previous_version']),('0.45.0','0.44.0'));self.assertIn("BACKUP_KEY = 'sc_workspace_registry_backup_v0450'",REGPHP);self.assertIn('LEGACY_PENDING_KEY_V0440',REGPHP);self.assertTrue((ROOT/'history/release-manifest-v0.44.0.json').exists());self.assertTrue((ROOT/'history/workspace-product-record-v0.44.0.json').exists())
if __name__=='__main__':unittest.main()
