import json, unittest
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
MAN=json.loads((ROOT/'release-manifest-v0.66.0.json').read_text())
REG=json.loads((ROOT/'registry/workspace-product-record-v0.66.0.json').read_text())
JS=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/workspace-v0.66.0.js').read_text()
HELPER=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-research-notebook-v8.js').read_text()
PHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace.php').read_text()
CSS=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/css/workspace-v0.66.0.css').read_text()
MAIN=(ROOT/'wordpress/sustainable-catalyst-workspace/sustainable-catalyst-workspace.php').read_text()
REGPHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace-registry.php').read_text()
class ResearchNotebookContract(unittest.TestCase):
 def test_01_lineage(self): self.assertEqual((MAN['version'],MAN['previous_version'],MAN['release_name']),('0.66.0','0.65.0','Import, Export & Backward-Compatibility Hardening'))
 def test_02_schema_migration(self): self.assertEqual((MAN['storage_schema_version'],MAN['project_schema'],MAN['export_schema']),(35,'sc-workspace-project/20.0','sc-workspace-project-export/20.0')); self.assertFalse(MAN['schema_migration_required']); self.assertEqual((MAN['migration']['storage_from'],MAN['migration']['storage_to']),(35,35)); self.assertTrue(MAN['migration']['project_schema_unchanged'])
 def test_03_notebook_schemas(self): self.assertEqual(MAN['notebook_workspace_schema'],'sc-workspace-notebook-workspace/8.0'); self.assertEqual(MAN['notebook_schema'],'sc-workspace-notebook/3.0'); self.assertEqual(MAN['notebook_block_schema'],'sc-workspace-notebook-block/3.0'); self.assertEqual(MAN['notebook_export_schema'],'sc-workspace-notebook-export/8.0')
 def test_04_schema_files(self):
  for name in ('sc-workspace-notebook-block-v2.schema.json','sc-workspace-notebook-v2.schema.json','sc-workspace-notebook-workspace-v2.schema.json','sc-workspace-project-v14.schema.json'): json.loads((ROOT/'schemas'/name).read_text())
 def test_05_block_types(self): self.assertEqual(MAN['research_notebook']['block_types'],['note','source','excerpt','question','claim','reference','checklist','divider','attachment'])
 def test_06_limits(self): self.assertEqual(MAN['research_notebook']['limits'],{'notebooks_per_project':30,'sections_per_notebook':40,'blocks_per_notebook':300,'blocks_per_project':600}); self.assertIn('MAX_NOTEBOOK_BLOCKS_PER_PROJECT = 600',JS)
 def test_07_explicit_promotion(self): self.assertTrue(MAN['research_notebook']['promotion_explicit']); self.assertTrue(MAN['research_notebook']['promotion_preserves_original_block']); self.assertFalse(MAN['research_notebook']['automatic_promotion']); self.assertIn('promoteNotebookBlock',JS)
 def test_08_promotion_mapping(self): self.assertEqual(MAN['research_notebook']['promotion_mapping']['excerpt'],'Evidence object'); self.assertEqual(MAN['research_notebook']['promotion_mapping']['source'],'Source object'); self.assertEqual(MAN['research_notebook']['promotion_mapping']['question'],'Analysis object'); self.assertEqual(MAN['research_notebook']['promotion_mapping']['claim'],'Analysis object')
 def test_09_no_ai_requirement(self): self.assertFalse(MAN['research_notebook']['automatic_ai']); self.assertFalse(MAN['research_notebook']['ai_required']); self.assertFalse(MAN['governance']['notebook_automatic_ai']); self.assertFalse(MAN['governance']['notebook_automatic_link_inference']); self.assertIn('No AI',PHP)
 def test_10_rest_contract(self): self.assertIn('/wp-json/sc-workspace/v1/notebook-contract',MAN['rest_routes']); self.assertIn("'/notebook-contract'",PHP); self.assertIn('public function notebook_contract()',PHP)
 def test_11_ui_surface(self): self.assertIn('data-scw-workspace-view="notebook"',PHP); self.assertIn('data-scw-workspace-section="notebook"',PHP); self.assertIn('data-scw-notebook-create-form',PHP); self.assertIn('data-scw-notebook-block-form',PHP); self.assertIn('.scw-research-notebook',CSS)
 def test_12_object_capture(self): self.assertIn('data-scw-object-to-notebook',PHP); self.assertIn('Add to Notebook',PHP); self.assertIn('objectToNotebook',JS)
 def test_13_migration_runtime(self): self.assertIn('function migrateV27(raw)',JS); self.assertIn('if (raw.schemaVersion === 27) return migrateV27(raw);',JS); self.assertIn("const LEGACY_PROJECT_SCHEMA_V12 = 'sc-workspace-project/12.0'",JS); self.assertIn('notebooks: notebookWorkspaceTemplate()',JS)
 def test_14_project_boundary(self): self.assertTrue(MAN['research_notebook']['project_bound']); self.assertTrue(MAN['research_notebook']['account_backup_inherits_project_boundary']); self.assertTrue(MAN['research_notebook']['cross_device_sync_inherits_project_boundary']); self.assertTrue(MAN['research_notebook']['restore_points_include_notebooks'])
 def test_15_helper_contract(self): self.assertIn('sc-workspace-notebook-workspace/8.0',HELPER); self.assertIn('exportNotebook',HELPER); self.assertIn("case'excerpt':return'evidence'",HELPER.replace(' ','')); self.assertIn("case'question':case'claim':return'analysis'",HELPER.replace(' ',''))
 def test_16_registry_and_plugin(self): self.assertEqual(REG['public_version'],'0.66.0'); self.assertEqual(REG['previous_version'],'0.65.0'); self.assertIn('Import, Export & Backward-Compatibility Hardening',REG['change_summary']); self.assertIn('Version: 1.8.0',MAIN); self.assertIn("BACKUP_KEY = 'sc_workspace_registry_backup_v180'",REGPHP); self.assertIn('LEGACY_PENDING_KEY_V0320',REGPHP)
 def test_17_history_and_library(self): self.assertTrue((ROOT/'history/release-manifest-v0.32.0.json').exists()); self.assertTrue((ROOT/'history/workspace-product-record-v0.32.0.json').exists()); self.assertEqual(MAN['canonical_library_path'],'/knowledge-libraries/'); self.assertIn('/knowledge-libraries/',PHP)
if __name__=='__main__': unittest.main()
