const assert=require('assert');
const A=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-security-privacy-audit-ii-v1.js');
class Store{constructor(seed={}){this.m=new Map(Object.entries(seed));}get length(){return this.m.size;}key(i){return [...this.m.keys()][i]??null;}getItem(k){return this.m.has(k)?this.m.get(k):null;}setItem(k,v){this.m.set(k,String(v));}removeItem(k){this.m.delete(k);}}
const local=new Store({sc_workspace:JSON.stringify({projects:[{id:'private-project',title:'Private title'}]}),sc_workspace_last_good_v1:'private recovery bytes',sc_workspace_future_private_v9:'secret-ish content',unrelated_key:'leave'});
const session=new Store({sc_workspace_public_beta_iii_journey_v0700:'{"reviewed":["capture"]}',other:'x'});
const report=A.buildReport(local,session,{protocol:'https:',isSecureContext:true,topEqualsSelf:true,cookieEnabled:true,crossOriginIsolated:false,referrerPresent:true},{cookieString:'wordpress_logged_in_x=opaque; scw_example=do-not-export',workspaceVersion:'0.77.0',now:'2026-08-11T21:20:00-05:00'});
assert.equal(report.schema,A.REPORT_SCHEMA);assert.equal(report.workspaceVersion,'0.77.0');assert.equal(report.storage.local.count,3);assert.equal(report.storage.session.count,1);assert.equal(report.storage.local.unknown,1);assert.equal(report.cookies.accessibleWorkspaceCookieCount,1);assert.equal(report.cookies.cookieNamesIncluded,false);assert.equal(report.cookies.cookieValuesIncluded,false);assert.equal(report.browser.referrerIncluded,false);assert.equal(report.exclusions.projectContent,true);assert.equal(report.exclusions.storageValues,true);assert.equal(report.exclusions.storageKeyNames,true);assert.equal(report.exclusions.accountIdentity,true);assert.equal(report.governance.telemetry,false);assert(!JSON.stringify(report).includes('Private title'));assert(!JSON.stringify(report).includes('private-project'));assert(!JSON.stringify(report).includes('scw_example'));assert(!JSON.stringify(report).includes('do-not-export'));
const bad=A.buildReport(local,session,{protocol:'http:',isSecureContext:false,topEqualsSelf:false,cookieEnabled:true,crossOriginIsolated:false,referrerPresent:false},{workspaceVersion:'0.77.0'});assert(bad.findings.some(x=>x.code==='insecure-context'));assert(bad.findings.some(x=>x.code==='embedded-context'));assert.equal(A.contract().nonClaims.sourceAuditIsPenetrationTest,false);assert.equal(A.contract().governance.schemaMigrationRequired,false);
console.log('PASS - v0.77.0 Security & Privacy Audit II runtime');
