const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const path = require('path');
const src = fs.readFileSync(path.join(__dirname,'../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-public-beta-v1.js'),'utf8');
const sandbox = { console };
vm.createContext(sandbox); vm.runInContext(src, sandbox);
const beta = sandbox.SCWorkspacePublicBeta;
assert(beta, 'helper exported');
assert.strictEqual(beta.SCHEMA,'sc-workspace-public-beta-readiness/1.0');
assert.deepStrictEqual(Array.from(beta.quickStarts()).map(x=>x.id),['research-investigation','analytical-assessment','decision-case','publication-preparation']);
const state={projects:[{id:'p1',title:'Older',updatedAt:'2026-08-08T00:00:00Z',objects:[{id:'o1'}],lifecycle:{state:'analysis-ready',milestones:[{}]}},{id:'p2',title:'Newer',updatedAt:'2026-08-09T00:00:00Z',objects:[],lifecycle:{state:'draft',milestones:[]}},{id:'p3',title:'Archived',archivedAt:'x',objects:[{id:'x'}]}],versionHistory:{restorePoints:[{},{}]},safeActions:{history:[{}]},reconciliation:{receipts:[{},{}]},crossDeviceSync:{enrollments:[{}]}};
const summary=beta.summary(state);
assert.strictEqual(summary.projectCount,2); assert.strictEqual(summary.objectCount,1); assert.strictEqual(summary.milestoneCount,1); assert.strictEqual(summary.restorePointCount,2); assert.strictEqual(summary.recentProjects[0].title,'Newer');
assert.strictEqual(summary.governance.hiddenScore,false); assert.strictEqual(summary.governance.automaticCloudUpload,false); assert.strictEqual(summary.governance.automaticTelemetry,false);
const memory={}; const localStorage={setItem:(k,v)=>memory[k]=v,removeItem:k=>delete memory[k]};
const env={window:{localStorage,sessionStorage:{},File:function(){},FileReader:function(){},Blob:function(){},postMessage(){},matchMedia(){return {matches:true}}},crypto:{subtle:{}},navigator:{onLine:true}};
const caps=beta.capabilities(env); assert.strictEqual(caps.localStorage,true); assert.strictEqual(caps.webCryptoSha256,true); assert.strictEqual(caps.fileApi,true); assert.strictEqual(caps.postMessage,true); assert.strictEqual(caps.reducedMotion,true);
const ready=beta.readiness(caps); assert.strictEqual(ready.state,'ready'); assert.strictEqual(ready.hiddenScore,false); assert.strictEqual(ready.crossProductReturnReady,true);
const limited=beta.readiness({localStorage:false,sessionStorage:true,fileApi:true}); assert.strictEqual(limited.state,'limited');
console.log('PASS - Workspace v0.30.0 public beta runtime');
