const assert=require('assert');
const H=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-product-help-v1.js');
assert.equal(H.SCHEMA,'sc-workspace-product-help/1.0');
assert.equal(H.topics().length,10);
assert.equal(H.search('sync conflict')[0].id,'sync-conflict');
assert.equal(H.guidanceFor('storage-write-failed').id,'save-failed');
assert.equal(H.guidanceFor('future-version').id,'import-rejected');
assert.equal(H.topic('move-device').route,'interoperability');
const report=H.report({workspaceVersion:'0.76.0',view:'help',topicId:'restore'},()=> '2026-08-11T20:50:00-05:00');
assert.equal(report.schema,'sc-workspace-product-help-report/1.0');
assert.equal(report.context.topicId,'restore');
assert.equal(report.privacy.projectContentIncluded,false);
assert.equal(report.privacy.sourceUrlsIncluded,false);
assert.equal(report.privacy.deviceIdentifierIncluded,false);
assert.equal(report.governance.advisoryOnly,true);
assert.equal(report.governance.canonicalMutation,false);
assert.equal(report.governance.automaticRecovery,false);
assert.equal(report.governance.automaticRestore,false);
assert.equal(report.governance.automaticUpload,false);
assert.equal(report.governance.telemetry,false);
console.log('PASS - v0.76.0 documentation, recovery guidance & product help runtime');
