const assert=require('assert');
const api=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-collaboration-architecture-v1.js');
let n=0; const id=p=>`${p}-${++n}`; let t=0; const now=()=>`2026-08-10T20:40:${String(t++).padStart(2,'0')}Z`;
const owner=api.createActor({displayName:'Owner',role:'owner'},id,now);
const reviewer=api.createActor({displayName:'Reviewer',role:'reviewer'},id,now);
assert(owner&&reviewer);
let policy=api.createPolicy('project-1',owner.id,id,now);
policy=api.setGrant(policy,reviewer.id,'reviewer',owner.id,now);
assert.equal(api.effectiveRole(policy,owner.id),'owner');
assert.equal(api.effectiveRole(policy,reviewer.id),'reviewer');
assert(api.can(policy,reviewer.id,'comment'));
assert(!api.can(policy,reviewer.id,'manage-policy'));
const projects=[{id:'project-1',title:'Project One',updatedAt:'2026-08-10T20:00:00Z',archivedAt:null,objects:[{id:'object-1',title:'Evidence A',type:'evidence',archivedAt:null,content:'CANONICAL CONTENT MUST NOT BE COPIED'}]}];
const target={kind:'object',projectId:'project-1',objectId:'object-1',objectTitle:'Evidence A'};
const comment=api.createComment({actorId:reviewer.id,body:'Please verify this evidence.'},target,id,now);
assert(comment&&comment.body.includes('verify'));
assert(api.resolveTarget(comment.target,projects).resolved);
const proposal=api.createProposal({actorId:reviewer.id,kind:'replace-field',field:'summary',proposedValue:'Proposed wording',rationale:'Clearer.'},target,id,now);
assert(proposal);
const accepted=api.transitionProposal(proposal,'accepted',owner.id,'Reviewed',now);
assert(accepted.ok); assert.equal(accepted.proposal.status,'accepted'); assert.strictEqual(accepted.canonicalMutation,false);
const contract=api.buildShareableProjectContract(projects[0],policy,[owner,reviewer],['object-1'],'0.53.0');
assert.equal(contract.schema,api.SHAREABLE_PROJECT_SCHEMA);
assert.equal(contract.governance.projectContentIncluded,false);
assert(!JSON.stringify(contract).includes('CANONICAL CONTENT MUST NOT BE COPIED'));
const library=api.normalizeArchitecture({actors:[owner,reviewer],policies:[policy],comments:[comment],proposals:[accepted.proposal]});
const pkg=api.exportArchitecture(library); const imported=api.importArchitecture(pkg); assert(imported.ok); assert.equal(imported.architecture.actors.length,2);
const bad=JSON.parse(JSON.stringify(pkg)); bad.architecture.actors[0].displayName='Tampered'; assert(!api.importArchitecture(bad).ok);
assert.equal(api.stats(library,projects).openComments,1);
console.log('PASS - v0.53.0 Collaboration Architecture runtime');
