import json,re,unittest
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
MAN=json.loads((ROOT/'release-manifest-v0.66.0.json').read_text());REG=json.loads((ROOT/'registry/workspace-product-record-v0.66.0.json').read_text())
MAIN=(ROOT/'wordpress/sustainable-catalyst-workspace/sustainable-catalyst-workspace.php').read_text();PHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace.php').read_text();REGPHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace-registry.php').read_text();JS=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/workspace-v0.66.0.js').read_text();HELP=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-collaboration-architecture-v1.js').read_text();CSS=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/css/workspace-v0.66.0.css').read_text()
class TestCollaborationArchitectureFoundation(unittest.TestCase):
 def test_01_lineage(self): self.assertEqual((MAN['version'],MAN['previous_version'],MAN['release_name']),('0.66.0','0.65.0','Import, Export & Backward-Compatibility Hardening'));self.assertIn('Version: 1.3.0',MAIN)
 def test_02_schema_stable(self): self.assertEqual(MAN['storage_schema_version'],35);self.assertEqual(MAN['project_schema'],'sc-workspace-project/20.0');self.assertFalse(MAN['schema_migration_required'])
 def test_03_schemas(self): self.assertEqual(MAN['collaboration_architecture_schema'],'sc-workspace-collaboration-architecture/1.0');self.assertEqual(MAN['shareable_project_contract_schema'],'sc-workspace-shareable-project-contract/1.0');self.assertTrue((ROOT/'schemas/sc-workspace-collaboration-policy-v1.schema.json').exists())
 def test_04_roles_and_capabilities(self): self.assertIn("'editor'",HELP);self.assertIn("'reviewer'",HELP);self.assertIn("'manage-policy'",HELP);self.assertIn('capabilitiesForRole',HELP)
 def test_05_explicit_ownership(self): self.assertIn('ownerActorId',HELP);self.assertIn('data-scw-collab-owner',PHP);self.assertTrue(MAN['governance']['collaboration_project_ownership_explicit'])
 def test_06_comments_reference_targets(self): self.assertIn('normalizeTarget',HELP);self.assertIn('data-scw-collab-comment-form',PHP);self.assertTrue(MAN['governance']['collaboration_comments_canonical_pointers_only'])
 def test_07_proposals_do_not_apply(self): self.assertIn('canonicalMutation:false',HELP);self.assertFalse(MAN['governance']['collaboration_proposal_acceptance_mutates_canonical']);self.assertIn('Canonical project content was NOT changed',JS)
 def test_08_shareable_contract_no_content(self): self.assertIn('projectContentIncluded:false',HELP);self.assertFalse(MAN['governance']['shareable_project_contract_includes_project_content']);self.assertIn('data-scw-collab-contract-export',PHP)
 def test_09_no_server_permissions(self): self.assertFalse(MAN['governance']['collaboration_policy_grants_server_access']);self.assertFalse(MAN['governance']['shareable_project_contract_creates_server_permissions']);self.assertFalse(MAN['governance']['live_project_collaboration'])
 def test_10_rest_and_enqueue(self): self.assertIn("'/collaboration-architecture-contract'",PHP);self.assertIn('public function collaboration_architecture_contract()',PHP);self.assertIn('sc-workspace-collaboration-architecture-v1.js',PHP);self.assertIn('/wp-json/sc-workspace/v1/collaboration-architecture-contract',MAN['rest_routes'])
 def test_11_registry(self): self.assertEqual((REG['public_version'],REG['previous_version']),('0.66.0','0.65.0'));self.assertIn("BACKUP_KEY = 'sc_workspace_registry_backup_v130'",REGPHP);self.assertIn('LEGACY_PENDING_KEY_V0520',REGPHP)
 def test_12_header_retained(self): self.assertEqual(MAN['governance']['editorial_header_rule_px'],4);self.assertRegex(CSS,r'\.scw-editorial-header-bar\{height:4px')
 def test_13_history_retained(self): self.assertTrue((ROOT/'history/release-manifest-v0.52.0.json').exists());self.assertTrue((ROOT/'history/workspace-product-record-v0.52.0.json').exists())
if __name__=='__main__':unittest.main()
