const assert=require('assert');
const signoff=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-production-signoff-v1.js');
global.SCWorkspaceProductionSignoff=signoff;
const api=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-ga-readiness-v1.js');
assert.strictEqual(api.RELEASE_VERSION,'0.84.0');
assert.strictEqual(api.PREVIOUS_RELEASE,'0.83.0');
assert.strictEqual(api.ROLLBACK_RELEASE,'0.83.0');
assert.strictEqual(api.PRODUCTION_SIGNOFF_RELEASE,'0.83.0');
assert.strictEqual(api.REQUIREMENTS.length,9);
let prod=signoff.blank();
prod.reviewerLabel='Production reviewer';prod.productionUrl='https://sustainablecatalyst.com/platform/';prod.attestation=true;
for(const item of signoff.REQUIREMENTS)prod.checks[item.id]=true;
prod=signoff.complete(prod,'2026-08-14T21:30:00.000Z').record;
const cert=signoff.certificate(prod);
assert.strictEqual(api.validProductionCertificate(cert),true);
let r=api.blank();
assert.strictEqual(api.evaluate(r,cert).ready,false);
r.releaseOwner='Release owner';r.productionUrl='https://sustainablecatalyst.com/platform/';r.attestation=true;
for(const item of api.REQUIREMENTS)if(item.id!=='production-signoff-certificate')r.checks[item.id]=true;
const done=api.complete(r,cert,'2026-08-14T21:35:00.000Z');
assert.strictEqual(done.evaluation.ready,true);
const dossier=api.dossier(done.record,cert);
assert.strictEqual(dossier.readyForOneDotZeroDecision,true);
assert.strictEqual(dossier.automaticPromotionToOneDotZero,false);
assert.strictEqual(dossier.projectContentIncluded,false);
assert.strictEqual(dossier.telemetry,false);
console.log('PASS - v0.84.0 GA readiness runtime');
