const assert=require('assert');const A=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-review-rooms-v1.js');
let seq=0;const id=p=>`${p}-${++seq}`,now=()=>`2026-08-15T12:00:${String(seq).padStart(2,'0')}Z`;
let room=A.createRoom({projectId:'p1',title:'Evidence review',purpose:'Challenge evidence',ownerActorId:'a1',scopeObjectIds:['o1']},id,now);assert(room);assert.equal(room.state,'draft');assert.equal(A.roleFor(room,'a1'),'owner');
let x=A.invite(room,{actorId:'a2',displayName:'Reviewer',role:'reviewer',invitedByActorId:'a1'},id,now);assert(x.ok);room=x.room;assert.equal(room.invitations.length,1);assert.equal(x.automaticExternalSend,false);assert.equal(x.serverPermissionGrant,false);
const project={id:'p1',updatedAt:'2026-08-15T11:00:00Z',objects:[{id:'o1',type:'evidence',title:'Evidence A',content:'frozen'},{id:'o2',type:'source',title:'Source B'}]};x=A.freezeSnapshot(room,project,'1.8.0','a1',id,now);assert(x.ok);room=x.room;assert.equal(room.state,'open');assert.deepEqual(room.snapshot.objectIds,['o1']);assert(room.snapshot.fingerprint);project.objects[0].content='changed';assert.equal(room.snapshot.objects[0].content,'frozen');
x=A.addComment(room,'a2','Needs a stronger source.','o1',id,now);assert(x.ok);room=x.room;assert.equal(room.state,'in-review');assert.equal(x.canonicalMutation,false);
x=A.setState(room,'changes-requested','a2','Please revise.',id,now);assert(x.ok);room=x.room;assert.equal(room.state,'changes-requested');
x=A.setState(room,'closed','a2','',id,now);assert.equal(x.ok,false);x=A.setState(room,'approved','a1','Owner reviewed.',id,now);assert(x.ok);room=x.room;
const pkg=A.exportRoom(room,{a1:'Owner',a2:'Reviewer'},'1.8.0');assert.equal(pkg.schema,A.EXPORT_SCHEMA);assert(pkg.fingerprint);assert.equal(pkg.governance.serverAclCreated,false);assert.equal(pkg.governance.automaticCanonicalMutation,false);const imp=A.importRoom(pkg);assert(imp.ok);assert.equal(imp.staged,true);assert.equal(imp.canonicalMutation,false);console.log('PASS - v1.8.0 shared review rooms JS runtime');
