const assert=require('assert');
const I=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-interchange-v2.js');
assert.equal(I.BUNDLE_SCHEMA,'sc-workspace-interchange/2.0');
const project={id:'p1',title:'Grid Research',description:'Research project',objects:[{id:'s1',type:'source',status:'ready',title:'Grid Source',summary:'Source summary',content:'Source notes',tags:['grid'],provenance:{sourceType:'web',sourceTitle:'Grid Source',sourceUrl:'https://example.test/grid',capturedAt:'2026-01-01T00:00:00Z'},bibliographic:{authors:['Jane Smith'],publicationDate:'2025',doi:'10.1000/grid'}},{id:'e1',type:'evidence',status:'working',title:'Grid Evidence',summary:'Evidence summary',content:'Evidence body',tags:['reliability'],provenance:{sourceType:'manual',sourceTitle:'Review',sourceUrl:'',capturedAt:'2026-01-02T00:00:00Z'}}],traceability:{lineage:[{relation:'supports',fromObjectId:'e1',toObjectId:'s1',note:'Recorded relation'}]}};
const w=I.exportProject(project,'workspace-json','0.46.0');assert.equal(w.data.schema,I.BUNDLE_SCHEMA);assert.equal(w.data.relationships.length,1);
const md=I.exportProject(project,'obsidian-markdown','0.46.0');assert(md.data.includes('workspace_project_id'));assert(md.data.includes('Grid Evidence'));
const csv=I.exportProject(project,'notion-csv','0.46.0');assert(csv.data.includes('Workspace Object ID'));assert(csv.data.includes('Grid Source'));
const csl=I.exportProject(project,'zotero-csl-json','0.46.0');const refs=JSON.parse(csl.data);assert.equal(refs[0].title,'Grid Source');
assert.equal(I.detectProfile('markdown','---\ntitle: "Note"\ntags: [grid]\n---\nBody','note.md'),'obsidian-markdown');
const obs=I.importDescriptors('obsidian-markdown','---\ntitle: "Imported Note"\ntags: [grid]\nsource: "https://example.test"\n---\nBody','note.md');assert.equal(obs[0].title,'Imported Note');assert.equal(obs[0].sourceUrl,'https://example.test');
const notion=I.importDescriptors('notion-csv','Name,Workspace Type,Tags,URL,Notes\nRow,evidence,"grid, test",https://example.test,Observed','notion.csv');assert.equal(notion[0].type,'evidence');assert.equal(notion[0].title,'Row');
const zot=I.importDescriptors('zotero-csl-json',JSON.stringify([{id:'z1',type:'article-journal',title:'Paper',author:[{given:'A',family:'Author'}],DOI:'10.1/test',URL:'https://example.test/paper'}]),'refs.csl.json');assert.equal(zot[0].type,'source');assert(zot[0].content.includes('DOI: 10.1/test'));
const report=I.importReport('notion-csv','notion.csv','abc',notion);assert.equal(report.reviewRequired,true);assert.equal(report.automaticOverwrite,false);
console.log('PASS - v0.46.0 Workspace Import & Interchange runtime');
