const assert = require('assert');
const nb = require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-research-notebook-v1.js');
let n = 0;
const id = prefix => `${prefix}-${++n}`;
const now = () => '2026-08-09T23:30:00.000Z';

assert.strictEqual(nb.WORKSPACE_SCHEMA, 'sc-workspace-notebook-workspace/1.0');
assert.strictEqual(nb.NOTEBOOK_SCHEMA, 'sc-workspace-notebook/1.0');
assert.strictEqual(nb.BLOCK_SCHEMA, 'sc-workspace-notebook-block/1.0');
assert.strictEqual(nb.EXPORT_SCHEMA, 'sc-workspace-notebook-export/1.0');
assert.deepStrictEqual(nb.BLOCK_TYPES, ['note','source','excerpt','question','claim','reference','checklist','divider','attachment']);
assert.deepStrictEqual(nb.LIMITS, { notebooksPerProject:30, sectionsPerNotebook:40, blocksPerNotebook:300, blocksPerProject:600 });

const ws = nb.workspace(null, id, now);
assert.strictEqual(ws.notebooks.length, 0);
const notebook = nb.createNotebook('Grid Research', 'Working notes', id, now);
assert.strictEqual(notebook.sections.length, 1);
assert.strictEqual(notebook.sections[0].title, 'Notes');
const section = nb.createSection('Core Sources', id, now);
notebook.sections.push(section);
const block = nb.createBlock('excerpt', {title:'Reliability finding', content:'Quoted research passage', sourceUrl:'https://example.org/report', tags:['grid','reliability']}, id, now);
section.blocks.push(block);
ws.notebooks.push(notebook); ws.activeNotebookId = notebook.id;
assert.strictEqual(nb.blockCount(ws), 1);
assert.strictEqual(nb.promotionTarget('excerpt'), 'object');
assert.strictEqual(nb.promotionObjectType('excerpt'), 'evidence');
assert.strictEqual(nb.promotionTarget('question'), 'research-question');
assert.strictEqual(nb.promotionTarget('claim'), 'research-claim');
assert.strictEqual(nb.promotionTarget('reference'), '');
const original = JSON.stringify(ws);
const exported = nb.exportNotebook(notebook, {id:'scwp-1',title:'Grid Project'}, '0.32.0');
assert.strictEqual(exported.schema, 'sc-workspace-notebook-export/1.0');
assert.strictEqual(exported.project.id, 'scwp-1');
assert.strictEqual(exported.notebook.title, 'Grid Research');
assert.strictEqual(JSON.stringify(ws), original, 'export must not mutate notebook state');
const arr=['a','b','c']; assert.strictEqual(nb.move(arr,1,-1),true); assert.deepStrictEqual(arr,['b','a','c']);
const normalized = nb.workspace(JSON.parse(JSON.stringify(ws)), id, now);
assert.strictEqual(normalized.notebooks[0].sections[1].blocks[0].type, 'excerpt');
console.log('PASS - Workspace v0.32.0 Research Notebook runtime');
