const assert=require('assert');
const api=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-shared-review-handoff-v1.js');
const collab=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-collaboration-architecture-v1.js');
let n=0;const id=p=>`${p}-${++n}`;let t=0;const now=()=>`2026-08-11T23:00:${String(t++).padStart(2,'0')}Z`;
const owner=collab.createActor({displayName:'Owner',role:'owner'},id,now),reviewer=collab.createActor({displayName:'Reviewer',role:'reviewer'},id,now);let policy=collab.createPolicy('p1',owner.id,id,now);policy=collab.setGrant(policy,reviewer.id,'reviewer',owner.id,now);
const architecture=collab.normalizeArchitecture({actors:[owner,reviewer],policies:[policy],comments:[],proposals:[]});
const project={id:'p1',title:'Review Project',updatedAt:'2026-08-11T22:00:00Z',archivedAt:null,objects:[{id:'o1',type:'evidence',title:'Evidence A',summary:'Summary A',content:'Frozen source material',status:'reviewed',tags:['a'],provenance:{sourceTitle:'Source A'},updatedAt:'2026-08-11T22:00:00Z',archivedAt:null}]};
const handoff=api.createHandoff({title:'External review',purpose:'Check evidence.',reviewerActorIds:[reviewer.id],scopeObjectIds:['o1']},project,policy,id,now);assert(handoff);
const pkg=api.buildReviewPackage(handoff,project,architecture,'0.73.0',now);assert(pkg.sourceRevision.fingerprint);assert.equal(pkg.governance.staleResponseRequiresOwnerAcknowledgement,true);assert.equal(pkg.governance.duplicateResponseCommitBlocked,true);assert.equal(pkg.governance.ownerIdentityCryptographicallyVerified,false);
const response=api.createResponse(pkg,{actorId:reviewer.id,decision:'changes-requested',summary:'Please verify.',comments:[{target:{kind:'object',projectId:'p1',objectId:'o1',objectTitle:'Evidence A'},body:'Verify source.'}],proposals:[]},id,now);assert(response);assert.equal(response.sourceRevisionFingerprint,pkg.sourceRevision.fingerprint);
let receiptLedger=api.normalizeReceiptLedger({});
const current=api.assessResponseImport(handoff,response,pkg,project,receiptLedger);assert.equal(current.ok,true);assert.equal(current.sourceState,'current');assert.equal(current.requiresOwnerAcknowledgement,false);assert.equal(current.commitAllowed,true);
let committed=api.commitResponseHardened(architecture,handoff,response,pkg,project,receiptLedger,collab,{ownerAcknowledged:false},id,now);assert.equal(committed.ok,true);assert(committed.receipt);assert.equal(committed.receipt.sourceState,'current');assert.equal(committed.receipt.ownerAcknowledged,false);
receiptLedger=api.addReceipt(receiptLedger,committed.receipt,now);assert.equal(receiptLedger.receipts.length,1);
const dup=api.assessResponseImport(handoff,response,pkg,project,receiptLedger);assert.equal(dup.ok,false);assert.equal(dup.duplicate,true);assert.equal(dup.commitAllowed,false);
const changed=JSON.parse(JSON.stringify(project));changed.updatedAt='2026-08-11T22:30:00Z';changed.objects[0].content='Changed after package';changed.objects[0].updatedAt='2026-08-11T22:30:00Z';
const response2=api.createResponse(pkg,{actorId:reviewer.id,decision:'approved',summary:'Second response.',comments:[],proposals:[{target:{kind:'object',projectId:'p1',objectId:'o1',objectTitle:'Evidence A'},kind:'custom',proposedValue:'Add note',rationale:'Follow-up'}]},id,now);assert(response2);
const stale=api.assessResponseImport(handoff,response2,pkg,changed,receiptLedger);assert.equal(stale.ok,true);assert.equal(stale.sourceState,'stale');assert.equal(stale.requiresOwnerAcknowledgement,true);assert.equal(stale.commitAllowed,false);
const blocked=api.commitResponseHardened(committed.architecture,handoff,response2,pkg,changed,receiptLedger,collab,{ownerAcknowledged:false},id,now);assert.equal(blocked.ok,false);assert.match(blocked.message,/Owner acknowledgement/);
const allowed=api.commitResponseHardened(committed.architecture,handoff,response2,pkg,changed,receiptLedger,collab,{ownerAcknowledged:true},id,now);assert.equal(allowed.ok,true);assert.equal(allowed.receipt.sourceState,'stale');assert.equal(allowed.receipt.ownerAcknowledged,true);assert.strictEqual(allowed.canonicalMutation,false);assert.strictEqual(allowed.proposalAcceptanceAppliesChange,false);
const legacy=JSON.parse(JSON.stringify(pkg));delete legacy.sourceRevision;delete legacy.fingerprint;legacy.fingerprint=api.fnv1a(JSON.stringify(legacy));
const legacyResponse=api.createResponse(legacy,{actorId:reviewer.id,decision:'no-decision',summary:'Legacy package response.',comments:[],proposals:[]},id,now);assert(legacyResponse);
const legacyAssessment=api.assessResponseImport(handoff,legacyResponse,legacy,project,{receipts:[]});assert.equal(legacyAssessment.sourceState,'legacy-unverifiable');assert.equal(legacyAssessment.requiresOwnerAcknowledgement,true);
assert.equal(api.createResponse(pkg,{actorId:'not-a-reviewer',summary:'Nope'},id,now),null);
console.log('PASS - v0.73.0 collaboration & shared review hardening runtime');
