import json, pathlib, unittest
ROOT=pathlib.Path(__file__).resolve().parents[1]
MAN=json.loads((ROOT/'release-manifest-v0.64.1.json').read_text())
REG=json.loads((ROOT/'registry/workspace-product-record-v0.64.1.json').read_text())
MAIN=(ROOT/'wordpress/sustainable-catalyst-workspace/sustainable-catalyst-workspace.php').read_text()
PHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace.php').read_text()
REGPHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace-registry.php').read_text()
APP=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/workspace-v0.64.1.js').read_text()
HELP=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-persistence-integrity-v1.js').read_text()
UI=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-persistence-integrity-ui-v1.js').read_text()
CSS=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/css/workspace-v0.64.1.css').read_text()
NAV=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-research-navigation-v1.js').read_text()
class T(unittest.TestCase):
 def test_01_lineage(self): self.assertEqual((MAN['version'],MAN['previous_version'],MAN['release_name']),('0.64.1','0.64.0','Accessibility Runtime & Desktop Layout Recovery'));self.assertIn('Version: 0.64.1',MAIN)
 def test_02_schema_stable(self): self.assertEqual(MAN['storage_schema_version'],35);self.assertEqual(MAN['project_schema'],'sc-workspace-project/20.0');self.assertFalse(MAN['schema_migration_required'])
 def test_03_schemas(self):
  for n in ['sc-workspace-persistence-integrity-v1.schema.json','sc-workspace-persistence-transaction-v1.schema.json','sc-workspace-persistence-integrity-report-v1.schema.json','sc-workspace-recovery-candidate-v1.schema.json']: json.loads((ROOT/'schemas'/n).read_text())
 def test_04_transactional_save(self): self.assertIn('integrity.stage',APP);self.assertIn('if (!staged?.ok)',APP);self.assertIn('integrity.commit',APP);self.assertIn('integrity.fail',APP);self.assertIn('read-after-write verification failed',APP)
 def test_05_integrity_stores(self): self.assertIn("METADATA_KEY='sc_workspace_persistence_integrity_v0620'",HELP);self.assertIn("TRANSACTION_KEY='sc_workspace_persistence_txn_v0620'",HELP);self.assertNotIn('targetRaw',HELP)
 def test_06_last_good(self): self.assertIn('captureLastGood',HELP);self.assertIn("schema:'sc-workspace-last-known-good/1.0'",HELP);self.assertIn('integrity:fp',HELP);self.assertIn('integrity.lastGoodState',APP);self.assertIn("checked?.state === 'integrity-drift'",APP)
 def test_07_no_security_overclaim(self): self.assertIn("ALGORITHM='fnv1a32'",HELP);self.assertIn("integrityPurpose:'corruption-detection-not-security'",HELP);self.assertIn('checksumSecurityClaim:false',HELP)
 def test_08_non_destructive_recovery(self): self.assertIn('automaticRestore:false',HELP);self.assertIn('canonicalMutation:false',HELP);self.assertIn('manual-review-only',HELP);self.assertIn('integrity drift',PHP.lower())
 def test_09_ui_and_nav(self): self.assertIn('data-scw-persistence-integrity',PHP);self.assertIn('data-scw-workspace-view="integrity"',PHP);self.assertIn("integrity:'Persistence Integrity'",NAV);self.assertIn('data-scw-pi-export-current',PHP);self.assertIn('data-scw-pi-export-good',PHP)
 def test_10_rest(self): self.assertIn("'/persistence-integrity-contract'",PHP);self.assertIn('/wp-json/sc-workspace/v1/persistence-integrity-contract',MAN['rest_routes'])
 def test_11_privacy_report(self): self.assertIn('projectContentIncluded:false',HELP);self.assertIn('rawStateIncluded:false',HELP);self.assertIn('containsCanonicalWorkspaceContent:true',HELP)
 def test_12_header(self): self.assertIn('.scw-persistence-integrity{border-top:4px solid #000',CSS)
 def test_13_registry_history(self): self.assertEqual((REG['public_version'],REG['previous_version']),('0.64.1','0.64.0'));self.assertIn("BACKUP_KEY = 'sc_workspace_registry_backup_v0641'",REGPHP);self.assertIn('LEGACY_PENDING_KEY_V0610',REGPHP);self.assertTrue((ROOT/'history/release-manifest-v0.61.0.json').exists())
 def test_14_ui_runtime_contract(self): self.assertIn('helper.reconcileJournal',UI);self.assertIn('Run integrity audit',PHP);self.assertIn('Open History / Recovery',PHP)
if __name__=='__main__': unittest.main()
