'use strict';
const assert=require('assert');
const path=process.argv[2] || '../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-safe-actions-v1.js';
const h=require(path);
assert.equal(h.SCHEMA,'sc-workspace-safe-actions/1.0');
assert.equal(h.GATE_SCHEMA,'sc-workspace-action-gate/1.0');
const review={summary:{added:2,removed:1,modified:3,total:6,relationshipsChanged:2,categoriesChanged:4},attention:['Evidence basis changed','Relationships changed']};
const gate=h.buildGate({id:'gate-1',action:'restore-copy',projectId:'p1',projectTitle:'Project One',baseline:{kind:'restore-point',id:'rp1',label:'Before edit'},target:{kind:'current-project',id:'p1',label:'Current project'},review,checkpointRestorePointId:'rp1',createdAt:'2026-08-09T00:00:00Z'});
assert.equal(gate.reviewSummary.total,6);
assert.equal(gate.reviewSummary.relationshipsChanged,2);
assert.equal(gate.requiredAcknowledgement.includes('does not overwrite'),true);
assert.equal(gate.governance.hiddenRiskScore,false);
assert.equal(gate.governance.automaticProceed,false);
assert.equal(gate.governance.automaticApply,false);
assert.equal(gate.governance.automaticMerge,false);
assert.equal(h.canProceed(gate,false),false);
assert.equal(h.canProceed(gate,true),true);
const proceeded=h.historyRecord(gate,'proceeded','2026-08-09T00:01:00Z');
assert.equal(proceeded.outcome,'proceeded'); assert.equal(proceeded.acknowledged,true); assert.equal(proceeded.reviewSummary.total,6);
const cancelled=h.historyRecord(gate,'cancelled','2026-08-09T00:02:00Z');
assert.equal(cancelled.outcome,'cancelled'); assert.equal(cancelled.acknowledged,false);
assert.deepEqual(Object.keys(h.ACTIONS).sort(),['institutional-promotion','restore-copy','share-portable','share-review-copy','sync-resolve-cloud','sync-resolve-local'].sort());
console.log('PASS - Change Gates & Safe Actions runtime');
