const assert=require('assert');const A=require('../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-cross-device-production-v1.js');
let p=A.plan({projectId:'p1',authenticated:false,enrolled:false});assert.equal(p.action,'local-only');
p=A.plan({projectId:'p1',authenticated:true,enrolled:false});assert.equal(p.action,'enroll');
p=A.plan({projectId:'p1',authenticated:true,enrolled:true,localFingerprint:'L',remoteExists:false,serverRevision:0});assert.equal(p.state,'not-uploaded');assert.equal(p.action,'push');
p=A.plan({projectId:'p1',authenticated:true,enrolled:true,localFingerprint:'A',remoteFingerprint:'B',baseFingerprint:'A',remoteExists:true,serverRevision:3,remoteRevision:4});assert.equal(p.state,'remote-ahead');assert.equal(p.action,'pull-safe');
p=A.plan({projectId:'p1',authenticated:true,enrolled:true,localFingerprint:'B',remoteFingerprint:'A',baseFingerprint:'A',remoteExists:true,serverRevision:3,remoteRevision:3});assert.equal(p.state,'local-ahead');assert.equal(p.action,'push');
p=A.plan({projectId:'p1',authenticated:true,enrolled:true,localFingerprint:'B',remoteFingerprint:'C',baseFingerprint:'A',remoteExists:true,serverRevision:3,remoteRevision:4});assert.equal(p.state,'conflict');assert.equal(p.action,'conflict');assert.equal(p.safeAutomaticApply,false);
const r=A.receipt(p,{workspaceVersion:'1.7.0',createdAt:'2026-08-15T00:00:00Z'});assert.equal(r.schema,A.RECEIPT_SCHEMA);assert.equal(r.workspaceVersion,'1.7.0');assert.equal(r.governance.projectContentIncluded,false);assert.equal(r.governance.deviceIdentifierIncluded,false);assert.equal(r.governance.backgroundSync,false);
const sum=A.accountSummary([{projectId:'p1',authenticated:true,enrolled:true,localFingerprint:'A',remoteFingerprint:'A',baseFingerprint:'A',remoteExists:true},{projectId:'p2',authenticated:true,enrolled:true,localFingerprint:'B',remoteFingerprint:'C',baseFingerprint:'A',remoteExists:true}]);assert.equal(sum.projects,2);assert.equal(sum.upToDate,1);assert.equal(sum.conflict,1);assert.equal(sum.requiresAttention,1);console.log('PASS - v1.7.0 cross-device production JS runtime');
