const fs=require('fs'); const vm=require('vm');
const helper=fs.readFileSync(require('path').join(__dirname,'../wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-ai-adapter-v1.js'),'utf8');
const store=new Map(); let posted=null; let navigated='';
const location={origin:'https://sustainablecatalyst.com',href:'https://sustainablecatalyst.com/research-librarian/'};
Object.defineProperty(location,'href',{get(){return this._href||'https://sustainablecatalyst.com/research-librarian/'},set(v){navigated=v;this._href=v},configurable:true});
const window={sessionStorage:{getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},location,opener:{closed:false,postMessage:(msg,origin)=>{posted={msg,origin}}}};
window.window=window;
const request={schema:'sc-workspace-ai-request-export/1.0',request:{id:'ai-1'},project:{id:'p-1'},returnUrl:'https://sustainablecatalyst.com/platform/',selectedObjects:[{id:'o-1'},{id:'o-2'}]};
store.set('sc_workspace_ai_request_v1',JSON.stringify(request));
vm.runInNewContext(helper,{window,URL,Date,JSON,Set,String,Array,Error});
const A=window.SCWorkspaceAIAdapter;
if(!A||A.version!=='1.0') throw new Error('adapter missing');
if(A.readRequest().project.id!=='p-1') throw new Error('request read failed');
const packet=A.buildResponse({response:'Grounded draft',citationObjectIds:['o-2','not-selected','o-2'],sourceTitle:'Research Librarian'});
if(packet.citationObjectIds.length!==1||packet.citationObjectIds[0]!=='o-2') throw new Error('citation grounding filter failed');
const returned=A.returnToWorkspace({response:'Grounded draft',citationObjectIds:['o-1'],sourceTitle:'Research Librarian',navigate:false});
if(returned.projectId!=='p-1'||returned.requestId!=='ai-1') throw new Error('response binding failed');
if(!store.get('sc_workspace_ai_response_v1')) throw new Error('response not stored');
if(!posted||posted.origin!=='https://sustainablecatalyst.com'||posted.msg.type!=='sc-workspace-ai-response') throw new Error('postMessage failed');
if(navigated) throw new Error('navigate:false ignored');
console.log('PASS - Responsible AI adapter runtime');
