-- Workspace v3.12.0 Spatial Evidence & Geospatial Investigation Workspace
BEGIN;
CREATE TABLE IF NOT EXISTS workspace_investigation_spatial_observation_heads (user_key varchar(128) NOT NULL, observation_id varchar(160) NOT NULL, project_id varchar(160) NOT NULL, observation_type varchar(48) NOT NULL, label varchar(1000) NOT NULL, geometry_json jsonb NOT NULL DEFAULT '{}'::jsonb, place_ref varchar(2000) NOT NULL DEFAULT '', coordinate_system varchar(64) NOT NULL DEFAULT 'EPSG:4326', source_ref varchar(2000) NOT NULL, source_fingerprint varchar(128) NOT NULL, observed_at varchar(64) NOT NULL DEFAULT '', review_state varchar(32) NOT NULL DEFAULT 'open', revision integer NOT NULL DEFAULT 1, observation_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,observation_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_spatial_observation_revisions (user_key varchar(128) NOT NULL, observation_id varchar(160) NOT NULL, revision integer NOT NULL, project_id varchar(160) NOT NULL, observation_type varchar(48) NOT NULL, label varchar(1000) NOT NULL, geometry_json jsonb NOT NULL DEFAULT '{}'::jsonb, place_ref varchar(2000) NOT NULL DEFAULT '', coordinate_system varchar(64) NOT NULL DEFAULT 'EPSG:4326', source_ref varchar(2000) NOT NULL, source_fingerprint varchar(128) NOT NULL, observed_at varchar(64) NOT NULL DEFAULT '', review_state varchar(32) NOT NULL DEFAULT 'open', observation_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,observation_id,revision));
CREATE TABLE IF NOT EXISTS workspace_investigation_spatial_context_links (user_key varchar(128) NOT NULL, link_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, observation_id varchar(160) NOT NULL, target_kind varchar(48) NOT NULL, target_ref varchar(2000) NOT NULL, relation varchar(64) NOT NULL, source_fingerprint varchar(128) NOT NULL DEFAULT '', note text NOT NULL DEFAULT '', link_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,link_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_spatial_relations (user_key varchar(128) NOT NULL, relation_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, from_observation_id varchar(160) NOT NULL, to_observation_id varchar(160) NOT NULL, relation varchar(64) NOT NULL, source_ref varchar(2000) NOT NULL DEFAULT '', source_fingerprint varchar(128) NOT NULL DEFAULT '', note text NOT NULL DEFAULT '', relation_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,relation_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_spatial_snapshots (user_key varchar(128) NOT NULL, snapshot_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, graph_fingerprint varchar(64) NOT NULL, diagnostics_fingerprint varchar(64) NOT NULL, snapshot_fingerprint varchar(64) NOT NULL, observation_count integer NOT NULL DEFAULT 0, context_link_count integer NOT NULL DEFAULT 0, relation_count integer NOT NULL DEFAULT 0, issue_count integer NOT NULL DEFAULT 0, context_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,snapshot_id));
CREATE INDEX IF NOT EXISTS ix_ws_spatial_obs_project ON workspace_investigation_spatial_observation_heads(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_spatial_links_project ON workspace_investigation_spatial_context_links(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_spatial_rel_project ON workspace_investigation_spatial_relations(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_spatial_snap_project ON workspace_investigation_spatial_snapshots(user_key,project_id);
COMMIT;
