-- Workspace v3.13.0 Media Artifact, Image, Video & Derivative Provenance Workspace
BEGIN;
CREATE TABLE IF NOT EXISTS workspace_investigation_media_artifact_heads (user_key varchar(128) NOT NULL, artifact_id varchar(160) NOT NULL, project_id varchar(160) NOT NULL, media_type varchar(32) NOT NULL, title varchar(1000) NOT NULL, source_ref varchar(2000) NOT NULL, source_fingerprint varchar(128) NOT NULL, content_hash_algorithm varchar(32) NOT NULL DEFAULT 'sha256', content_hash varchar(256) NOT NULL, mime_type varchar(160) NOT NULL DEFAULT '', original_filename varchar(1000) NOT NULL DEFAULT '', captured_at varchar(64) NOT NULL DEFAULT '', duration_seconds varchar(64) NOT NULL DEFAULT '', review_state varchar(32) NOT NULL DEFAULT 'open', revision integer NOT NULL DEFAULT 1, artifact_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,artifact_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_media_artifact_revisions (user_key varchar(128) NOT NULL, artifact_id varchar(160) NOT NULL, revision integer NOT NULL, project_id varchar(160) NOT NULL, media_type varchar(32) NOT NULL, title varchar(1000) NOT NULL, source_ref varchar(2000) NOT NULL, source_fingerprint varchar(128) NOT NULL, content_hash_algorithm varchar(32) NOT NULL DEFAULT 'sha256', content_hash varchar(256) NOT NULL, mime_type varchar(160) NOT NULL DEFAULT '', original_filename varchar(1000) NOT NULL DEFAULT '', captured_at varchar(64) NOT NULL DEFAULT '', duration_seconds varchar(64) NOT NULL DEFAULT '', review_state varchar(32) NOT NULL DEFAULT 'open', artifact_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,artifact_id,revision));
CREATE TABLE IF NOT EXISTS workspace_investigation_media_locators (user_key varchar(128) NOT NULL, locator_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, artifact_id varchar(160) NOT NULL, locator_type varchar(40) NOT NULL, locator_json jsonb NOT NULL DEFAULT '{}'::jsonb, note text NOT NULL DEFAULT '', locator_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,locator_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_media_derivatives (user_key varchar(128) NOT NULL, derivative_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, parent_artifact_id varchar(160) NOT NULL, child_artifact_id varchar(160) NOT NULL, transformation_type varchar(64) NOT NULL, parameters_json jsonb NOT NULL DEFAULT '{}'::jsonb, tool_ref varchar(1000) NOT NULL DEFAULT '', operation_ref varchar(1000) NOT NULL DEFAULT '', source_fingerprint varchar(128) NOT NULL DEFAULT '', derivative_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,derivative_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_media_context_links (user_key varchar(128) NOT NULL, link_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, artifact_id varchar(160) NOT NULL, target_kind varchar(48) NOT NULL, target_ref varchar(2000) NOT NULL, relation varchar(64) NOT NULL, locator_id varchar(96) NOT NULL DEFAULT '', source_fingerprint varchar(128) NOT NULL DEFAULT '', note text NOT NULL DEFAULT '', link_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,link_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_media_relations (user_key varchar(128) NOT NULL, relation_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, from_artifact_id varchar(160) NOT NULL, to_artifact_id varchar(160) NOT NULL, relation varchar(64) NOT NULL, source_ref varchar(2000) NOT NULL DEFAULT '', source_fingerprint varchar(128) NOT NULL DEFAULT '', note text NOT NULL DEFAULT '', relation_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,relation_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_media_snapshots (user_key varchar(128) NOT NULL, snapshot_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, graph_fingerprint varchar(64) NOT NULL, diagnostics_fingerprint varchar(64) NOT NULL, integrity_fingerprint varchar(64) NOT NULL, snapshot_fingerprint varchar(64) NOT NULL, artifact_count integer NOT NULL DEFAULT 0, locator_count integer NOT NULL DEFAULT 0, derivative_count integer NOT NULL DEFAULT 0, context_link_count integer NOT NULL DEFAULT 0, relation_count integer NOT NULL DEFAULT 0, issue_count integer NOT NULL DEFAULT 0, context_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,snapshot_id));
CREATE INDEX IF NOT EXISTS ix_ws_media_artifact_project ON workspace_investigation_media_artifact_heads(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_media_hash ON workspace_investigation_media_artifact_heads(user_key,content_hash_algorithm,content_hash);
CREATE INDEX IF NOT EXISTS ix_ws_media_locator_project ON workspace_investigation_media_locators(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_media_derivative_project ON workspace_investigation_media_derivatives(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_media_context_project ON workspace_investigation_media_context_links(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_media_relation_project ON workspace_investigation_media_relations(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_media_snapshot_project ON workspace_investigation_media_snapshots(user_key,project_id);
COMMIT;
