-- Workspace v3.14.0 Source Reliability, Provenance & Evidence Integrity Workspace
BEGIN;
CREATE TABLE IF NOT EXISTS workspace_investigation_source_heads (user_key varchar(128) NOT NULL, source_id varchar(160) NOT NULL, project_id varchar(160) NOT NULL, source_type varchar(48) NOT NULL, title varchar(1000) NOT NULL, source_ref varchar(2000) NOT NULL, publisher varchar(1000) NOT NULL DEFAULT '', published_at varchar(64) NOT NULL DEFAULT '', retrieved_at varchar(64) NOT NULL DEFAULT '', content_fingerprint varchar(128) NOT NULL, review_state varchar(32) NOT NULL DEFAULT 'open', revision integer NOT NULL DEFAULT 1, source_record_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,source_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_source_revisions (user_key varchar(128) NOT NULL, source_id varchar(160) NOT NULL, revision integer NOT NULL, project_id varchar(160) NOT NULL, source_type varchar(48) NOT NULL, title varchar(1000) NOT NULL, source_ref varchar(2000) NOT NULL, publisher varchar(1000) NOT NULL DEFAULT '', published_at varchar(64) NOT NULL DEFAULT '', retrieved_at varchar(64) NOT NULL DEFAULT '', content_fingerprint varchar(128) NOT NULL, review_state varchar(32) NOT NULL DEFAULT 'open', source_record_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,source_id,revision));
CREATE TABLE IF NOT EXISTS workspace_investigation_source_provenance_events (user_key varchar(128) NOT NULL, event_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, source_id varchar(160) NOT NULL, event_type varchar(48) NOT NULL, parent_ref varchar(2000) NOT NULL DEFAULT '', child_ref varchar(2000) NOT NULL DEFAULT '', occurred_at varchar(64) NOT NULL DEFAULT '', actor_ref varchar(1000) NOT NULL DEFAULT '', operation_ref varchar(1000) NOT NULL DEFAULT '', source_fingerprint varchar(128) NOT NULL DEFAULT '', event_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,event_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_source_custody_events (user_key varchar(128) NOT NULL, custody_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, source_id varchar(160) NOT NULL, action varchar(48) NOT NULL, custodian_ref varchar(1000) NOT NULL, occurred_at varchar(64) NOT NULL DEFAULT '', location_ref varchar(1000) NOT NULL DEFAULT '', receipt_ref varchar(2000) NOT NULL DEFAULT '', source_fingerprint varchar(128) NOT NULL DEFAULT '', custody_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,custody_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_integrity_assertions (user_key varchar(128) NOT NULL, assertion_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, source_id varchar(160) NOT NULL, assertion_type varchar(64) NOT NULL, status varchar(32) NOT NULL, basis_ref varchar(2000) NOT NULL DEFAULT '', source_fingerprint varchar(128) NOT NULL DEFAULT '', note text NOT NULL DEFAULT '', assertion_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,assertion_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_source_evidence_bindings (user_key varchar(128) NOT NULL, binding_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, source_id varchar(160) NOT NULL, target_kind varchar(48) NOT NULL, target_ref varchar(2000) NOT NULL, relation varchar(64) NOT NULL, locator_ref varchar(1000) NOT NULL DEFAULT '', source_fingerprint varchar(128) NOT NULL DEFAULT '', note text NOT NULL DEFAULT '', binding_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,binding_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_source_integrity_snapshots (user_key varchar(128) NOT NULL, snapshot_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, graph_fingerprint varchar(64) NOT NULL, diagnostics_fingerprint varchar(64) NOT NULL, integrity_fingerprint varchar(64) NOT NULL, snapshot_fingerprint varchar(64) NOT NULL, source_count integer NOT NULL DEFAULT 0, provenance_event_count integer NOT NULL DEFAULT 0, custody_event_count integer NOT NULL DEFAULT 0, assertion_count integer NOT NULL DEFAULT 0, binding_count integer NOT NULL DEFAULT 0, issue_count integer NOT NULL DEFAULT 0, context_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,snapshot_id));
CREATE INDEX IF NOT EXISTS ix_ws_source_project ON workspace_investigation_source_heads(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_source_content_fp ON workspace_investigation_source_heads(user_key,content_fingerprint);
CREATE INDEX IF NOT EXISTS ix_ws_source_prov_project ON workspace_investigation_source_provenance_events(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_source_custody_project ON workspace_investigation_source_custody_events(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_integrity_assert_project ON workspace_investigation_integrity_assertions(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_source_binding_project ON workspace_investigation_source_evidence_bindings(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_source_integrity_snapshot_project ON workspace_investigation_source_integrity_snapshots(user_key,project_id);
COMMIT;
