-- Workspace v3.15.0 Investigative Search, Discovery & Cross-Case Retrieval Workspace
BEGIN;
CREATE TABLE IF NOT EXISTS workspace_investigation_saved_search_heads (user_key varchar(128) NOT NULL, search_id varchar(160) NOT NULL, project_id varchar(160) NOT NULL DEFAULT '', name varchar(500) NOT NULL, query_text text NOT NULL, project_scope_json jsonb NOT NULL DEFAULT '[]'::jsonb, kinds_json jsonb NOT NULL DEFAULT '[]'::jsonb, filters_json jsonb NOT NULL DEFAULT '{}'::jsonb, revision integer NOT NULL DEFAULT 1, search_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,search_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_saved_search_revisions (user_key varchar(128) NOT NULL, search_id varchar(160) NOT NULL, revision integer NOT NULL, project_id varchar(160) NOT NULL DEFAULT '', name varchar(500) NOT NULL, query_text text NOT NULL, project_scope_json jsonb NOT NULL DEFAULT '[]'::jsonb, kinds_json jsonb NOT NULL DEFAULT '[]'::jsonb, filters_json jsonb NOT NULL DEFAULT '{}'::jsonb, search_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,search_id,revision));
CREATE TABLE IF NOT EXISTS workspace_investigation_search_executions (user_key varchar(128) NOT NULL, execution_id varchar(96) NOT NULL, saved_search_id varchar(160) NOT NULL DEFAULT '', query_text text NOT NULL, project_scope_json jsonb NOT NULL DEFAULT '[]'::jsonb, kinds_json jsonb NOT NULL DEFAULT '[]'::jsonb, filters_json jsonb NOT NULL DEFAULT '{}'::jsonb, result_count integer NOT NULL DEFAULT 0, result_fingerprint varchar(64) NOT NULL, results_json jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,execution_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_search_collections (user_key varchar(128) NOT NULL, collection_id varchar(96) NOT NULL, name varchar(500) NOT NULL, description text NOT NULL DEFAULT '', project_scope_json jsonb NOT NULL DEFAULT '[]'::jsonb, object_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, collection_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,collection_id));
CREATE TABLE IF NOT EXISTS workspace_investigation_search_snapshots (user_key varchar(128) NOT NULL, snapshot_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, query_text text NOT NULL, result_count integer NOT NULL DEFAULT 0, result_fingerprint varchar(64) NOT NULL, facets_fingerprint varchar(64) NOT NULL, diagnostics_fingerprint varchar(64) NOT NULL, snapshot_fingerprint varchar(64) NOT NULL, context_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,snapshot_id));
CREATE INDEX IF NOT EXISTS ix_ws_saved_search_project ON workspace_investigation_saved_search_heads(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_search_execution_created ON workspace_investigation_search_executions(user_key,created_at DESC);
CREATE INDEX IF NOT EXISTS ix_ws_search_snapshot_project ON workspace_investigation_search_snapshots(user_key,project_id);
COMMIT;
