-- Workspace v3.16.0 Quantitative Reconstruction & Scientific Analysis Handoffs
BEGIN;
CREATE TABLE IF NOT EXISTS workspace_quantitative_reconstruction_heads (user_key varchar(128) NOT NULL, reconstruction_id varchar(160) NOT NULL, project_id varchar(160) NOT NULL, title varchar(500) NOT NULL, objective text NOT NULL DEFAULT '', research_question text NOT NULL DEFAULT '', method_class varchar(64) NOT NULL, assumptions_json jsonb NOT NULL DEFAULT '[]'::jsonb, parameters_json jsonb NOT NULL DEFAULT '{}'::jsonb, revision integer NOT NULL DEFAULT 1, reconstruction_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,reconstruction_id));
CREATE TABLE IF NOT EXISTS workspace_quantitative_reconstruction_revisions (user_key varchar(128) NOT NULL, reconstruction_id varchar(160) NOT NULL, revision integer NOT NULL, project_id varchar(160) NOT NULL, title varchar(500) NOT NULL, objective text NOT NULL DEFAULT '', research_question text NOT NULL DEFAULT '', method_class varchar(64) NOT NULL, assumptions_json jsonb NOT NULL DEFAULT '[]'::jsonb, parameters_json jsonb NOT NULL DEFAULT '{}'::jsonb, reconstruction_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,reconstruction_id,revision));
CREATE TABLE IF NOT EXISTS workspace_quantitative_input_bindings (user_key varchar(128) NOT NULL, binding_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, reconstruction_id varchar(160) NOT NULL, input_kind varchar(80) NOT NULL, object_ref varchar(2000) NOT NULL, object_fingerprint varchar(128) NOT NULL DEFAULT '', role varchar(80) NOT NULL DEFAULT 'input', transform_spec_json jsonb NOT NULL DEFAULT '{}'::jsonb, note text NOT NULL DEFAULT '', binding_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,binding_id));
CREATE TABLE IF NOT EXISTS workspace_quantitative_analysis_handoffs (user_key varchar(128) NOT NULL, handoff_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, reconstruction_id varchar(160) NOT NULL, destination_product varchar(80) NOT NULL, analysis_kind varchar(160) NOT NULL, requested_operations_json jsonb NOT NULL DEFAULT '[]'::jsonb, environment_ref varchar(1000) NOT NULL DEFAULT '', reproducibility_requirements_json jsonb NOT NULL DEFAULT '{}'::jsonb, status varchar(40) NOT NULL DEFAULT 'ready', package_fingerprint varchar(64) NOT NULL, external_handoff_ref varchar(2000) NOT NULL DEFAULT '', receipt_ref varchar(2000) NOT NULL DEFAULT '', note text NOT NULL DEFAULT '', metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,handoff_id));
CREATE TABLE IF NOT EXISTS workspace_quantitative_result_bindings (user_key varchar(128) NOT NULL, binding_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, handoff_id varchar(160) NOT NULL, reconstruction_id varchar(160) NOT NULL, result_kind varchar(80) NOT NULL, result_ref varchar(2000) NOT NULL, result_fingerprint varchar(128) NOT NULL DEFAULT '', status varchar(40) NOT NULL DEFAULT 'reported', note text NOT NULL DEFAULT '', binding_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,binding_id));
CREATE TABLE IF NOT EXISTS workspace_quantitative_analysis_snapshots (user_key varchar(128) NOT NULL, snapshot_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, manifest_fingerprint varchar(64) NOT NULL, diagnostics_fingerprint varchar(64) NOT NULL, graph_fingerprint varchar(64) NOT NULL DEFAULT '', snapshot_fingerprint varchar(64) NOT NULL, reconstruction_count integer NOT NULL DEFAULT 0, input_binding_count integer NOT NULL DEFAULT 0, handoff_count integer NOT NULL DEFAULT 0, result_binding_count integer NOT NULL DEFAULT 0, issue_count integer NOT NULL DEFAULT 0, context_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,snapshot_id));
CREATE INDEX IF NOT EXISTS ix_ws_quant_reconstruction_project ON workspace_quantitative_reconstruction_heads(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_quant_input_reconstruction ON workspace_quantitative_input_bindings(user_key,reconstruction_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ws_quant_input_fingerprint ON workspace_quantitative_input_bindings(user_key,binding_fingerprint);
CREATE INDEX IF NOT EXISTS ix_ws_quant_handoff_project ON workspace_quantitative_analysis_handoffs(user_key,project_id);
CREATE INDEX IF NOT EXISTS ix_ws_quant_result_handoff ON workspace_quantitative_result_bindings(user_key,handoff_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ws_quant_result_fingerprint ON workspace_quantitative_result_bindings(user_key,binding_fingerprint);
CREATE INDEX IF NOT EXISTS ix_ws_quant_snapshot_project ON workspace_quantitative_analysis_snapshots(user_key,project_id);
COMMIT;
