BEGIN;

CREATE TABLE IF NOT EXISTS workspace_uncertainty_assessment_heads (
 user_key varchar(128) NOT NULL, assessment_id varchar(160) NOT NULL, project_id varchar(160) NOT NULL, title varchar(500) NOT NULL, objective text NOT NULL DEFAULT '', method_family varchar(80) NOT NULL, assumptions_json jsonb NOT NULL DEFAULT '[]'::jsonb, configuration_json jsonb NOT NULL DEFAULT '{}'::jsonb, revision integer NOT NULL DEFAULT 1, assessment_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,assessment_id));
CREATE INDEX IF NOT EXISTS idx_uncertainty_assessment_project ON workspace_uncertainty_assessment_heads(user_key,project_id);
CREATE TABLE IF NOT EXISTS workspace_uncertainty_assessment_revisions (
 user_key varchar(128) NOT NULL, assessment_id varchar(160) NOT NULL, revision integer NOT NULL, project_id varchar(160) NOT NULL, title varchar(500) NOT NULL, objective text NOT NULL DEFAULT '', method_family varchar(80) NOT NULL, assumptions_json jsonb NOT NULL DEFAULT '[]'::jsonb, configuration_json jsonb NOT NULL DEFAULT '{}'::jsonb, assessment_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,assessment_id,revision));
CREATE TABLE IF NOT EXISTS workspace_uncertainty_parameters (
 user_key varchar(128) NOT NULL, parameter_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, assessment_id varchar(160) NOT NULL, name varchar(240) NOT NULL, role varchar(64) NOT NULL, distribution varchar(80) NOT NULL, distribution_parameters_json jsonb NOT NULL DEFAULT '{}'::jsonb, units varchar(120) NOT NULL DEFAULT '', evidence_ref varchar(2000) NOT NULL DEFAULT '', evidence_fingerprint varchar(128) NOT NULL DEFAULT '', parameter_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,parameter_id));
CREATE INDEX IF NOT EXISTS idx_uncertainty_parameters_assessment ON workspace_uncertainty_parameters(user_key,assessment_id);
CREATE TABLE IF NOT EXISTS workspace_uncertainty_scenarios (
 user_key varchar(128) NOT NULL, scenario_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, assessment_id varchar(160) NOT NULL, title varchar(500) NOT NULL, weight varchar(80) NOT NULL DEFAULT '', parameter_overrides_json jsonb NOT NULL DEFAULT '{}'::jsonb, evidence_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, scenario_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,scenario_id));
CREATE TABLE IF NOT EXISTS workspace_sensitivity_analysis_requests (
 user_key varchar(128) NOT NULL, request_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, assessment_id varchar(160) NOT NULL, method varchar(80) NOT NULL, destination_product varchar(80) NOT NULL, output_metrics_json jsonb NOT NULL DEFAULT '[]'::jsonb, configuration_json jsonb NOT NULL DEFAULT '{}'::jsonb, status varchar(40) NOT NULL DEFAULT 'ready', request_fingerprint varchar(64) NOT NULL, external_handoff_ref varchar(2000) NOT NULL DEFAULT '', metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,request_id));
CREATE TABLE IF NOT EXISTS workspace_probabilistic_result_bindings (
 user_key varchar(128) NOT NULL, binding_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, assessment_id varchar(160) NOT NULL, result_kind varchar(80) NOT NULL, result_ref varchar(2000) NOT NULL, result_fingerprint varchar(128) NOT NULL DEFAULT '', interpretation_status varchar(40) NOT NULL DEFAULT 'reported', note text NOT NULL DEFAULT '', binding_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,binding_id));
CREATE TABLE IF NOT EXISTS workspace_uncertainty_investigation_snapshots (
 user_key varchar(128) NOT NULL, snapshot_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, manifest_fingerprint varchar(64) NOT NULL, diagnostics_fingerprint varchar(64) NOT NULL, graph_fingerprint varchar(64) NOT NULL DEFAULT '', snapshot_fingerprint varchar(64) NOT NULL, assessment_count integer NOT NULL DEFAULT 0, parameter_count integer NOT NULL DEFAULT 0, scenario_count integer NOT NULL DEFAULT 0, sensitivity_request_count integer NOT NULL DEFAULT 0, result_binding_count integer NOT NULL DEFAULT 0, issue_count integer NOT NULL DEFAULT 0, context_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,snapshot_id));
CREATE INDEX IF NOT EXISTS idx_uncertainty_snapshots_project ON workspace_uncertainty_investigation_snapshots(user_key,project_id,created_at DESC);

COMMIT;
