BEGIN;

CREATE TABLE IF NOT EXISTS workspace_causal_question_heads (
 user_key varchar(128) NOT NULL, question_id varchar(160) NOT NULL, project_id varchar(160) NOT NULL, title varchar(500) NOT NULL, question_text text NOT NULL, estimand varchar(500) NOT NULL DEFAULT '', exposure_ref varchar(1000) NOT NULL DEFAULT '', outcome_ref varchar(1000) NOT NULL DEFAULT '', review_state varchar(40) NOT NULL DEFAULT 'open', revision integer NOT NULL DEFAULT 1, question_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,question_id));
CREATE INDEX IF NOT EXISTS idx_causal_question_project ON workspace_causal_question_heads(user_key,project_id);
CREATE TABLE IF NOT EXISTS workspace_causal_question_revisions (
 user_key varchar(128) NOT NULL, question_id varchar(160) NOT NULL, revision integer NOT NULL, project_id varchar(160) NOT NULL, title varchar(500) NOT NULL, question_text text NOT NULL, estimand varchar(500) NOT NULL DEFAULT '', exposure_ref varchar(1000) NOT NULL DEFAULT '', outcome_ref varchar(1000) NOT NULL DEFAULT '', review_state varchar(40) NOT NULL DEFAULT 'open', question_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,question_id,revision));
CREATE TABLE IF NOT EXISTS workspace_causal_structures (
 user_key varchar(128) NOT NULL, structure_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, question_id varchar(160) NOT NULL, title varchar(500) NOT NULL, structure_kind varchar(80) NOT NULL, variables_json jsonb NOT NULL DEFAULT '[]'::jsonb, edges_json jsonb NOT NULL DEFAULT '[]'::jsonb, graph_ref varchar(2000) NOT NULL DEFAULT '', graph_fingerprint varchar(128) NOT NULL DEFAULT '', structure_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,structure_id));
CREATE INDEX IF NOT EXISTS idx_causal_structures_question ON workspace_causal_structures(user_key,question_id);
CREATE TABLE IF NOT EXISTS workspace_alternative_explanations (
 user_key varchar(128) NOT NULL, explanation_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, question_id varchar(160) NOT NULL, title varchar(500) NOT NULL, explanation text NOT NULL, mechanism text NOT NULL DEFAULT '', status varchar(40) NOT NULL DEFAULT 'open', hypothesis_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, evidence_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, explanation_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,explanation_id));
CREATE TABLE IF NOT EXISTS workspace_causal_identification_assumptions (
 user_key varchar(128) NOT NULL, assumption_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, question_id varchar(160) NOT NULL, assumption_type varchar(120) NOT NULL, statement text NOT NULL, rationale text NOT NULL DEFAULT '', status varchar(40) NOT NULL DEFAULT 'asserted', evidence_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, assumption_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,assumption_id));
CREATE TABLE IF NOT EXISTS workspace_causal_analysis_handoffs (
 user_key varchar(128) NOT NULL, handoff_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, question_id varchar(160) NOT NULL, method varchar(120) NOT NULL, destination_product varchar(80) NOT NULL, estimand varchar(500) NOT NULL DEFAULT '', treatment_ref varchar(1000) NOT NULL DEFAULT '', outcome_ref varchar(1000) NOT NULL DEFAULT '', adjustment_set_json jsonb NOT NULL DEFAULT '[]'::jsonb, configuration_json jsonb NOT NULL DEFAULT '{}'::jsonb, status varchar(40) NOT NULL DEFAULT 'ready', handoff_fingerprint varchar(64) NOT NULL, external_handoff_ref varchar(2000) NOT NULL DEFAULT '', metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,handoff_id));
CREATE TABLE IF NOT EXISTS workspace_causal_result_bindings (
 user_key varchar(128) NOT NULL, binding_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, question_id varchar(160) NOT NULL, handoff_id varchar(96) NOT NULL DEFAULT '', result_kind varchar(100) NOT NULL, result_ref varchar(2000) NOT NULL, result_fingerprint varchar(128) NOT NULL, interpretation_status varchar(40) NOT NULL DEFAULT 'reported', note text NOT NULL DEFAULT '', binding_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,binding_id));
CREATE TABLE IF NOT EXISTS workspace_causal_investigation_snapshots (
 user_key varchar(128) NOT NULL, snapshot_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, analysis_fingerprint varchar(64) NOT NULL, manifest_fingerprint varchar(64) NOT NULL, graph_fingerprint varchar(64) NOT NULL DEFAULT '', diagnostics_fingerprint varchar(64) NOT NULL, snapshot_fingerprint varchar(64) NOT NULL, question_count integer NOT NULL DEFAULT 0, structure_count integer NOT NULL DEFAULT 0, explanation_count integer NOT NULL DEFAULT 0, assumption_count integer NOT NULL DEFAULT 0, handoff_count integer NOT NULL DEFAULT 0, result_binding_count integer NOT NULL DEFAULT 0, issue_count integer NOT NULL DEFAULT 0, context_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,snapshot_id));
CREATE INDEX IF NOT EXISTS idx_causal_snapshots_project ON workspace_causal_investigation_snapshots(user_key,project_id,created_at DESC);

COMMIT;
