BEGIN;

CREATE TABLE IF NOT EXISTS workspace_predictive_scenario_heads (
 user_key varchar(128) NOT NULL, scenario_id varchar(160) NOT NULL, project_id varchar(160) NOT NULL, title varchar(500) NOT NULL, description text NOT NULL DEFAULT '', scenario_kind varchar(80) NOT NULL DEFAULT 'exploratory', horizon varchar(500) NOT NULL DEFAULT '', assumptions_json jsonb NOT NULL DEFAULT '[]'::jsonb, input_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, causal_question_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, uncertainty_assessment_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, review_state varchar(40) NOT NULL DEFAULT 'open', revision integer NOT NULL DEFAULT 1, scenario_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,scenario_id));
CREATE INDEX IF NOT EXISTS idx_predictive_scenario_project ON workspace_predictive_scenario_heads(user_key,project_id);

CREATE TABLE IF NOT EXISTS workspace_predictive_scenario_revisions (
 user_key varchar(128) NOT NULL, scenario_id varchar(160) NOT NULL, revision integer NOT NULL, project_id varchar(160) NOT NULL, title varchar(500) NOT NULL, description text NOT NULL DEFAULT '', scenario_kind varchar(80) NOT NULL DEFAULT 'exploratory', horizon varchar(500) NOT NULL DEFAULT '', assumptions_json jsonb NOT NULL DEFAULT '[]'::jsonb, input_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, causal_question_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, uncertainty_assessment_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, review_state varchar(40) NOT NULL DEFAULT 'open', scenario_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,scenario_id,revision));

CREATE TABLE IF NOT EXISTS workspace_predictive_model_bindings (
 user_key varchar(128) NOT NULL, binding_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, scenario_id varchar(160) NOT NULL, model_family varchar(120) NOT NULL, model_ref varchar(2000) NOT NULL, model_fingerprint varchar(128) NOT NULL, training_data_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, feature_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, environment_ref varchar(2000) NOT NULL DEFAULT '', environment_fingerprint varchar(128) NOT NULL DEFAULT '', binding_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,binding_id));
CREATE INDEX IF NOT EXISTS idx_predictive_model_binding_scenario ON workspace_predictive_model_bindings(user_key,scenario_id);

CREATE TABLE IF NOT EXISTS workspace_predictive_forecast_requests (
 user_key varchar(128) NOT NULL, forecast_request_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, scenario_id varchar(160) NOT NULL, model_binding_id varchar(96) NOT NULL DEFAULT '', forecast_kind varchar(120) NOT NULL, destination_product varchar(80) NOT NULL, target_ref varchar(2000) NOT NULL DEFAULT '', horizon varchar(500) NOT NULL DEFAULT '', configuration_json jsonb NOT NULL DEFAULT '{}'::jsonb, calibration_plan_json jsonb NOT NULL DEFAULT '{}'::jsonb, backtest_plan_json jsonb NOT NULL DEFAULT '{}'::jsonb, status varchar(40) NOT NULL DEFAULT 'ready', forecast_request_fingerprint varchar(64) NOT NULL, external_handoff_ref varchar(2000) NOT NULL DEFAULT '', metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,forecast_request_id));
CREATE INDEX IF NOT EXISTS idx_predictive_forecast_scenario ON workspace_predictive_forecast_requests(user_key,scenario_id);

CREATE TABLE IF NOT EXISTS workspace_predictive_forecast_result_bindings (
 user_key varchar(128) NOT NULL, binding_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, scenario_id varchar(160) NOT NULL, forecast_request_id varchar(96) NOT NULL DEFAULT '', result_kind varchar(100) NOT NULL, result_ref varchar(2000) NOT NULL, result_fingerprint varchar(128) NOT NULL, model_conditional boolean NOT NULL DEFAULT true, calibration_ref varchar(2000) NOT NULL DEFAULT '', calibration_fingerprint varchar(128) NOT NULL DEFAULT '', backtest_ref varchar(2000) NOT NULL DEFAULT '', backtest_fingerprint varchar(128) NOT NULL DEFAULT '', note text NOT NULL DEFAULT '', binding_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,binding_id));
CREATE INDEX IF NOT EXISTS idx_predictive_result_scenario ON workspace_predictive_forecast_result_bindings(user_key,scenario_id);

CREATE TABLE IF NOT EXISTS workspace_predictive_scenario_comparisons (
 user_key varchar(128) NOT NULL, comparison_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, title varchar(500) NOT NULL, relation varchar(80) NOT NULL DEFAULT 'compare', scenario_ids_json jsonb NOT NULL DEFAULT '[]'::jsonb, result_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, note text NOT NULL DEFAULT '', comparison_fingerprint varchar(64) NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,comparison_id));
CREATE INDEX IF NOT EXISTS idx_predictive_comparison_project ON workspace_predictive_scenario_comparisons(user_key,project_id);

CREATE TABLE IF NOT EXISTS workspace_predictive_investigation_snapshots (
 user_key varchar(128) NOT NULL, snapshot_id varchar(96) NOT NULL, project_id varchar(160) NOT NULL, manifest_fingerprint varchar(64) NOT NULL, graph_fingerprint varchar(64) NOT NULL DEFAULT '', diagnostics_fingerprint varchar(64) NOT NULL, snapshot_fingerprint varchar(64) NOT NULL, scenario_count integer NOT NULL DEFAULT 0, model_binding_count integer NOT NULL DEFAULT 0, forecast_request_count integer NOT NULL DEFAULT 0, result_binding_count integer NOT NULL DEFAULT 0, comparison_count integer NOT NULL DEFAULT 0, issue_count integer NOT NULL DEFAULT 0, context_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_key,snapshot_id));
CREATE INDEX IF NOT EXISTS idx_predictive_snapshots_project ON workspace_predictive_investigation_snapshots(user_key,project_id,created_at DESC);

COMMIT;
