/* AUTO-GENERATED by scripts/generate_typed_client_contracts_v3200.py. DO NOT EDIT. */
const SCW_TYPED_CONTRACT_VERSION = '3.2.0' as const;
const SCW_TYPED_CONTRACT_SCHEMA = 'sc-workspace-typed-client-contract/1.0' as const;
const SCW_OPENAPI_PROJECTION_SHA256 = '271c332999eb5d158e07fc8655bb4fb2fcfd2ef0adbd76cf6d5f3de18c33a413' as const;

type WorkspaceCommand = 'project.put' | 'project.delete' | 'notebook.put' | 'notebook.delete' | 'artifact.put' | 'artifact.delete' | 'job.submit' | 'job.cancel' | 'job.retry';
type WorkspaceQuery = 'workspace.overview' | 'project.detail' | 'notebook.detail' | 'artifact.index' | 'dataset.index' | 'model.index' | 'execution.index' | 'provenance.receipts' | 'command.receipts';
type JsonObject = { [key: string]: unknown };
type WorkspaceScientificObjectKind = 'artifact'|'dataset'|'model'|'parameter-set'|'execution-run'|'execution-environment'|'runtime-adapter'|'study-package'|'visualization-spec'|'scientific-receipt';
type WorkspaceProduct = 'workspace'|'knowledge-library'|'research-librarian'|'workbench'|'research-lab'|'decision-studio'|'site-intelligence'|'catalyst-data'|'platform-core';
type WorkspaceHandoffIntent = 'analyze'|'simulate'|'visualize'|'validate'|'compare'|'decide'|'publish'|'investigate'|'cite'|'continue-research';
interface WorkspaceCommandRequest { schema: 'sc-workspace-command-request/1.0'; command: WorkspaceCommand; commandId?: string; idempotencyKey?: string; payload: JsonObject; }
interface WorkspaceQueryRequest { schema: 'sc-workspace-query-request/1.0'; query: WorkspaceQuery; parameters?: JsonObject; }
interface NotebookExecutionPlanRequest { schema: 'sc-workspace-notebook-execution-plan-request/1.0'; notebookId: string; expectedNotebookRevision?: number; selectedCellIds?: string[]; strictDependencies?: boolean; }
interface ScientificStudyPackageRequest { schema: 'sc-workspace-scientific-study-package-request/1.0'; projectId: string; title?: string; description?: string; selectedNotebookIds?: string[]; includeArtifactBlobs?: boolean; includeScientificReceipts?: boolean; }
interface WorkspaceSyncMutation { action: 'put'|'delete'; document?: JsonObject; projectId?: string; title?: string; }
interface WorkspaceSyncEnvelope { schema: 'sc-workspace-sync-envelope/1.0'; envelopeId: string; operationId: string; deviceId: string; objectKind: 'project'|'notebook'; objectId: string; baseRevision: number; baseFingerprint?: string; clientSequence: number; clientUpdatedAt?: string; mutation: WorkspaceSyncMutation; }
interface WorkspaceSyncReconcileRequest { schema: 'sc-workspace-sync-reconcile-request/1.0'; deviceId: string; clientRevisionVector: Record<string,number>; projectIds?: string[]; }
interface WorkspaceHandoffObjectRef { kind: WorkspaceScientificObjectKind; objectId: string; revision?: number; fingerprint?: string; }
interface WorkspaceResearchHandoffRequest { schema: 'sc-workspace-research-handoff-request/1.0'; handoffId?: string; projectId?: string; sourceProduct: WorkspaceProduct; destinationProduct: WorkspaceProduct; intent: WorkspaceHandoffIntent; objects: WorkspaceHandoffObjectRef[]; context?: JsonObject; }
interface WorkspaceResearchHandoffAcceptRequest { schema: 'sc-workspace-research-handoff-accept-request/1.0'; destinationProduct: WorkspaceProduct; destinationObjectId?: string; destinationReceiptId?: string; notes?: JsonObject; }
interface WorkspaceAuthorizationEvaluateRequest { schema: 'sc-workspace-authorization-evaluate-request/1.0'; action: 'workspace.read'|'workspace.write'|'workspace.execute'|'workspace.sync'|'workspace.handoff.prepare'|'workspace.handoff.accept'|'workspace.authorization.inspect'|'workspace.authorization.evaluate'; resourceKind?: 'workspace'|'project'|'notebook'|'artifact'|'dataset'|'model'|'execution'|'visualization'|'study-package'|'handoff'|'authorization'; resourceId?: string; projectId?: string; context?: JsonObject; }
interface VisualizationSpecRequest { schema: 'sc-workspace-visualization-spec-request/1.0'; visualizationId?: string; projectId: string; title?: string; expectedRevision?: number; operationId?: string; spec: JsonObject; }
interface PlatformCoreSessionRequest { schema:'sc-workspace-platform-core-session-request/1.0'; projectId:string; title?:string; workflowRef?:string; projectStateRef?:string; visibility?:'internal'|'public'; metadata?:JsonObject; provenance?:JsonObject; }
interface PlatformCoreObjectBindingRequest { schema:'sc-workspace-platform-core-object-binding-request/1.0'; projectId:string; kind:WorkspaceScientificObjectKind; objectId:string; role?:string; visibility?:'internal'|'public'; metadata?:JsonObject; }
interface PlatformCoreExecutionBindingRequest { schema:'sc-workspace-platform-core-execution-binding-request/1.0'; projectId:string; executionRunId:string; runtime?:string; methodRef?:string; visibility?:'internal'|'public'; metadata?:JsonObject; }
interface PlatformCoreVisualBindingRequest { schema:'sc-workspace-platform-core-visual-binding-request/1.0'; projectId:string; visualizationId:string; visualType?:string; sceneRef?:string; viewRef?:string; sourceRefs?:string[]; visibility?:'internal'|'public'; metadata?:JsonObject; }
interface PlatformCorePackageBindingRequest { schema:'sc-workspace-platform-core-package-binding-request/1.0'; projectId:string; packageId:string; packageType?:string; memberRefs?:string[]; visibility?:'internal'|'public'; metadata?:JsonObject; }
interface PlatformCoreHandoffBindingRequest { schema:'sc-workspace-platform-core-handoff-binding-request/1.0'; projectId:string; handoffId:string; visibility?:'internal'|'public'; metadata?:JsonObject; }
interface UnifiedResearchContextSnapshotRequest { schema: 'sc-workspace-unified-research-project-context-snapshot-request/1.0'; includeCoreViews?: boolean; }
interface WorkspaceApiEnvelope { schema?: string; ok?: boolean; [key: string]: unknown }
const SCW_TYPED_ENDPOINTS = Object.freeze({
  unifiedResearchContext: { method: 'GET' as const, path: '/v1/research-context' },
  unifiedResearchProjectContext: { method: 'GET' as const, path: '/v1/research-context/projects/{project_id}' },
  unifiedResearchContextSnapshotCreate: { method: 'POST' as const, path: '/v1/research-context/projects/{project_id}/snapshots' },
  unifiedResearchContextSnapshots: { method: 'GET' as const, path: '/v1/research-context/projects/{project_id}/snapshots' },
  platformCoreRuntime: { method: 'GET' as const, path: '/v1/platform-core-runtime' },
  platformCoreRuntimeReadiness: { method: 'GET' as const, path: '/v1/platform-core-runtime/readiness' },
  platformCoreSessionCreate: { method: 'POST' as const, path: '/v1/platform-core-runtime/sessions' },
  platformCoreProjectContext: { method: 'GET' as const, path: '/v1/platform-core-runtime/projects/{project_id}' },
  platformCoreObjectBind: { method: 'POST' as const, path: '/v1/platform-core-runtime/object-bindings' },
  platformCoreExecutionBind: { method: 'POST' as const, path: '/v1/platform-core-runtime/execution-bindings' },
  platformCoreVisualBind: { method: 'POST' as const, path: '/v1/platform-core-runtime/visual-bindings' },
  platformCorePackageBind: { method: 'POST' as const, path: '/v1/platform-core-runtime/package-bindings' },
  platformCoreHandoffBind: { method: 'POST' as const, path: '/v1/platform-core-runtime/handoff-bindings' },
  platformCoreSessionSummary: { method: 'GET' as const, path: '/v1/platform-core-runtime/sessions/{session_id}/summary' },
  platformCoreSessionLineage: { method: 'GET' as const, path: '/v1/platform-core-runtime/sessions/{session_id}/lineage' },
  platformCoreSessionBundle: { method: 'GET' as const, path: '/v1/platform-core-runtime/sessions/{session_id}/bundle' },
  platformCoreRuntimeReceipts: { method: 'GET' as const, path: '/v1/platform-core-runtime/receipts' },
  backendNativeWorkspace: { method: 'GET' as const, path: '/v1/backend-native-workspace' },
  backendNativeBootstrap: { method: 'GET' as const, path: '/v1/backend-native-workspace/bootstrap' },
  frontendRuntime: { method: 'GET' as const, path: '/v1/frontend-runtime' },
  productionCertification: { method: 'GET' as const, path: '/v1/production-certification' },
  authorizationProfile: { method: 'GET' as const, path: '/v1/authorization' },
  authorizationIdentity: { method: 'GET' as const, path: '/v1/authorization/identity' },
  authorizationEvaluate: { method: 'POST' as const, path: '/v1/authorization/evaluate' },
  authorizationDecisions: { method: 'GET' as const, path: '/v1/authorization/decisions' },
  clientContracts: { method: 'GET' as const, path: '/v1/client-contracts' },
  thinClientState: { method: 'GET' as const, path: '/v1/thin-client-state' },
  thinClientBootstrap: { method: 'GET' as const, path: '/v1/thin-client-state/bootstrap' },
  syncProfile: { method: 'GET' as const, path: '/v1/sync' },
  syncBootstrap: { method: 'GET' as const, path: '/v1/sync/bootstrap' },
  syncEnvelope: { method: 'POST' as const, path: '/v1/sync/envelopes' },
  syncReconcile: { method: 'POST' as const, path: '/v1/sync/reconcile' },
  syncReceipts: { method: 'GET' as const, path: '/v1/sync/receipts' },
  scientificObjectProfile: { method: 'GET' as const, path: '/v1/scientific-objects/profile' },
  scientificObjects: { method: 'GET' as const, path: '/v1/scientific-objects' },
  scientificObjectGet: { method: 'GET' as const, path: '/v1/scientific-objects/{kind}/{object_id}' },
  scientificObjectHistory: { method: 'GET' as const, path: '/v1/scientific-objects/{kind}/{object_id}/revisions' },
  scientificObjectRelations: { method: 'GET' as const, path: '/v1/scientific-objects/{kind}/{object_id}/relations' },
  handoffProfile: { method: 'GET' as const, path: '/v1/handoffs/profile' },
  handoffCreate: { method: 'POST' as const, path: '/v1/handoffs' },
  handoffGet: { method: 'GET' as const, path: '/v1/handoffs/{handoff_id}' },
  handoffAccept: { method: 'POST' as const, path: '/v1/handoffs/{handoff_id}/accept' },
  handoffReceipts: { method: 'GET' as const, path: '/v1/handoff-receipts' },
  domainAuthority: { method: 'GET' as const, path: '/v1/domain-authority' },
  commandQuery: { method: 'GET' as const, path: '/v1/command-query' },
  executeCommand: { method: 'POST' as const, path: '/v1/commands/execute' },
  executeQuery: { method: 'POST' as const, path: '/v1/queries/execute' },
  workspaceOverview: { method: 'GET' as const, path: '/v1/read-models/workspace-overview' },
  notebookOrchestration: { method: 'GET' as const, path: '/v1/notebook-orchestration' },
  notebookPlans: { method: 'POST' as const, path: '/v1/notebook-execution-plans' },
  studyPackageProfile: { method: 'GET' as const, path: '/v1/scientific-study-packages/profile' },
  studyPackages: { method: 'POST' as const, path: '/v1/scientific-study-packages' },
  visualizationProfile: { method: 'GET' as const, path: '/v1/visualization-specs/profile' },
  visualizationSpecs: { method: 'POST' as const, path: '/v1/visualization-specs' },
  visualizationReceipts: { method: 'GET' as const, path: '/v1/visualization-spec-receipts' },
});
