/* AUTO-GENERATED by scripts/generate_typed_client_contracts_v2340.py. DO NOT EDIT. */
const SCW_TYPED_CONTRACT_VERSION = '2.34.0' as const;
const SCW_TYPED_CONTRACT_SCHEMA = 'sc-workspace-typed-client-contract/1.0' as const;
const SCW_OPENAPI_PROJECTION_SHA256 = '4cf47149a0e1618fc74d1078d55932a0b901ff294ab0ccf1a77526f0bb6d5749' as const;

type WorkspaceCommand = 'project.put' | 'project.delete' | 'notebook.put' | 'notebook.delete' | 'artifact.put' | 'artifact.delete' | 'job.submit' | 'job.cancel' | 'job.retry';
type WorkspaceQuery = 'workspace.overview' | 'project.detail' | 'notebook.detail' | 'artifact.index' | 'dataset.index' | 'model.index' | 'execution.index' | 'provenance.receipts' | 'command.receipts';
type JsonObject = { [key: string]: unknown };
type WorkspaceScientificObjectKind = 'artifact'|'dataset'|'model'|'parameter-set'|'execution-run'|'execution-environment'|'runtime-adapter'|'study-package'|'visualization-spec'|'scientific-receipt';
type WorkspaceProduct = 'workspace'|'knowledge-library'|'research-librarian'|'workbench'|'research-lab'|'decision-studio'|'site-intelligence'|'catalyst-data'|'platform-core';
type WorkspaceHandoffIntent = 'analyze'|'simulate'|'visualize'|'validate'|'compare'|'decide'|'publish'|'investigate'|'cite'|'continue-research';
interface WorkspaceCommandRequest { schema: 'sc-workspace-command-request/1.0'; command: WorkspaceCommand; commandId?: string; idempotencyKey?: string; payload: JsonObject; }
interface WorkspaceQueryRequest { schema: 'sc-workspace-query-request/1.0'; query: WorkspaceQuery; parameters?: JsonObject; }
interface NotebookExecutionPlanRequest { schema: 'sc-workspace-notebook-execution-plan-request/1.0'; notebookId: string; expectedNotebookRevision?: number; selectedCellIds?: string[]; strictDependencies?: boolean; }
interface ScientificStudyPackageRequest { schema: 'sc-workspace-scientific-study-package-request/1.0'; projectId: string; title?: string; description?: string; selectedNotebookIds?: string[]; includeArtifactBlobs?: boolean; includeScientificReceipts?: boolean; }
interface WorkspaceSyncMutation { action: 'put'|'delete'; document?: JsonObject; projectId?: string; title?: string; }
interface WorkspaceSyncEnvelope { schema: 'sc-workspace-sync-envelope/1.0'; envelopeId: string; operationId: string; deviceId: string; objectKind: 'project'|'notebook'; objectId: string; baseRevision: number; baseFingerprint?: string; clientSequence: number; clientUpdatedAt?: string; mutation: WorkspaceSyncMutation; }
interface WorkspaceSyncReconcileRequest { schema: 'sc-workspace-sync-reconcile-request/1.0'; deviceId: string; clientRevisionVector: Record<string,number>; projectIds?: string[]; }
interface WorkspaceHandoffObjectRef { kind: WorkspaceScientificObjectKind; objectId: string; revision?: number; fingerprint?: string; }
interface WorkspaceResearchHandoffRequest { schema: 'sc-workspace-research-handoff-request/1.0'; handoffId?: string; projectId?: string; sourceProduct: WorkspaceProduct; destinationProduct: WorkspaceProduct; intent: WorkspaceHandoffIntent; objects: WorkspaceHandoffObjectRef[]; context?: JsonObject; }
interface WorkspaceResearchHandoffAcceptRequest { schema: 'sc-workspace-research-handoff-accept-request/1.0'; destinationProduct: WorkspaceProduct; destinationObjectId?: string; destinationReceiptId?: string; notes?: JsonObject; }
interface WorkspaceAuthorizationEvaluateRequest { schema: 'sc-workspace-authorization-evaluate-request/1.0'; action: 'workspace.read'|'workspace.write'|'workspace.execute'|'workspace.sync'|'workspace.handoff.prepare'|'workspace.handoff.accept'|'workspace.authorization.inspect'|'workspace.authorization.evaluate'; resourceKind?: 'workspace'|'project'|'notebook'|'artifact'|'dataset'|'model'|'execution'|'visualization'|'study-package'|'handoff'|'authorization'; resourceId?: string; projectId?: string; context?: JsonObject; }
interface VisualizationSpecRequest { schema: 'sc-workspace-visualization-spec-request/1.0'; visualizationId?: string; projectId: string; title?: string; expectedRevision?: number; operationId?: string; spec: JsonObject; }
interface WorkspaceApiEnvelope { schema?: string; ok?: boolean; [key: string]: unknown }
const SCW_TYPED_ENDPOINTS = Object.freeze({
  authorizationProfile: { method: 'GET' as const, path: '/v1/authorization' },
  authorizationIdentity: { method: 'GET' as const, path: '/v1/authorization/identity' },
  authorizationEvaluate: { method: 'POST' as const, path: '/v1/authorization/evaluate' },
  authorizationDecisions: { method: 'GET' as const, path: '/v1/authorization/decisions' },
  clientContracts: { method: 'GET' as const, path: '/v1/client-contracts' },
  thinClientState: { method: 'GET' as const, path: '/v1/thin-client-state' },
  thinClientBootstrap: { method: 'GET' as const, path: '/v1/thin-client-state/bootstrap' },
  syncProfile: { method: 'GET' as const, path: '/v1/sync' },
  syncBootstrap: { method: 'GET' as const, path: '/v1/sync/bootstrap' },
  syncEnvelope: { method: 'POST' as const, path: '/v1/sync/envelopes' },
  syncReconcile: { method: 'POST' as const, path: '/v1/sync/reconcile' },
  syncReceipts: { method: 'GET' as const, path: '/v1/sync/receipts' },
  scientificObjectProfile: { method: 'GET' as const, path: '/v1/scientific-objects/profile' },
  scientificObjects: { method: 'GET' as const, path: '/v1/scientific-objects' },
  scientificObjectGet: { method: 'GET' as const, path: '/v1/scientific-objects/{kind}/{object_id}' },
  scientificObjectHistory: { method: 'GET' as const, path: '/v1/scientific-objects/{kind}/{object_id}/revisions' },
  scientificObjectRelations: { method: 'GET' as const, path: '/v1/scientific-objects/{kind}/{object_id}/relations' },
  handoffProfile: { method: 'GET' as const, path: '/v1/handoffs/profile' },
  handoffCreate: { method: 'POST' as const, path: '/v1/handoffs' },
  handoffGet: { method: 'GET' as const, path: '/v1/handoffs/{handoff_id}' },
  handoffAccept: { method: 'POST' as const, path: '/v1/handoffs/{handoff_id}/accept' },
  handoffReceipts: { method: 'GET' as const, path: '/v1/handoff-receipts' },
  domainAuthority: { method: 'GET' as const, path: '/v1/domain-authority' },
  commandQuery: { method: 'GET' as const, path: '/v1/command-query' },
  executeCommand: { method: 'POST' as const, path: '/v1/commands/execute' },
  executeQuery: { method: 'POST' as const, path: '/v1/queries/execute' },
  workspaceOverview: { method: 'GET' as const, path: '/v1/read-models/workspace-overview' },
  notebookOrchestration: { method: 'GET' as const, path: '/v1/notebook-orchestration' },
  notebookPlans: { method: 'POST' as const, path: '/v1/notebook-execution-plans' },
  studyPackageProfile: { method: 'GET' as const, path: '/v1/scientific-study-packages/profile' },
  studyPackages: { method: 'POST' as const, path: '/v1/scientific-study-packages' },
  visualizationProfile: { method: 'GET' as const, path: '/v1/visualization-specs/profile' },
  visualizationSpecs: { method: 'POST' as const, path: '/v1/visualization-specs' },
  visualizationReceipts: { method: 'GET' as const, path: '/v1/visualization-spec-receipts' },
});
