/* AUTO-GENERATED by scripts/generate_typed_client_contracts_v2310.py. DO NOT EDIT. */
const SCW_TYPED_CONTRACT_VERSION = '2.31.0' as const;
const SCW_TYPED_CONTRACT_SCHEMA = 'sc-workspace-typed-client-contract/1.0' as const;
const SCW_OPENAPI_PROJECTION_SHA256 = '041749f7febbc782cd8ffe8b06f0c4e7de0c21b5849c9131eaeb3d60067dfa40' as const;

type WorkspaceCommand = 'project.put' | 'project.delete' | 'notebook.put' | 'notebook.delete' | 'artifact.put' | 'artifact.delete' | 'job.submit' | 'job.cancel' | 'job.retry';
type WorkspaceQuery = 'workspace.overview' | 'project.detail' | 'notebook.detail' | 'artifact.index' | 'dataset.index' | 'model.index' | 'execution.index' | 'provenance.receipts' | 'command.receipts';
type JsonObject = { [key: string]: unknown };
interface WorkspaceCommandRequest { schema: 'sc-workspace-command-request/1.0'; command: WorkspaceCommand; commandId?: string; idempotencyKey?: string; payload: JsonObject; }
interface WorkspaceQueryRequest { schema: 'sc-workspace-query-request/1.0'; query: WorkspaceQuery; parameters?: JsonObject; }
interface NotebookExecutionPlanRequest { schema: 'sc-workspace-notebook-execution-plan-request/1.0'; notebookId: string; expectedNotebookRevision?: number; selectedCellIds?: string[]; strictDependencies?: boolean; }
interface ScientificStudyPackageRequest { schema: 'sc-workspace-scientific-study-package-request/1.0'; projectId: string; title?: string; description?: string; selectedNotebookIds?: string[]; includeArtifactBlobs?: boolean; includeScientificReceipts?: boolean; }
interface WorkspaceSyncMutation { action: 'put'|'delete'; document?: JsonObject; projectId?: string; title?: string; }
interface WorkspaceSyncEnvelope { schema: 'sc-workspace-sync-envelope/1.0'; envelopeId: string; operationId: string; deviceId: string; objectKind: 'project'|'notebook'; objectId: string; baseRevision: number; baseFingerprint?: string; clientSequence: number; clientUpdatedAt?: string; mutation: WorkspaceSyncMutation; }
interface WorkspaceSyncReconcileRequest { schema: 'sc-workspace-sync-reconcile-request/1.0'; deviceId: string; clientRevisionVector: Record<string,number>; projectIds?: string[]; }
interface VisualizationSpecRequest { schema: 'sc-workspace-visualization-spec-request/1.0'; visualizationId?: string; projectId: string; title?: string; expectedRevision?: number; operationId?: string; spec: JsonObject; }
interface WorkspaceApiEnvelope { schema?: string; ok?: boolean; [key: string]: unknown }
const SCW_TYPED_ENDPOINTS = Object.freeze({
  clientContracts: { method: 'GET' as const, path: '/v1/client-contracts' },
  thinClientState: { method: 'GET' as const, path: '/v1/thin-client-state' },
  thinClientBootstrap: { method: 'GET' as const, path: '/v1/thin-client-state/bootstrap' },
  syncProfile: { method: 'GET' as const, path: '/v1/sync' },
  syncBootstrap: { method: 'GET' as const, path: '/v1/sync/bootstrap' },
  syncEnvelope: { method: 'POST' as const, path: '/v1/sync/envelopes' },
  syncReconcile: { method: 'POST' as const, path: '/v1/sync/reconcile' },
  syncReceipts: { method: 'GET' as const, path: '/v1/sync/receipts' },
  domainAuthority: { method: 'GET' as const, path: '/v1/domain-authority' },
  commandQuery: { method: 'GET' as const, path: '/v1/command-query' },
  executeCommand: { method: 'POST' as const, path: '/v1/commands/execute' },
  executeQuery: { method: 'POST' as const, path: '/v1/queries/execute' },
  workspaceOverview: { method: 'GET' as const, path: '/v1/read-models/workspace-overview' },
  notebookOrchestration: { method: 'GET' as const, path: '/v1/notebook-orchestration' },
  notebookPlans: { method: 'POST' as const, path: '/v1/notebook-execution-plans' },
  studyPackageProfile: { method: 'GET' as const, path: '/v1/scientific-study-packages/profile' },
  studyPackages: { method: 'POST' as const, path: '/v1/scientific-study-packages' },
  visualizationProfile: { method: 'GET' as const, path: '/v1/visualization-specs/profile' },
  visualizationSpecs: { method: 'POST' as const, path: '/v1/visualization-specs' },
  visualizationReceipts: { method: 'GET' as const, path: '/v1/visualization-spec-receipts' },
});
