/* Workspace v2.33.0 local-first synchronization runtime. Offline envelopes are draft mutations, never canonical truth. */
interface WorkspaceSyncMutation { action:'put'|'delete'; document?:JsonObject; projectId?:string; title?:string; }
interface WorkspaceSyncEnvelope { schema:'sc-workspace-sync-envelope/1.0'; envelopeId:string; operationId:string; deviceId:string; objectKind:'project'|'notebook'; objectId:string; baseRevision:number; baseFingerprint?:string; clientSequence:number; clientUpdatedAt?:string; mutation:WorkspaceSyncMutation; }
interface WorkspaceSyncReconcileRequest { schema:'sc-workspace-sync-reconcile-request/1.0'; deviceId:string; clientRevisionVector:Record<string,number>; projectIds?:string[]; }
interface WorkspaceSyncResult extends WorkspaceApiEnvelope { status?:string; replayed?:boolean; rehydrateRequired?:boolean; canonicalHead?:unknown; conflict?:unknown; }
class WorkspaceLocalFirstSyncStore {
  private readonly api:WorkspaceTypedApiClient; private readonly storage:Storage|null; private readonly key='sc_workspace_sync_outbox_v2310'; private readonly deviceKey='sc_workspace_sync_device_v2310';
  constructor(api:WorkspaceTypedApiClient,storage:Storage|null=typeof window!=='undefined'?window.localStorage:null){this.api=api;this.storage=storage;}
  deviceId():string{if(!this.storage)return 'volatile-device';let id=this.storage.getItem(this.deviceKey)||'';if(!id){id='device-'+Math.random().toString(36).slice(2)+'-'+Date.now().toString(36);this.storage.setItem(this.deviceKey,id);}return id;}
  private read():WorkspaceSyncEnvelope[]{if(!this.storage)return[];try{const value=JSON.parse(this.storage.getItem(this.key)||'[]');return Array.isArray(value)?value as WorkspaceSyncEnvelope[]:[];}catch(_){return[];}}
  private write(items:WorkspaceSyncEnvelope[]):void{if(this.storage)this.storage.setItem(this.key,JSON.stringify(items));}
  pending():WorkspaceSyncEnvelope[]{return this.read().map(x=>JSON.parse(JSON.stringify(x)) as WorkspaceSyncEnvelope);}
  enqueue(input:Omit<WorkspaceSyncEnvelope,'schema'|'envelopeId'|'operationId'|'deviceId'|'clientSequence'>):WorkspaceSyncEnvelope{const items=this.read();const seq=items.reduce((m,x)=>Math.max(m,x.clientSequence||0),0)+1;const nonce=Date.now().toString(36)+'-'+seq.toString(36);const env:WorkspaceSyncEnvelope={schema:'sc-workspace-sync-envelope/1.0',envelopeId:'env-'+nonce,operationId:'op-'+nonce,deviceId:this.deviceId(),clientSequence:seq,...input};items.push(env);this.write(items);return env;}
  async flush():Promise<WorkspaceSyncResult[]>{const queue=this.read();const kept:WorkspaceSyncEnvelope[]=[];const results:WorkspaceSyncResult[]=[];for(const env of queue){try{const result=await this.api.syncEnvelope(env) as WorkspaceSyncResult;results.push(result);if(result.status==='conflict')kept.push(env);}catch(error){if(error instanceof WorkspaceTypedApiError&&error.status===409){const payload=(error.payload||{}) as WorkspaceSyncResult;results.push(payload);kept.push(env);break;}kept.push(env);break;}}this.write(kept);return results;}
  async reconcile(revisionVector:Record<string,number>,projectIds?:string[]):Promise<WorkspaceApiEnvelope>{return this.api.syncReconcile({schema:'sc-workspace-sync-reconcile-request/1.0',deviceId:this.deviceId(),clientRevisionVector:revisionVector,projectIds});}
  clearApplied():void{this.write([]);}
  diagnostics(){return Object.freeze({schema:'sc-workspace-local-first-sync-client/1.0',version:'2.33.0',backendAuthoritative:true,browserAuthoritativeState:false,offlineOutboxAuthoritative:false,pendingMutationsAreDrafts:true,automaticSemanticMerge:false,pendingCount:this.read().length,deviceId:this.deviceId()});}
}
const SCWorkspaceLocalFirstSyncRuntime=Object.freeze({schema:'sc-workspace-local-first-sync-client-runtime/1.0',version:'2.33.0',backendAuthoritative:true,browserAuthoritativeState:false,offlineOutboxAuthoritative:false,pendingMutationsAreDrafts:true,baseRevisionRequired:true,automaticSemanticMerge:false,create(api:WorkspaceTypedApiClient,storage?:Storage|null){return new WorkspaceLocalFirstSyncStore(api,storage===undefined?(typeof window!=='undefined'?window.localStorage:null):storage);}});
const scwSyncGlobal=window as unknown as {SCWorkspaceLocalFirstSync?:typeof SCWorkspaceLocalFirstSyncRuntime;SCWorkspaceApi?:WorkspaceTypedApiClient;SCWorkspaceSync?:WorkspaceLocalFirstSyncStore;};
scwSyncGlobal.SCWorkspaceLocalFirstSync=SCWorkspaceLocalFirstSyncRuntime;if(scwSyncGlobal.SCWorkspaceApi){scwSyncGlobal.SCWorkspaceSync=SCWorkspaceLocalFirstSyncRuntime.create(scwSyncGlobal.SCWorkspaceApi);}
