from __future__ import annotations
from typing import Any
from .command_query import COMMANDS, QUERIES
from .utils import sha256_hex

CLIENT_CONTRACT_SCHEMA = "sc-workspace-typed-client-contract/1.0"
CLIENT_RUNTIME_SCHEMA = "sc-workspace-typed-client-runtime/1.0"
TYPED_ENDPOINTS: dict[str, dict[str, str]] = {
    "uncertaintyInvestigationWorkspace": {"method":"GET","path":"/v1/uncertainty-investigation-workspace"},
    "uncertaintyAssessmentStore": {"method":"POST","path":"/v1/uncertainty-investigation-workspace/assessments"},
    "uncertaintyAssessments": {"method":"GET","path":"/v1/uncertainty-investigation-workspace/assessments"},
    "uncertaintyAssessment": {"method":"GET","path":"/v1/uncertainty-investigation-workspace/assessments/{assessment_id}"},
    "uncertaintyAssessmentRevisions": {"method":"GET","path":"/v1/uncertainty-investigation-workspace/assessments/{assessment_id}/revisions"},
    "uncertaintyParameterCreate": {"method":"POST","path":"/v1/uncertainty-investigation-workspace/parameters"},
    "uncertaintyParameters": {"method":"GET","path":"/v1/uncertainty-investigation-workspace/parameters"},
    "uncertaintyScenarioCreate": {"method":"POST","path":"/v1/uncertainty-investigation-workspace/scenarios"},
    "uncertaintyScenarios": {"method":"GET","path":"/v1/uncertainty-investigation-workspace/scenarios"},
    "sensitivityAnalysisRequestCreate": {"method":"POST","path":"/v1/uncertainty-investigation-workspace/sensitivity-requests"},
    "sensitivityAnalysisRequests": {"method":"GET","path":"/v1/uncertainty-investigation-workspace/sensitivity-requests"},
    "probabilisticResultBindingCreate": {"method":"POST","path":"/v1/uncertainty-investigation-workspace/result-bindings"},
    "probabilisticResultBindings": {"method":"GET","path":"/v1/uncertainty-investigation-workspace/result-bindings"},
    "uncertaintyInvestigationManifest": {"method":"GET","path":"/v1/uncertainty-investigation-workspace/projects/{project_id}/manifest"},
    "uncertaintyInvestigationGraph": {"method":"GET","path":"/v1/uncertainty-investigation-workspace/projects/{project_id}/graph"},
    "uncertaintyInvestigationDiagnostics": {"method":"GET","path":"/v1/uncertainty-investigation-workspace/projects/{project_id}/diagnostics"},
    "uncertaintyInvestigationSnapshotCreate": {"method":"POST","path":"/v1/uncertainty-investigation-workspace/projects/{project_id}/snapshots"},
    "uncertaintyInvestigationSnapshots": {"method":"GET","path":"/v1/uncertainty-investigation-workspace/projects/{project_id}/snapshots"},
    "quantitativeAnalysisWorkspace": {"method":"GET","path":"/v1/quantitative-analysis-workspace"},
    "quantitativeReconstructionStore": {"method":"POST","path":"/v1/quantitative-analysis-workspace/reconstructions"},
    "quantitativeReconstructions": {"method":"GET","path":"/v1/quantitative-analysis-workspace/reconstructions"},
    "quantitativeReconstruction": {"method":"GET","path":"/v1/quantitative-analysis-workspace/reconstructions/{reconstruction_id}"},
    "quantitativeReconstructionRevisions": {"method":"GET","path":"/v1/quantitative-analysis-workspace/reconstructions/{reconstruction_id}/revisions"},
    "quantitativeInputBindingCreate": {"method":"POST","path":"/v1/quantitative-analysis-workspace/input-bindings"},
    "quantitativeInputBindings": {"method":"GET","path":"/v1/quantitative-analysis-workspace/input-bindings"},
    "quantitativeAnalysisHandoffCreate": {"method":"POST","path":"/v1/quantitative-analysis-workspace/handoffs"},
    "quantitativeAnalysisHandoffs": {"method":"GET","path":"/v1/quantitative-analysis-workspace/handoffs"},
    "quantitativeAnalysisHandoff": {"method":"GET","path":"/v1/quantitative-analysis-workspace/handoffs/{handoff_id}"},
    "quantitativeAnalysisHandoffStatus": {"method":"POST","path":"/v1/quantitative-analysis-workspace/handoffs/{handoff_id}/status"},
    "quantitativeResultBindingCreate": {"method":"POST","path":"/v1/quantitative-analysis-workspace/result-bindings"},
    "quantitativeResultBindings": {"method":"GET","path":"/v1/quantitative-analysis-workspace/result-bindings"},
    "quantitativeAnalysisManifest": {"method":"GET","path":"/v1/quantitative-analysis-workspace/projects/{project_id}/manifest"},
    "quantitativeAnalysisGraph": {"method":"GET","path":"/v1/quantitative-analysis-workspace/projects/{project_id}/graph"},
    "quantitativeAnalysisDiagnostics": {"method":"GET","path":"/v1/quantitative-analysis-workspace/projects/{project_id}/diagnostics"},
    "quantitativeAnalysisSnapshotCreate": {"method":"POST","path":"/v1/quantitative-analysis-workspace/projects/{project_id}/snapshots"},
    "quantitativeAnalysisSnapshots": {"method":"GET","path":"/v1/quantitative-analysis-workspace/projects/{project_id}/snapshots"},
    "investigativeSearchWorkspace": {"method":"GET","path":"/v1/investigative-search-workspace"},
    "savedSearchStore": {"method":"POST","path":"/v1/investigative-search-workspace/saved-searches"},
    "savedSearches": {"method":"GET","path":"/v1/investigative-search-workspace/saved-searches"},
    "savedSearch": {"method":"GET","path":"/v1/investigative-search-workspace/saved-searches/{search_id}"},
    "savedSearchRevisions": {"method":"GET","path":"/v1/investigative-search-workspace/saved-searches/{search_id}/revisions"},
    "investigativeSearchExecute": {"method":"POST","path":"/v1/investigative-search-workspace/executions"},
    "investigativeSearchExecutions": {"method":"GET","path":"/v1/investigative-search-workspace/executions"},
    "investigativeSearchExecution": {"method":"GET","path":"/v1/investigative-search-workspace/executions/{execution_id}"},
    "projectInvestigativeSearch": {"method":"GET","path":"/v1/investigative-search-workspace/projects/{project_id}/search"},
    "crossCaseInvestigativeSearch": {"method":"GET","path":"/v1/investigative-search-workspace/cross-case/search"},
    "investigativeSearchFacets": {"method":"GET","path":"/v1/investigative-search-workspace/projects/{project_id}/facets"},
    "investigativeSearchDiagnostics": {"method":"GET","path":"/v1/investigative-search-workspace/projects/{project_id}/diagnostics"},
    "investigativeSearchSnapshotCreate": {"method":"POST","path":"/v1/investigative-search-workspace/projects/{project_id}/snapshots"},
    "investigativeSearchSnapshots": {"method":"GET","path":"/v1/investigative-search-workspace/projects/{project_id}/snapshots"},
    "investigativeSearchCollectionCreate": {"method":"POST","path":"/v1/investigative-search-workspace/collections"},
    "investigativeSearchCollections": {"method":"GET","path":"/v1/investigative-search-workspace/collections"},
    "investigativeSearchCollection": {"method":"GET","path":"/v1/investigative-search-workspace/collections/{collection_id}"},
    "investigativeSearchDiscoveryGraph": {"method":"GET","path":"/v1/investigative-search-workspace/projects/{project_id}/discovery-graph"},
    "sourceIntegrityWorkspace": {"method":"GET","path":"/v1/source-integrity-workspace"},
    "sourceStore": {"method":"POST","path":"/v1/source-integrity-workspace/sources"},
    "sources": {"method":"GET","path":"/v1/source-integrity-workspace/sources"},
    "source": {"method":"GET","path":"/v1/source-integrity-workspace/sources/{source_id}"},
    "sourceRevisions": {"method":"GET","path":"/v1/source-integrity-workspace/sources/{source_id}/revisions"},
    "sourceProvenanceEventCreate": {"method":"POST","path":"/v1/source-integrity-workspace/provenance-events"},
    "sourceProvenanceEvents": {"method":"GET","path":"/v1/source-integrity-workspace/provenance-events"},
    "sourceCustodyEventCreate": {"method":"POST","path":"/v1/source-integrity-workspace/custody-events"},
    "sourceCustodyEvents": {"method":"GET","path":"/v1/source-integrity-workspace/custody-events"},
    "integrityAssertionCreate": {"method":"POST","path":"/v1/source-integrity-workspace/integrity-assertions"},
    "integrityAssertions": {"method":"GET","path":"/v1/source-integrity-workspace/integrity-assertions"},
    "sourceEvidenceBindingCreate": {"method":"POST","path":"/v1/source-integrity-workspace/evidence-bindings"},
    "sourceEvidenceBindings": {"method":"GET","path":"/v1/source-integrity-workspace/evidence-bindings"},
    "sourceIntegrityGraph": {"method":"GET","path":"/v1/source-integrity-workspace/projects/{project_id}/graph"},
    "sourceIntegrityDiagnostics": {"method":"GET","path":"/v1/source-integrity-workspace/projects/{project_id}/diagnostics"},
    "sourceIntegrityAssessment": {"method":"GET","path":"/v1/source-integrity-workspace/projects/{project_id}/integrity"},
    "sourceIntegritySnapshotCreate": {"method":"POST","path":"/v1/source-integrity-workspace/projects/{project_id}/snapshots"},
    "sourceIntegritySnapshots": {"method":"GET","path":"/v1/source-integrity-workspace/projects/{project_id}/snapshots"},

    "mediaProvenanceWorkspace": {"method":"GET","path":"/v1/media-provenance-workspace"},
    "mediaArtifactStore": {"method":"POST","path":"/v1/media-provenance-workspace/artifacts"},
    "mediaArtifacts": {"method":"GET","path":"/v1/media-provenance-workspace/artifacts"},
    "mediaArtifact": {"method":"GET","path":"/v1/media-provenance-workspace/artifacts/{artifact_id}"},
    "mediaArtifactRevisions": {"method":"GET","path":"/v1/media-provenance-workspace/artifacts/{artifact_id}/revisions"},
    "mediaLocatorCreate": {"method":"POST","path":"/v1/media-provenance-workspace/locators"},
    "mediaLocators": {"method":"GET","path":"/v1/media-provenance-workspace/locators"},
    "mediaDerivativeCreate": {"method":"POST","path":"/v1/media-provenance-workspace/derivatives"},
    "mediaDerivatives": {"method":"GET","path":"/v1/media-provenance-workspace/derivatives"},
    "mediaContextLinkCreate": {"method":"POST","path":"/v1/media-provenance-workspace/context-links"},
    "mediaContextLinks": {"method":"GET","path":"/v1/media-provenance-workspace/context-links"},
    "mediaRelationCreate": {"method":"POST","path":"/v1/media-provenance-workspace/relations"},
    "mediaRelations": {"method":"GET","path":"/v1/media-provenance-workspace/relations"},
    "mediaProvenanceGraph": {"method":"GET","path":"/v1/media-provenance-workspace/projects/{project_id}/graph"},
    "mediaDiagnostics": {"method":"GET","path":"/v1/media-provenance-workspace/projects/{project_id}/diagnostics"},
    "mediaIntegrity": {"method":"GET","path":"/v1/media-provenance-workspace/projects/{project_id}/integrity"},
    "mediaSnapshotCreate": {"method":"POST","path":"/v1/media-provenance-workspace/projects/{project_id}/snapshots"},
    "mediaSnapshots": {"method":"GET","path":"/v1/media-provenance-workspace/projects/{project_id}/snapshots"},

    "spatialEvidenceWorkspace": {"method":"GET","path":"/v1/spatial-evidence-workspace"},
    "spatialObservationStore": {"method":"POST","path":"/v1/spatial-evidence-workspace/observations"},
    "spatialObservations": {"method":"GET","path":"/v1/spatial-evidence-workspace/observations"},
    "spatialObservation": {"method":"GET","path":"/v1/spatial-evidence-workspace/observations/{observation_id}"},
    "spatialObservationRevisions": {"method":"GET","path":"/v1/spatial-evidence-workspace/observations/{observation_id}/revisions"},
    "spatialContextLinkCreate": {"method":"POST","path":"/v1/spatial-evidence-workspace/context-links"},
    "spatialContextLinks": {"method":"GET","path":"/v1/spatial-evidence-workspace/context-links"},
    "spatialRelationCreate": {"method":"POST","path":"/v1/spatial-evidence-workspace/relations"},
    "spatialRelations": {"method":"GET","path":"/v1/spatial-evidence-workspace/relations"},
    "spatialMapProjection": {"method":"GET","path":"/v1/spatial-evidence-workspace/projects/{project_id}/map"},
    "spatialGraph": {"method":"GET","path":"/v1/spatial-evidence-workspace/projects/{project_id}/graph"},
    "spatialDiagnostics": {"method":"GET","path":"/v1/spatial-evidence-workspace/projects/{project_id}/diagnostics"},
    "spatialSnapshotCreate": {"method":"POST","path":"/v1/spatial-evidence-workspace/projects/{project_id}/snapshots"},
    "spatialSnapshots": {"method":"GET","path":"/v1/spatial-evidence-workspace/projects/{project_id}/snapshots"},

    "documentaryEvidenceWorkspace": {"method":"GET","path":"/v1/documentary-evidence-workspace"},
    "documentStore": {"method":"POST","path":"/v1/documentary-evidence-workspace/documents"},
    "documents": {"method":"GET","path":"/v1/documentary-evidence-workspace/documents"},
    "document": {"method":"GET","path":"/v1/documentary-evidence-workspace/documents/{document_id}"},
    "documentRevisions": {"method":"GET","path":"/v1/documentary-evidence-workspace/documents/{document_id}/revisions"},
    "documentExcerptCreate": {"method":"POST","path":"/v1/documentary-evidence-workspace/excerpts"},
    "documentExcerpts": {"method":"GET","path":"/v1/documentary-evidence-workspace/excerpts"},
    "testimonyStore": {"method":"POST","path":"/v1/documentary-evidence-workspace/testimonies"},
    "testimonies": {"method":"GET","path":"/v1/documentary-evidence-workspace/testimonies"},
    "testimony": {"method":"GET","path":"/v1/documentary-evidence-workspace/testimonies/{testimony_id}"},
    "testimonyRevisions": {"method":"GET","path":"/v1/documentary-evidence-workspace/testimonies/{testimony_id}/revisions"},
    "documentaryContextLinkCreate": {"method":"POST","path":"/v1/documentary-evidence-workspace/context-links"},
    "documentaryContextLinks": {"method":"GET","path":"/v1/documentary-evidence-workspace/context-links"},
    "testimonyRelationCreate": {"method":"POST","path":"/v1/documentary-evidence-workspace/testimony-relations"},
    "testimonyRelations": {"method":"GET","path":"/v1/documentary-evidence-workspace/testimony-relations"},
    "documentaryGraph": {"method":"GET","path":"/v1/documentary-evidence-workspace/projects/{project_id}/graph"},
    "documentaryAnalysis": {"method":"GET","path":"/v1/documentary-evidence-workspace/projects/{project_id}/analysis"},
    "documentarySnapshotCreate": {"method":"POST","path":"/v1/documentary-evidence-workspace/projects/{project_id}/snapshots"},
    "documentarySnapshots": {"method":"GET","path":"/v1/documentary-evidence-workspace/projects/{project_id}/snapshots"},
    "entityResolutionWorkspace": {"method":"GET","path":"/v1/entity-resolution-workspace"},
    "entityStore": {"method":"POST","path":"/v1/entity-resolution-workspace/entities"},
    "entities": {"method":"GET","path":"/v1/entity-resolution-workspace/entities"},
    "entity": {"method":"GET","path":"/v1/entity-resolution-workspace/entities/{entity_id}"},
    "entityRevisions": {"method":"GET","path":"/v1/entity-resolution-workspace/entities/{entity_id}/revisions"},
    "entityAliasCreate": {"method":"POST","path":"/v1/entity-resolution-workspace/aliases"},
    "entityAliases": {"method":"GET","path":"/v1/entity-resolution-workspace/aliases"},
    "entityIdentifierCreate": {"method":"POST","path":"/v1/entity-resolution-workspace/identifiers"},
    "entityIdentifiers": {"method":"GET","path":"/v1/entity-resolution-workspace/identifiers"},
    "entityRelationshipCreate": {"method":"POST","path":"/v1/entity-resolution-workspace/relationships"},
    "entityRelationships": {"method":"GET","path":"/v1/entity-resolution-workspace/relationships"},
    "entityContextLinkCreate": {"method":"POST","path":"/v1/entity-resolution-workspace/context-links"},
    "entityContextLinks": {"method":"GET","path":"/v1/entity-resolution-workspace/context-links"},
    "entityMatchCandidateCreate": {"method":"POST","path":"/v1/entity-resolution-workspace/match-candidates"},
    "entityMatchCandidates": {"method":"GET","path":"/v1/entity-resolution-workspace/match-candidates"},
    "entityMatchCandidateReview": {"method":"POST","path":"/v1/entity-resolution-workspace/match-candidates/{candidate_id}/review"},
    "entityResolutionGraph": {"method":"GET","path":"/v1/entity-resolution-workspace/projects/{project_id}/graph"},
    "entityResolutionDiagnostics": {"method":"GET","path":"/v1/entity-resolution-workspace/projects/{project_id}/diagnostics"},
    "entityResolutionSnapshotCreate": {"method":"POST","path":"/v1/entity-resolution-workspace/projects/{project_id}/snapshots"},
    "entityResolutionSnapshots": {"method":"GET","path":"/v1/entity-resolution-workspace/projects/{project_id}/snapshots"},
    "investigationTimelineWorkspace": {"method":"GET","path":"/v1/investigation-timeline-workspace"},
    "investigationEventStore": {"method":"POST","path":"/v1/investigation-timeline-workspace/events"},
    "investigationEvents": {"method":"GET","path":"/v1/investigation-timeline-workspace/events"},
    "investigationEvent": {"method":"GET","path":"/v1/investigation-timeline-workspace/events/{event_id}"},
    "investigationEventRevisions": {"method":"GET","path":"/v1/investigation-timeline-workspace/events/{event_id}/revisions"},
    "investigationEventStatementLinkCreate": {"method":"POST","path":"/v1/investigation-timeline-workspace/event-statement-links"},
    "investigationEventStatementLinks": {"method":"GET","path":"/v1/investigation-timeline-workspace/event-statement-links"},
    "investigationEventRelationCreate": {"method":"POST","path":"/v1/investigation-timeline-workspace/event-relations"},
    "investigationEventRelations": {"method":"GET","path":"/v1/investigation-timeline-workspace/event-relations"},
    "investigationTimeline": {"method":"GET","path":"/v1/investigation-timeline-workspace/projects/{project_id}/timeline"},
    "investigationReconstructionGraph": {"method":"GET","path":"/v1/investigation-timeline-workspace/projects/{project_id}/reconstruction-graph"},
    "investigationTemporalDiagnostics": {"method":"GET","path":"/v1/investigation-timeline-workspace/projects/{project_id}/temporal-diagnostics"},
    "investigationTimelineSnapshotCreate": {"method":"POST","path":"/v1/investigation-timeline-workspace/projects/{project_id}/snapshots"},
    "investigationTimelineSnapshots": {"method":"GET","path":"/v1/investigation-timeline-workspace/projects/{project_id}/snapshots"},
    "investigationGraphWorkspace": {"method":"GET","path":"/v1/investigation-graph-workspace"},
    "investigationHypothesisSetStore": {"method":"POST","path":"/v1/investigation-graph-workspace/hypothesis-sets"},
    "investigationHypothesisSets": {"method":"GET","path":"/v1/investigation-graph-workspace/hypothesis-sets"},
    "investigationHypothesisSet": {"method":"GET","path":"/v1/investigation-graph-workspace/hypothesis-sets/{hypothesis_set_id}"},
    "investigationGraph": {"method":"GET","path":"/v1/investigation-graph-workspace/projects/{project_id}/graph"},
    "investigationContradictions": {"method":"GET","path":"/v1/investigation-graph-workspace/projects/{project_id}/contradictions"},
    "investigationHypothesisMatrix": {"method":"GET","path":"/v1/investigation-graph-workspace/projects/{project_id}/hypothesis-matrix"},
    "investigationCoverage": {"method":"GET","path":"/v1/investigation-graph-workspace/projects/{project_id}/coverage"},
    "investigationGraphSnapshotCreate": {"method":"POST","path":"/v1/investigation-graph-workspace/projects/{project_id}/snapshots"},
    "investigationGraphSnapshots": {"method":"GET","path":"/v1/investigation-graph-workspace/projects/{project_id}/snapshots"},
    "investigativeResearchWorkspace": {"method":"GET","path":"/v1/investigative-research-workspace"},
    "investigationStatementStore": {"method":"POST","path":"/v1/investigative-research-workspace/statements"},
    "investigationStatements": {"method":"GET","path":"/v1/investigative-research-workspace/statements"},
    "investigationStatement": {"method":"GET","path":"/v1/investigative-research-workspace/statements/{statement_id}"},
    "investigationStatementRevisions": {"method":"GET","path":"/v1/investigative-research-workspace/statements/{statement_id}/revisions"},
    "investigationEvidenceLinkCreate": {"method":"POST","path":"/v1/investigative-research-workspace/evidence-links"},
    "investigationEvidenceLinks": {"method":"GET","path":"/v1/investigative-research-workspace/evidence-links"},
    "investigationStatementRelationCreate": {"method":"POST","path":"/v1/investigative-research-workspace/statement-relations"},
    "investigationStatementRelations": {"method":"GET","path":"/v1/investigative-research-workspace/statement-relations"},
    "investigativeResearchProject": {"method":"GET","path":"/v1/investigative-research-workspace/projects/{project_id}"},
    "investigativeResearchSnapshotCreate": {"method":"POST","path":"/v1/investigative-research-workspace/projects/{project_id}/snapshots"},
    "investigativeResearchSnapshots": {"method":"GET","path":"/v1/investigative-research-workspace/projects/{project_id}/snapshots"},
    "visualResearchWorkspace": {"method": "GET", "path": "/v1/visual-research-workspace"},
    "visualResearchProject": {"method": "GET", "path": "/v1/visual-research-workspace/projects/{project_id}"},
    "visualResearchVisualization": {"method": "GET", "path": "/v1/visual-research-workspace/projects/{project_id}/visualizations/{visualization_id}"},
    "visualResearchVisualizationBind": {"method": "POST", "path": "/v1/visual-research-workspace/projects/{project_id}/visualizations/{visualization_id}/bind"},
    "visualResearchSnapshotCreate": {"method": "POST", "path": "/v1/visual-research-workspace/projects/{project_id}/snapshots"},
    "visualResearchSnapshots": {"method": "GET", "path": "/v1/visual-research-workspace/projects/{project_id}/snapshots"},
    "analyticsRProvider": {"method": "GET", "path": "/v1/analytics/providers/catalystanalyticsr"},
    "analyticsRProviderValidate": {"method": "POST", "path": "/v1/analytics/providers/catalystanalyticsr/validate"},
    "analyticsRProviderExecute": {"method": "POST", "path": "/v1/analytics/providers/catalystanalyticsr/execute"},
    "analyticsProviderReceipts": {"method": "GET", "path": "/v1/analytics/provider-receipts"},
    "analyticsProviderReceipt": {"method": "GET", "path": "/v1/analytics/provider-receipts/{receipt_id}"},
    "executionProvenance": {"method": "GET", "path": "/v1/execution-provenance"},
    "executionProvenanceProject": {"method": "GET", "path": "/v1/execution-provenance/projects/{project_id}"},
    "executionProvenanceRun": {"method": "GET", "path": "/v1/execution-provenance/projects/{project_id}/runs/{run_id}"},
    "executionProvenanceSnapshotCreate": {"method": "POST", "path": "/v1/execution-provenance/projects/{project_id}/snapshots"},
    "executionProvenanceSnapshots": {"method": "GET", "path": "/v1/execution-provenance/projects/{project_id}/snapshots"},
    "researchSessionBindings": {"method": "GET", "path": "/v1/research-bindings"},
    "researchSessionProjectBindings": {"method": "GET", "path": "/v1/research-bindings/projects/{project_id}"},
    "researchSessionBindingCreate": {"method": "POST", "path": "/v1/research-bindings/projects/{project_id}"},
    "researchSessionBindingsReconcile": {"method": "POST", "path": "/v1/research-bindings/projects/{project_id}/reconcile"},
    "unifiedResearchContext": {"method": "GET", "path": "/v1/research-context"},
    "unifiedResearchProjectContext": {"method": "GET", "path": "/v1/research-context/projects/{project_id}"},
    "unifiedResearchContextSnapshotCreate": {"method": "POST", "path": "/v1/research-context/projects/{project_id}/snapshots"},
    "unifiedResearchContextSnapshots": {"method": "GET", "path": "/v1/research-context/projects/{project_id}/snapshots"},
    "platformCoreRuntime": {"method": "GET", "path": "/v1/platform-core-runtime"},
    "platformCoreRuntimeReadiness": {"method": "GET", "path": "/v1/platform-core-runtime/readiness"},
    "platformCoreSessionCreate": {"method": "POST", "path": "/v1/platform-core-runtime/sessions"},
    "platformCoreProjectContext": {"method": "GET", "path": "/v1/platform-core-runtime/projects/{project_id}"},
    "platformCoreObjectBind": {"method": "POST", "path": "/v1/platform-core-runtime/object-bindings"},
    "platformCoreExecutionBind": {"method": "POST", "path": "/v1/platform-core-runtime/execution-bindings"},
    "platformCoreVisualBind": {"method": "POST", "path": "/v1/platform-core-runtime/visual-bindings"},
    "platformCorePackageBind": {"method": "POST", "path": "/v1/platform-core-runtime/package-bindings"},
    "platformCoreHandoffBind": {"method": "POST", "path": "/v1/platform-core-runtime/handoff-bindings"},
    "platformCoreSessionSummary": {"method": "GET", "path": "/v1/platform-core-runtime/sessions/{session_id}/summary"},
    "platformCoreSessionLineage": {"method": "GET", "path": "/v1/platform-core-runtime/sessions/{session_id}/lineage"},
    "platformCoreSessionBundle": {"method": "GET", "path": "/v1/platform-core-runtime/sessions/{session_id}/bundle"},
    "platformCoreRuntimeReceipts": {"method": "GET", "path": "/v1/platform-core-runtime/receipts"},
    "backendNativeWorkspace": {"method": "GET", "path": "/v1/backend-native-workspace"},
    "backendNativeBootstrap": {"method": "GET", "path": "/v1/backend-native-workspace/bootstrap"},
    "frontendRuntime": {"method": "GET", "path": "/v1/frontend-runtime"},
    "productionCertification": {"method": "GET", "path": "/v1/production-certification"},
    "authorizationProfile": {"method": "GET", "path": "/v1/authorization"},
    "authorizationIdentity": {"method": "GET", "path": "/v1/authorization/identity"},
    "authorizationEvaluate": {"method": "POST", "path": "/v1/authorization/evaluate"},
    "authorizationDecisions": {"method": "GET", "path": "/v1/authorization/decisions"},
    "clientContracts": {"method": "GET", "path": "/v1/client-contracts"},
    "thinClientState": {"method": "GET", "path": "/v1/thin-client-state"},
    "thinClientBootstrap": {"method": "GET", "path": "/v1/thin-client-state/bootstrap"},
    "syncProfile": {"method": "GET", "path": "/v1/sync"},
    "syncBootstrap": {"method": "GET", "path": "/v1/sync/bootstrap"},
    "syncEnvelope": {"method": "POST", "path": "/v1/sync/envelopes"},
    "syncReconcile": {"method": "POST", "path": "/v1/sync/reconcile"},
    "syncReceipts": {"method": "GET", "path": "/v1/sync/receipts"},
    "scientificObjectProfile": {"method": "GET", "path": "/v1/scientific-objects/profile"},
    "scientificObjects": {"method": "GET", "path": "/v1/scientific-objects"},
    "scientificObjectGet": {"method": "GET", "path": "/v1/scientific-objects/{kind}/{object_id}"},
    "scientificObjectHistory": {"method": "GET", "path": "/v1/scientific-objects/{kind}/{object_id}/revisions"},
    "scientificObjectRelations": {"method": "GET", "path": "/v1/scientific-objects/{kind}/{object_id}/relations"},
    "handoffProfile": {"method": "GET", "path": "/v1/handoffs/profile"},
    "handoffCreate": {"method": "POST", "path": "/v1/handoffs"},
    "handoffGet": {"method": "GET", "path": "/v1/handoffs/{handoff_id}"},
    "handoffAccept": {"method": "POST", "path": "/v1/handoffs/{handoff_id}/accept"},
    "handoffReceipts": {"method": "GET", "path": "/v1/handoff-receipts"},
    "domainAuthority": {"method": "GET", "path": "/v1/domain-authority"},
    "commandQuery": {"method": "GET", "path": "/v1/command-query"},
    "executeCommand": {"method": "POST", "path": "/v1/commands/execute"},
    "executeQuery": {"method": "POST", "path": "/v1/queries/execute"},
    "workspaceOverview": {"method": "GET", "path": "/v1/read-models/workspace-overview"},
    "notebookOrchestration": {"method": "GET", "path": "/v1/notebook-orchestration"},
    "notebookPlans": {"method": "POST", "path": "/v1/notebook-execution-plans"},
    "studyPackageProfile": {"method": "GET", "path": "/v1/scientific-study-packages/profile"},
    "studyPackages": {"method": "POST", "path": "/v1/scientific-study-packages"},
    "visualizationProfile": {"method": "GET", "path": "/v1/visualization-specs/profile"},
    "visualizationSpecs": {"method": "POST", "path": "/v1/visualization-specs"},
    "visualizationReceipts": {"method": "GET", "path": "/v1/visualization-spec-receipts"},
}
REQUEST_SCHEMAS = {
    "mediaArtifactStore": "sc-workspace-investigation-media-artifact-request/1.0",
    "mediaLocatorCreate": "sc-workspace-investigation-media-locator-request/1.0",
    "mediaDerivativeCreate": "sc-workspace-investigation-media-derivative-request/1.0",
    "mediaContextLinkCreate": "sc-workspace-investigation-media-context-link-request/1.0",
    "mediaRelationCreate": "sc-workspace-investigation-media-relation-request/1.0",
    "mediaSnapshotCreate": "sc-workspace-investigation-media-snapshot-request/1.0",
    "documentStore": "sc-workspace-investigation-document-request/1.0",
    "documentExcerptCreate": "sc-workspace-investigation-document-excerpt-request/1.0",
    "testimonyStore": "sc-workspace-investigation-testimony-request/1.0",
    "documentaryContextLinkCreate": "sc-workspace-investigation-documentary-context-link-request/1.0",
    "testimonyRelationCreate": "sc-workspace-investigation-testimony-relation-request/1.0",
    "documentarySnapshotCreate": "sc-workspace-investigation-documentary-snapshot-request/1.0",
    "entityStore": "sc-workspace-investigation-entity-request/1.0",
    "entityAliasCreate": "sc-workspace-investigation-entity-alias-request/1.0",
    "entityIdentifierCreate": "sc-workspace-investigation-entity-identifier-request/1.0",
    "entityRelationshipCreate": "sc-workspace-investigation-entity-relationship-request/1.0",
    "entityContextLinkCreate": "sc-workspace-investigation-entity-context-link-request/1.0",
    "entityMatchCandidateCreate": "sc-workspace-investigation-entity-match-candidate-request/1.0",
    "entityMatchCandidateReview": "sc-workspace-investigation-entity-match-review-request/1.0",
    "entityResolutionSnapshotCreate": "sc-workspace-investigation-entity-resolution-snapshot-request/1.0",
    "investigationHypothesisSetStore": "sc-workspace-investigation-hypothesis-set-request/1.0",
    "investigationGraphSnapshotCreate": "sc-workspace-investigation-graph-snapshot-request/1.0",
    "investigationStatementStore": "sc-workspace-investigation-statement-request/1.0",
    "investigationEvidenceLinkCreate": "sc-workspace-investigation-evidence-link-request/1.0",
    "investigationStatementRelationCreate": "sc-workspace-investigation-statement-relation-request/1.0",
    "investigativeResearchSnapshotCreate": "sc-workspace-investigative-research-snapshot-request/1.0",
    "quantitativeReconstructionStore": "sc-workspace-quantitative-reconstruction-request/1.0",
    "quantitativeInputBindingCreate": "sc-workspace-quantitative-input-binding-request/1.0",
    "quantitativeAnalysisHandoffCreate": "sc-workspace-quantitative-analysis-handoff-request/1.0",
    "quantitativeAnalysisHandoffStatus": "sc-workspace-quantitative-analysis-handoff-status-request/1.0",
    "quantitativeResultBindingCreate": "sc-workspace-quantitative-result-binding-request/1.0",
    "quantitativeAnalysisSnapshotCreate": "sc-workspace-quantitative-analysis-snapshot-request/1.0",
    "visualResearchVisualizationBind": "sc-workspace-visual-research-binding-request/1.0",
    "visualResearchSnapshotCreate": "sc-workspace-visual-research-workspace-snapshot-request/1.0",
    "executionProvenanceSnapshotCreate": "sc-workspace-scientific-execution-provenance-snapshot-request/1.0",
    "researchSessionBindingCreate": "sc-workspace-research-session-binding-request/1.0",
    "researchSessionBindingsReconcile": "sc-workspace-research-session-binding-reconcile-request/1.0",
    "unifiedResearchContextSnapshotCreate": "sc-workspace-unified-research-project-context-snapshot-request/1.0",
    "platformCoreSessionCreate": "sc-workspace-platform-core-session-request/1.0",
    "platformCoreObjectBind": "sc-workspace-platform-core-object-binding-request/1.0",
    "platformCoreExecutionBind": "sc-workspace-platform-core-execution-binding-request/1.0",
    "platformCoreVisualBind": "sc-workspace-platform-core-visual-binding-request/1.0",
    "platformCorePackageBind": "sc-workspace-platform-core-package-binding-request/1.0",
    "platformCoreHandoffBind": "sc-workspace-platform-core-handoff-binding-request/1.0",
    "executeCommand": "sc-workspace-command-request/1.0",
    "executeQuery": "sc-workspace-query-request/1.0",
    "notebookPlans": "sc-workspace-notebook-execution-plan-request/1.0",
    "studyPackages": "sc-workspace-scientific-study-package-request/1.0",
    "visualizationSpecs": "sc-workspace-visualization-spec-request/1.0",
    "syncEnvelope": "sc-workspace-sync-envelope/1.0",
    "syncReconcile": "sc-workspace-sync-reconcile-request/1.0",
    "handoffCreate": "sc-workspace-research-handoff-request/1.0",
    "handoffAccept": "sc-workspace-research-handoff-accept-request/1.0",
    "authorizationEvaluate": "sc-workspace-authorization-evaluate-request/1.0",
}

def _typed_openapi_projection(openapi: dict[str, Any]) -> dict[str, Any]:
    paths = openapi.get("paths") or {}
    projection: dict[str, Any] = {"openapi": openapi.get("openapi"), "version": (openapi.get("info") or {}).get("version"), "paths": {}}
    for key, endpoint in TYPED_ENDPOINTS.items():
        path = endpoint["path"]
        method = endpoint["method"].lower()
        operation = (paths.get(path) or {}).get(method)
        projection["paths"][key] = {
            "method": endpoint["method"], "path": path,
            "operationId": (operation or {}).get("operationId", ""),
            "requestBody": (operation or {}).get("requestBody"),
            "responses": (operation or {}).get("responses"),
        }
    return projection

def profile(openapi: dict[str, Any]) -> dict[str, Any]:
    projection = _typed_openapi_projection(openapi)
    missing = [key for key, item in projection["paths"].items() if not item.get("operationId")]
    return {
        "schema": CLIENT_CONTRACT_SCHEMA,
        "workspaceVersion": "3.17.0",
        "mode": "generated-typescript-backend-native-scientific-workspace-client",
        "backendAuthoritative": True,
        "browserAuthoritativeState": False,
        "transport": "wordpress-server-proxy",
        "browserDirectBackendAccess": False,
        "serviceCredentialsBrowserVisible": False,
        "generatedFromOpenApi": True,
        "openApiProjectionSha256": sha256_hex(projection),
        "typedEndpointCount": len(TYPED_ENDPOINTS),
        "typedEndpoints": TYPED_ENDPOINTS,
        "requestSchemas": REQUEST_SCHEMAS,
        "commandCount": len(COMMANDS), "commands": list(COMMANDS),
        "queryCount": len(QUERIES), "queries": list(QUERIES),
        "strictTypeScript": True,
        "runtimeEnvelopeChecks": True,
        "arbitraryCodeExecution": False,
        "missingOpenApiOperations": missing,
    }
