#!/usr/bin/env python3
from __future__ import annotations
import argparse
from pathlib import Path
from app.main import app
from app.client_contracts import profile
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'frontend/typed-client/src/00-generated-contracts.ts'
def quote_union(items): return ' | '.join(repr(x) for x in items)
def render():
    item=profile(app.openapi())
    endpoints='\n'.join(f"  {k}: {{ method: '{v['method']}' as const, path: '{v['path']}' }}," for k,v in item['typedEndpoints'].items())
    return f'''/* AUTO-GENERATED by scripts/generate_typed_client_contracts_v2360.py. DO NOT EDIT. */\nconst SCW_TYPED_CONTRACT_VERSION = '2.36.0' as const;\nconst SCW_TYPED_CONTRACT_SCHEMA = '{item['schema']}' as const;\nconst SCW_OPENAPI_PROJECTION_SHA256 = '{item['openApiProjectionSha256']}' as const;\n\ntype WorkspaceCommand = {quote_union(item['commands'])};\ntype WorkspaceQuery = {quote_union(item['queries'])};\ntype JsonObject = {{ [key: string]: unknown }};\ntype WorkspaceScientificObjectKind = 'artifact'|'dataset'|'model'|'parameter-set'|'execution-run'|'execution-environment'|'runtime-adapter'|'study-package'|'visualization-spec'|'scientific-receipt';\ntype WorkspaceProduct = 'workspace'|'knowledge-library'|'research-librarian'|'workbench'|'research-lab'|'decision-studio'|'site-intelligence'|'catalyst-data'|'platform-core';\ntype WorkspaceHandoffIntent = 'analyze'|'simulate'|'visualize'|'validate'|'compare'|'decide'|'publish'|'investigate'|'cite'|'continue-research';\ninterface WorkspaceCommandRequest {{ schema: 'sc-workspace-command-request/1.0'; command: WorkspaceCommand; commandId?: string; idempotencyKey?: string; payload: JsonObject; }}\ninterface WorkspaceQueryRequest {{ schema: 'sc-workspace-query-request/1.0'; query: WorkspaceQuery; parameters?: JsonObject; }}\ninterface NotebookExecutionPlanRequest {{ schema: 'sc-workspace-notebook-execution-plan-request/1.0'; notebookId: string; expectedNotebookRevision?: number; selectedCellIds?: string[]; strictDependencies?: boolean; }}\ninterface ScientificStudyPackageRequest {{ schema: 'sc-workspace-scientific-study-package-request/1.0'; projectId: string; title?: string; description?: string; selectedNotebookIds?: string[]; includeArtifactBlobs?: boolean; includeScientificReceipts?: boolean; }}\ninterface WorkspaceSyncMutation {{ action: 'put'|'delete'; document?: JsonObject; projectId?: string; title?: string; }}
interface WorkspaceSyncEnvelope {{ schema: 'sc-workspace-sync-envelope/1.0'; envelopeId: string; operationId: string; deviceId: string; objectKind: 'project'|'notebook'; objectId: string; baseRevision: number; baseFingerprint?: string; clientSequence: number; clientUpdatedAt?: string; mutation: WorkspaceSyncMutation; }}
interface WorkspaceSyncReconcileRequest {{ schema: 'sc-workspace-sync-reconcile-request/1.0'; deviceId: string; clientRevisionVector: Record<string,number>; projectIds?: string[]; }}
interface WorkspaceHandoffObjectRef {{ kind: WorkspaceScientificObjectKind; objectId: string; revision?: number; fingerprint?: string; }}
interface WorkspaceResearchHandoffRequest {{ schema: 'sc-workspace-research-handoff-request/1.0'; handoffId?: string; projectId?: string; sourceProduct: WorkspaceProduct; destinationProduct: WorkspaceProduct; intent: WorkspaceHandoffIntent; objects: WorkspaceHandoffObjectRef[]; context?: JsonObject; }}
interface WorkspaceResearchHandoffAcceptRequest {{ schema: 'sc-workspace-research-handoff-accept-request/1.0'; destinationProduct: WorkspaceProduct; destinationObjectId?: string; destinationReceiptId?: string; notes?: JsonObject; }}
interface WorkspaceAuthorizationEvaluateRequest {{ schema: 'sc-workspace-authorization-evaluate-request/1.0'; action: 'workspace.read'|'workspace.write'|'workspace.execute'|'workspace.sync'|'workspace.handoff.prepare'|'workspace.handoff.accept'|'workspace.authorization.inspect'|'workspace.authorization.evaluate'; resourceKind?: 'workspace'|'project'|'notebook'|'artifact'|'dataset'|'model'|'execution'|'visualization'|'study-package'|'handoff'|'authorization'; resourceId?: string; projectId?: string; context?: JsonObject; }}
interface VisualizationSpecRequest {{ schema: 'sc-workspace-visualization-spec-request/1.0'; visualizationId?: string; projectId: string; title?: string; expectedRevision?: number; operationId?: string; spec: JsonObject; }}\ninterface WorkspaceApiEnvelope {{ schema?: string; ok?: boolean; [key: string]: unknown }}\nconst SCW_TYPED_ENDPOINTS = Object.freeze({{\n{endpoints}\n}});\n'''
def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args(); rendered=render()
    if args.check:
        if not OUT.exists() or OUT.read_text()!=rendered: raise SystemExit('ERROR: generated TypeScript contracts are stale')
        print('PASS: generated TypeScript contracts match backend OpenAPI projection'); return
    OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(rendered); print(f'WROTE {OUT}')
if __name__=='__main__': main()
