#!/usr/bin/env python3
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
MAN=json.loads((ROOT/'release-manifest-v0.51.0.json').read_text())
REG=json.loads((ROOT/'registry/workspace-product-record-v0.51.0.json').read_text())
PREV=json.loads((ROOT/'history/release-manifest-v0.50.0.json').read_text())
MAIN=(ROOT/'wordpress/sustainable-catalyst-workspace/sustainable-catalyst-workspace.php').read_text()
PHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace.php').read_text()
REGPHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace-registry.php').read_text()
JS=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/workspace-v0.51.0.js').read_text()
HELP=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-grounded-research-assistant-v1.js').read_text()
CSS=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/css/workspace-v0.51.0.css').read_text()
def check(v,label):
 if not v: raise SystemExit('FAIL - '+label)
 print('PASS - '+label)
check('Version: 0.51.0' in MAIN,'plugin version')
check((MAN['version'],MAN['previous_version'],MAN['release_name'])==('0.51.0','0.50.0','Grounded Research Assistant II'),'release lineage')
check(PREV['version']=='0.50.0' and PREV['release_name']=='Workspace Experience Consolidation','v0.50 predecessor retained')
check((MAN['storage_schema_version'],MAN['project_schema'],MAN['export_schema'])==(35,'sc-workspace-project/20.0','sc-workspace-project-export/20.0'),'schema stable')
check(not MAN['schema_migration_required'] and MAN['migration']['grounded_research_assistant_only_release'] and not MAN['migration']['grounded_research_canonical_data_rewrite'],'assistance-only boundary')
check(MAN['grounded_research_assistant']['scope_selection']=='explicit-multi-record' and MAN['grounded_research_assistant']['citation_enforcement'],'explicit scope and citation enforcement')
check(MAN['grounded_research_assistant']['provider_neutral'] and not MAN['grounded_research_assistant']['automatic_ai'],'provider-neutral no automatic AI')
check(MAN['grounded_research_assistant']['human_review_required'] and MAN['grounded_research_assistant']['materialization']=='explicit-document-only','review/materialization boundary')
check('prepareRequest' in HELP and 'citationCoverage' in HELP and 'applyResponse' in HELP and 'groundingFingerprint' in HELP,'assistant runtime surface')
check('data-scw-grounded-research-assistant' in PHP and 'data-scw-grounded-add-selected' in PHP and 'data-scw-grounded-materialize' in PHP,'assistant UI rendered')
check("'/grounded-research-assistant-contract'" in PHP and 'public function grounded_research_assistant_contract()' in PHP,'public assistant contract')
check('sc-workspace-grounded-research-assistant-v1.js' in PHP and 'workspace-v0.51.0.js' in PHP and 'workspace-v0.51.0.css' in PHP,'v0.51 assets enqueued')
check('.scw-editorial-header-bar{height:4px' in CSS,'4px editorial header retained')
check((REG['public_version'],REG['previous_version'])==('0.51.0','0.50.0'),'registry lineage')
check("BACKUP_KEY = 'sc_workspace_registry_backup_v0510'" in REGPHP and "PENDING_KEY = 'sc_workspace_registry_pending_v0510'" in REGPHP and 'LEGACY_PENDING_KEY_V0500' in REGPHP,'registry retry lineage')
check("'0.51.0'" in JS and 'renderGroundedResearchAssistant' in JS,'main runtime current version and assistant integration')
files=list((ROOT/'schemas').glob('*.json'))+[ROOT/'release-manifest-v0.51.0.json',ROOT/'registry/workspace-product-record-v0.51.0.json']
for f in files: json.loads(f.read_text())
print(f'PASS - {len(files)} JSON schema/release records')
print('VALIDATION PASSED: Sustainable Catalyst Workspace v0.51.0 — Grounded Research Assistant II')
