from pathlib import Path
import subprocess,sys
from release_lineage import current_release,load_manifest,load_registry,validate_current_release_lineage
R=Path(__file__).resolve().parents[1];CUR=current_release(R);P=R/'wordpress/sustainable-catalyst-workspace';MAN=load_manifest(R,'1.9.0');OLD=load_manifest(R,'1.8.0');REG=load_registry(R,'1.9.0');MAIN=(P/'sustainable-catalyst-workspace.php').read_text();PHP=(P/'includes/class-sc-workspace.php').read_text();H=(P/'includes/class-sc-workspace-institutional-audit-studio.php').read_text();J=(P/'assets/js/sc-workspace-institutional-audit-studio-v1.js').read_text();DEP=(P/'includes/class-sc-workspace-deployment.php').read_text();PROD=(P/'includes/class-sc-workspace-production-certification.php').read_text();REGPHP=(P/'includes/class-sc-workspace-registry.php').read_text()
def check(x,l):
 if not x: raise SystemExit('FAIL - v1.9.0 institutional audit studio gate: '+l)
lineage=validate_current_release_lineage(R);check(lineage['ok'],'current release lineage: '+('; '.join(lineage['errors']) if lineage['errors'] else 'unknown'))
check((MAN['version'],MAN['previous_version'],MAN['release_name'])==('1.9.0','1.8.0','Institutional Governance, Provenance & Audit Studio'),'release identity')
check((REG['public_version'],REG['previous_version'],REG['release_name'])==('1.9.0','1.8.0','Institutional Governance, Provenance & Audit Studio'),'registry identity')
for k in ['storage_schema_version','project_schema','export_schema','object_schema','research_schema']:check(MAN[k]==OLD[k],'frozen '+k)
check(set(MAN['rest_routes'])-set(OLD['rest_routes'])=={'/wp-json/sc-workspace/v1/institutional-audit-studio-contract'},'only institutional audit route added')
g=MAN['institutional_audit_studio'];check(g['schema']=='sc-workspace-institutional-audit-studio/1.0','contract schema');check(len(g['evidence_families'])==10,'evidence families')
for k in ['explicit_scope','derived_from_authoritative_ledgers','canonical_records_remain_owned_by_source_subsystems','evidence_lineage_visible','decision_lineage_visible','relationship_explanations_visible','immutable_evidence_fingerprint','reproducible_audit_package_export','attestation_user_supplied','institutional_handoff_linked','review_room_evidence_linked']:check(g.get(k) is True,k)
for k in ['audit_package_copies_canonical_bodies','attestation_identity_inferred','regulatory_certification_claimed','compliance_score','automatic_compliance_inference','automatic_external_submission','automatic_canonical_mutation','automatic_ai','behavioral_telemetry','query_telemetry','schema_migration_required']:check(g.get(k) is False,k)
check(f'Version: {CUR.version}' in MAIN and f"SC_WORKSPACE_VERSION', '{CUR.version}'" in MAIN and 'class-sc-workspace-institutional-audit-studio.php' in MAIN,'WordPress bootstrap')
check("'/institutional-audit-studio-contract'" in PHP and 'institutional_audit_studio_contract' in PHP and 'sc-workspace-institutional-audit-studio-v1' in PHP,'REST/enqueue');check('data-release-stage="institutional-scale-hardening"' in PHP and CUR.script_name in PHP and CUR.style_name in PHP,'stage/assets')
for t in ['sc-workspace-institutional-audit-studio/1.0','sc-workspace-audit-dossier/1.0','sc-workspace-audit-attestation/1.0','regulatoryCertificationClaimed']:check(t in H or t in J,'contract/helper '+t)
for t in ['Institutional Audit Studio','Build audit dossier','Record attestation','Auditability, not automatic compliance']:check(t in PHP,'visible UI '+t)
check(f"PREVIOUS_RELEASE = '{CUR.previous_version}'" in DEP and f"ROLLBACK_RELEASE = '{CUR.previous_version}'" in DEP and CUR.script_name in DEP and 'class-sc-workspace-institutional-audit-studio.php' in DEP,'deployment predecessor/preflight');check(f"PREVIOUS_RELEASE = '{CUR.previous_version}'" in PROD and f"ROLLBACK_RELEASE = '{CUR.previous_version}'" in PROD,'production predecessor');check('LEGACY_PENDING_KEY_V190' in REGPHP and 'LEGACY_PENDING_KEY_V180' in REGPHP,'registry retry lineage')
for f in ['docs/INSTITUTIONAL_GOVERNANCE_PROVENANCE_AUDIT_STUDIO_V190.md','RELEASE_NOTES_1.9.0.md','schemas/sc-workspace-audit-dossier-v1.schema.json','schemas/sc-workspace-audit-provenance-record-v1.schema.json','schemas/sc-workspace-audit-attestation-v1.schema.json','schemas/sc-workspace-institutional-audit-package-v1.schema.json','tests/test_institutional_audit_studio_contract.py','tests/test_institutional_audit_studio_runtime.js','tests/test_institutional_audit_studio_runtime.php']:check((R/f).exists(),f)
subprocess.run([sys.executable,str(R/'scripts/validate_shared_review_rooms_controlled_collaboration.py')],check=True,cwd=R)
print('PASS - v1.9.0 Institutional Governance, Provenance & Audit Studio source gate')
