from pathlib import Path
import subprocess,sys
from release_lineage import current_release,load_manifest,load_registry,validate_current_release_lineage
R=Path(__file__).resolve().parents[1];CUR=current_release(R);P=R/'wordpress/sustainable-catalyst-workspace';MAN=load_manifest(R,'1.8.0');OLD=load_manifest(R,'1.7.0');REG=load_registry(R,'1.8.0');MAIN=(P/'sustainable-catalyst-workspace.php').read_text();PHP=(P/'includes/class-sc-workspace.php').read_text();H=(P/'includes/class-sc-workspace-review-rooms.php').read_text();J=(P/'assets/js/sc-workspace-review-rooms-v1.js').read_text();UI=(P/'assets/js/sc-workspace-review-rooms-ui-v1.js').read_text();APP=CUR.script_path.read_text();DEP=(P/'includes/class-sc-workspace-deployment.php').read_text();PROD=(P/'includes/class-sc-workspace-production-certification.php').read_text();REGPHP=(P/'includes/class-sc-workspace-registry.php').read_text()
def check(x,l):
 if not x: raise SystemExit('FAIL - v1.8.0 shared review rooms gate: '+l)
lineage=validate_current_release_lineage(R);check(lineage['ok'],'current release lineage: '+('; '.join(lineage['errors']) if lineage['errors'] else 'unknown'))
check((MAN['version'],MAN['previous_version'],MAN['release_name'])==('1.8.0','1.7.0','Shared Review Rooms & Controlled Collaboration'),'release identity')
check((REG['public_version'],REG['previous_version'],REG['release_name'])==('1.8.0','1.7.0','Shared Review Rooms & Controlled Collaboration'),'registry identity')
for k in ['storage_schema_version','project_schema','export_schema','object_schema','research_schema']:check(MAN[k]==OLD[k],'frozen '+k)
check(set(MAN['rest_routes'])-set(OLD['rest_routes'])=={'/wp-json/sc-workspace/v1/shared-review-rooms-contract'},'only shared review rooms route added')
g=MAN['shared_review_rooms'];check(g['schema']=='sc-workspace-shared-review-rooms/1.0','contract schema');check(g['room_schema']=='sc-workspace-shared-review-room/1.0','room schema');check(g['snapshot_schema']=='sc-workspace-review-room-snapshot/1.0','snapshot schema');check(g['room_states']==['draft','open','in-review','changes-requested','approved','closed'],'room states');check(g['roles']==['owner','editor','reviewer','observer'],'roles')
for k in ['scoped_permissions','permissions_are_local_governance_records','explicit_invitations','immutable_review_snapshots','snapshot_scope_uses_explicit_object_ids','snapshot_fingerprint_required','review_state_transitions_audited','owner_closes_room','portable_room_export','portable_room_import_stages_before_commit','canonical_project_owner_retained']:check(g.get(k) is True,k)
for k in ['server_acl_created','automatic_invitation_delivery','invitation_creates_account','proposal_acceptance_applies_canonical_change','automatic_canonical_mutation','live_coediting','shared_cloud_tenant','team_cloud_storage','background_sync','automatic_external_send','automatic_ai','behavioral_telemetry','query_telemetry','schema_migration_required']:check(g.get(k) is False,k)
check(f'Version: {CUR.version}' in MAIN and f"SC_WORKSPACE_VERSION', '{CUR.version}'" in MAIN and 'class-sc-workspace-review-rooms.php' in MAIN,'WordPress bootstrap')
check("'/shared-review-rooms-contract'" in PHP and 'shared_review_rooms_contract' in PHP and 'sc-workspace-review-rooms-v1' in PHP and 'sc-workspace-review-rooms-ui-v1' in PHP,'REST/enqueue');check('data-release-stage="institutional-scale-hardening"' in PHP and CUR.script_name in PHP and CUR.style_name in PHP,'stage/assets')
for t in ['sc-workspace-shared-review-rooms/1.0','sc-workspace-review-room-snapshot/1.0','freezeSnapshot','exportRoom','serverAclCreated:false']:check(t in H or t in J,'contract/helper '+t)
for t in ['Shared Review Rooms','Freeze review snapshot','Record invitation','Controlled review, not a shared tenant']:check(t in PHP,'visible UI '+t)
check(f"PREVIOUS_RELEASE = '{CUR.previous_version}'" in DEP and f"ROLLBACK_RELEASE = '{CUR.previous_version}'" in DEP and CUR.script_name in DEP and 'class-sc-workspace-review-rooms.php' in DEP,'deployment predecessor/preflight');check(f"PREVIOUS_RELEASE = '{CUR.previous_version}'" in PROD and f"ROLLBACK_RELEASE = '{CUR.previous_version}'" in PROD,'production predecessor');check('LEGACY_PENDING_KEY_V180' in REGPHP and 'LEGACY_PENDING_KEY_V170' in REGPHP,'registry retry lineage')
for f in ['docs/SHARED_REVIEW_ROOMS_CONTROLLED_COLLABORATION_V180.md','RELEASE_NOTES_1.8.0.md','schemas/sc-workspace-shared-review-room-v1.schema.json','schemas/sc-workspace-review-room-invitation-v1.schema.json','schemas/sc-workspace-review-room-snapshot-v1.schema.json','schemas/sc-workspace-review-room-event-v1.schema.json','schemas/sc-workspace-review-room-export-v1.schema.json','tests/test_shared_review_rooms_contract.py','tests/test_shared_review_rooms_runtime.js','tests/test_shared_review_rooms_runtime.php']:check((R/f).exists(),f)
subprocess.run([sys.executable,str(R/'scripts/validate_cross_device_continuity_productionization.py')],check=True,cwd=R)
print('PASS - v1.8.0 Shared Review Rooms & Controlled Collaboration source gate')
