from pathlib import Path
import subprocess,sys
from release_lineage import current_release,load_manifest,load_registry,validate_current_release_lineage
R=Path(__file__).resolve().parents[1];CUR=current_release(R);P=R/'wordpress/sustainable-catalyst-workspace';MAN=load_manifest(R,'1.11.0');OLD=load_manifest(R,'1.10.0');REG=load_registry(R,'1.11.0');MAIN=(P/'sustainable-catalyst-workspace.php').read_text();PHP=(P/'includes/class-sc-workspace.php').read_text();H=(P/'includes/class-sc-workspace-developer-api.php').read_text();SDK=(P/'assets/js/sc-workspace-developer-sdk-v1.js').read_text();UI=(P/'assets/js/sc-workspace-developer-api-ui-v1.js').read_text();DEP=(P/'includes/class-sc-workspace-deployment.php').read_text();PROD=(P/'includes/class-sc-workspace-production-certification.php').read_text();REGPHP=(P/'includes/class-sc-workspace-registry.php').read_text()
def check(x,l):
 if not x: raise SystemExit('FAIL - v1.11.0 Developer API/SDK gate: '+l)
lineage=validate_current_release_lineage(R,'1.11.0','1.10.0');check(lineage['ok'],'current release lineage: '+('; '.join(lineage['errors']) if lineage['errors'] else 'unknown'))
check((MAN['version'],MAN['previous_version'],MAN['release_name'])==('1.11.0','1.10.0','Developer API, SDK & Extension Contracts'),'release identity')
check((REG['public_version'],REG['previous_version'],REG['release_name'])==('1.11.0','1.10.0','Developer API, SDK & Extension Contracts'),'registry identity')
for k in ['storage_schema_version','project_schema','export_schema','object_schema','research_schema']:check(MAN[k]==OLD[k],'frozen '+k)
check(set(MAN['rest_routes'])-set(OLD['rest_routes'])=={'/wp-json/sc-workspace/v1/developer-api-contract'},'only Developer API route added')
g=MAN['developer_api'];check(g['schema']=='sc-workspace-developer-api/1.0','developer API schema');check(g['sdk_schema']=='sc-workspace-sdk-contract/1.0','SDK schema');check(g['extension_manifest_schema']=='sc-workspace-extension-manifest/1.0','extension manifest schema');check(g['capability_grant_schema']=='sc-workspace-extension-capability-grant/1.0','grant schema');check(g['event_envelope_schema']=='sc-workspace-extension-event-envelope/1.0','event envelope schema');check(g['api_namespace']=='sc-workspace/v1','API namespace');check(g['default_capability_mode']=='read-only-descriptive','default capability mode');check(len(g['stable_contract_families'])==10,'ten stable contract families');check(len(g['capabilities'])==10,'ten capabilities')
for k in ['extension_manifest_required','capability_grant_required','grants_are_explicit','grants_are_portable_records','browser_local_sdk','rollback_schema_compatible']:check(g.get(k) is True,k)
for k in ['grant_is_authentication_credential','mutating_rest_endpoints','arbitrary_code_execution','dynamic_plugin_installation','remote_extension_loading','automatic_network_request','automatic_canonical_mutation','automatic_ai','behavioral_telemetry','query_telemetry','secrets_in_manifest','tokens_in_urls','schema_migration_required']:check(g.get(k) is False,k)
check('Version: 1.11.0' in MAIN and "SC_WORKSPACE_VERSION', '1.11.0'" in MAIN and 'class-sc-workspace-developer-api.php' in MAIN,'WordPress bootstrap')
check("'/developer-api-contract'" in PHP and 'developer_api_contract' in PHP and 'sc-workspace-developer-sdk-v1' in PHP and 'sc-workspace-developer-api-ui-v1' in PHP,'REST/enqueue');check('data-release-stage="developer-api"' in PHP and CUR.script_name in PHP and CUR.style_name in PHP,'stage/assets')
for t in ['sc-workspace-developer-api/1.0','sc-workspace-extension-capability-grant/1.0','mutatingRestEndpoints','arbitraryCodeExecution']:check(t in H or t in SDK,'contract/SDK '+t)
for t in ['Developer API &amp; Extensions','Export starter extension manifest','Read-only by default']:check(t in PHP or t in UI,'visible UI '+t)
check("PREVIOUS_RELEASE = '1.10.0'" in DEP and "ROLLBACK_RELEASE = '1.10.0'" in DEP and CUR.script_name in DEP and 'class-sc-workspace-developer-api.php' in DEP and 'sc-workspace-developer-sdk-v1.js' in DEP and 'sc-workspace-developer-api-ui-v1.js' in DEP,'deployment predecessor/preflight');check("PREVIOUS_RELEASE = '1.10.0'" in PROD and "ROLLBACK_RELEASE = '1.10.0'" in PROD,'production predecessor');check("BACKUP_KEY = 'sc_workspace_registry_backup_v1110'" in REGPHP and 'LEGACY_PENDING_KEY_V1100' in REGPHP,'registry retry lineage')
for f in ['docs/DEVELOPER_API_SDK_EXTENSION_CONTRACTS_V1110.md','RELEASE_NOTES_1.11.0.md','schemas/sc-workspace-developer-api-v1.schema.json','schemas/sc-workspace-sdk-contract-v1.schema.json','schemas/sc-workspace-extension-manifest-v1.schema.json','schemas/sc-workspace-extension-capability-grant-v1.schema.json','schemas/sc-workspace-extension-event-envelope-v1.schema.json','tests/test_developer_api_contract.py','tests/test_developer_api_runtime.js','tests/test_developer_api_runtime.php']:check((R/f).exists(),f)
subprocess.run([sys.executable,str(R/'scripts/validate_workspace_automation_research_operations.py')],check=True,cwd=R)
print('PASS - v1.11.0 Developer API, SDK & Extension Contracts source gate')
