from pathlib import Path
import subprocess,sys
from release_lineage import current_release,load_manifest,load_registry,validate_current_release_lineage
R=Path(__file__).resolve().parents[1];CUR=current_release(R);P=R/'wordpress/sustainable-catalyst-workspace';MAN=load_manifest(R,'1.12.0');OLD=load_manifest(R,'1.11.0');REG=load_registry(R,'1.12.0');MAIN=(P/'sustainable-catalyst-workspace.php').read_text();PHP=(P/'includes/class-sc-workspace.php').read_text();H=(P/'includes/class-sc-workspace-institutional-scale-hardening.php').read_text();JS=(P/'assets/js/sc-workspace-institutional-scale-hardening-v1.js').read_text();UI=(P/'assets/js/sc-workspace-institutional-scale-hardening-ui-v1.js').read_text();DEP=(P/'includes/class-sc-workspace-deployment.php').read_text();PROD=(P/'includes/class-sc-workspace-production-certification.php').read_text();REGPHP=(P/'includes/class-sc-workspace-registry.php').read_text()
def check(x,l):
 if not x: raise SystemExit('FAIL - v1.12.0 institutional scale hardening gate: '+l)
lineage=validate_current_release_lineage(R,'1.13.0','1.12.0');check(lineage['ok'],'current release lineage: '+('; '.join(lineage['errors']) if lineage['errors'] else 'unknown'))
check((MAN['version'],MAN['previous_version'],MAN['release_name'])==('1.12.0','1.11.0','Large Workspace & Institutional Scale Hardening'),'release identity');check((REG['public_version'],REG['previous_version'],REG['release_name'])==('1.12.0','1.11.0','Large Workspace & Institutional Scale Hardening'),'registry identity')
for k in ['storage_schema_version','project_schema','export_schema','object_schema','research_schema']:check(MAN[k]==OLD[k],'frozen '+k)
check(set(MAN['rest_routes'])-set(OLD['rest_routes'])=={'/wp-json/sc-workspace/v1/institutional-scale-hardening-contract'},'only scale hardening route added')
g=MAN['institutional_scale_hardening'];check(g['schema']=='sc-workspace-institutional-scale-hardening/1.0','schema');check(g['deterministic_scale_assessment'] and g['bounded_rendering'] and g['chunked_local_indexing'] and g['bounded_graph_expansion'] and g['sharded_institutional_exports'],'scale features');check(g['recovery_first_critical_mode'] and g['operation_journal_required'] and g['last_known_good_required'],'recovery-first controls')
for k in ['local_first','advisory_only','rollback_schema_compatible']:check(g.get(k) is True,k)
for k in ['canonical_mutation','automatic_deletion','automatic_compaction','automatic_archival','automatic_migration','automatic_upload','server_offload','automatic_ai','behavioral_telemetry','query_telemetry','schema_migration_required']:check(g.get(k) is False,k)
check('Version: 1.13.0' in MAIN and "SC_WORKSPACE_VERSION', '1.13.0'" in MAIN and 'class-sc-workspace-institutional-scale-hardening.php' in MAIN,'WordPress bootstrap');check("'/institutional-scale-hardening-contract'" in PHP and 'institutional_scale_hardening_contract' in PHP and 'sc-workspace-institutional-scale-hardening-v1' in PHP and 'sc-workspace-institutional-scale-hardening-ui-v1' in PHP,'REST/enqueue');check('data-release-stage="connected-intelligence"' in PHP and CUR.script_name in PHP and CUR.style_name in PHP,'stage/assets')
for t in ['function deriveMetrics','function assess','function plan','function checkpoint','function exportShardManifest','automaticDeletion:false','serverOffload:false']:check(t in JS,'runtime '+t)
for t in ['Large Workspace &amp; Institutional Scale Hardening','Assess scale envelope','Export scale report']:check(t in PHP or t in UI,'visible UI '+t)
check("PREVIOUS_RELEASE = '1.12.0'" in DEP and "ROLLBACK_RELEASE = '1.12.0'" in DEP and CUR.script_name in DEP and 'class-sc-workspace-institutional-scale-hardening.php' in DEP,'deployment predecessor/preflight');check("PREVIOUS_RELEASE = '1.12.0'" in PROD and "ROLLBACK_RELEASE = '1.12.0'" in PROD,'production predecessor');check("BACKUP_KEY = 'sc_workspace_registry_backup_v1130'" in REGPHP and 'LEGACY_PENDING_KEY_V1120' in REGPHP,'registry retry lineage')
for f in ['docs/INSTITUTIONAL_SCALE_HARDENING_V1120.md','RELEASE_NOTES_1.12.0.md','schemas/sc-workspace-institutional-scale-hardening-v1.schema.json','schemas/sc-workspace-institutional-scale-envelope-v1.schema.json','schemas/sc-workspace-institutional-scale-plan-v1.schema.json','schemas/sc-workspace-scale-recovery-checkpoint-v1.schema.json','schemas/sc-workspace-institutional-export-shard-manifest-v1.schema.json','tests/test_institutional_scale_hardening_contract.py','tests/test_institutional_scale_hardening_runtime.js','tests/test_institutional_scale_hardening_runtime.php']:check((R/f).exists(),f)
subprocess.run([sys.executable,str(R/'scripts/validate_developer_api_sdk_extension_contracts.py')],check=True,cwd=R)
print('PASS - v1.12.0 Large Workspace & Institutional Scale Hardening source gate')
