from pathlib import Path
from release_lineage import current_release, load_manifest, validate_current_release_lineage
R=Path(__file__).resolve().parents[1]; CUR=current_release(R)
HIST=load_manifest(R,'0.81.0'); CURRENT=load_manifest(R,CUR.version)
P=R/'wordpress/sustainable-catalyst-workspace'; MAIN=CUR.plugin_main.read_text(); PHP=(P/'includes/class-sc-workspace.php').read_text(); REGPHP=(P/'includes/class-sc-workspace-registry.php').read_text(); DEP=(P/'includes/class-sc-workspace-deployment.php').read_text(); NAV=(P/'assets/js/sc-workspace-research-navigation-v1.js').read_text(); EXP=(P/'assets/js/sc-workspace-experience-v1.js').read_text(); RUNTIME=(P/'assets/js/sc-workspace-wordpress-deployment-hardening-v1.js').read_text(); UI=(P/'assets/js/sc-workspace-wordpress-deployment-hardening-ui-v1.js').read_text()
def check(x,l):
    if not x: raise SystemExit('FAIL - WordPress & Deployment Hardening source gate: '+l)
check(validate_current_release_lineage(R)['ok'],'current release lineage')
check(HIST['version']=='0.81.0' and HIST['previous_version']=='0.80.0','historical lineage')
for k in ['storage_schema_version','project_schema','export_schema','object_schema','research_schema']: check(CURRENT[k]==HIST[k],'frozen '+k)
check(CURRENT['object_types']==HIST['object_types'],'frozen object types')
check('sc_workspace_bootstrap_failure' in MAIN and 'is_readable' in MAIN and 'return;' in MAIN,'safe bootstrap guard')
check('SC_Workspace_Deployment_Hardening::activate()' in MAIN and 'activation_preflight' in DEP,'activation preflight')
check('MAX_HISTORY = 12' in DEP and 'sc_workspace_deployment_history_v1' in DEP,'bounded deployment history')
rollback=(CURRENT.get('ga_field_stabilization') or CURRENT.get('general_availability') or CURRENT.get('production_ga_readiness') or CURRENT.get('production_release_signoff') or CURRENT.get('production_certification_installer_validation_lineage_repair') or CURRENT.get('production_smoke_cache_rollback_certification') or {}).get('rollback_release',CUR.previous_version)
check(f"PREVIOUS_RELEASE = '{CUR.previous_version}'" in DEP,'current semantic predecessor'); check(f"ROLLBACK_RELEASE = '{rollback}'" in DEP,'current declared rollback')
check(CUR.script_name in DEP and CUR.style_name in DEP,'deployment current assets')
check(CUR.asset_handle in PHP and CUR.script_name in PHP and CUR.style_name in PHP,'current versioned assets')
check("'/deployment-hardening-contract'" in PHP and 'deployment_hardening_contract' in PHP,'deployment REST contract')
for route in ['final-audit','beta-closure','release-candidate','deployment','production-certification','recovery-drills']: check("'"+route+"'" in NAV,'Review navigation '+route)
check("id:'deployment'" in EXP,'deployment experience command')
check(f"const RELEASE_VERSION='{CUR.version}'" in RUNTIME and f"const PREVIOUS_RELEASE='{CUR.previous_version}'" in RUNTIME,'deployment runtime identity')
check(CUR.script_name in RUNTIME and CUR.style_name in RUNTIME,'runtime expected current assets')
check('projectContentIncluded:false' in RUNTIME and 'rawUserAgentIncluded:false' in RUNTIME and 'serverFilesystemPathsIncluded:false' in RUNTIME,'privacy minimized')
check('data-scw-wordpress-deployment-hardening' in UI,'deployment UI target')
hard=HIST['wordpress_deployment_hardening']
for k in ['release_candidate','feature_freeze','safe_bootstrap_guard','activation_preflight','bounded_deployment_history','server_package_integrity_check','mixed_version_browser_detection','versioned_asset_filenames','version_query_required','registry_pending_detection','rollback_schema_compatible','rollback_artifact_required']: check(hard.get(k) is True,k)
for k in ['automatic_cache_purge','automatic_rollback','automatic_project_migration','project_data_inspected','project_data_mutated','new_product_subsystem','behavioral_telemetry','schema_migration_required']: check(hard.get(k) is False,k)
print(f'PASS - inherited v0.81 WordPress & Deployment Hardening source gate under current v{CUR.version}')
