from pathlib import Path
import subprocess,sys
from release_lineage import current_release,load_manifest,load_registry,validate_current_release_lineage
R=Path(__file__).resolve().parents[1];CUR=current_release(R);P=R/'wordpress/sustainable-catalyst-workspace';MAN=load_manifest(R,'1.7.0');OLD=load_manifest(R,'1.6.0');REG=load_registry(R,'1.7.0');MAIN=(P/'sustainable-catalyst-workspace.php').read_text();PHP=(P/'includes/class-sc-workspace.php').read_text();H=(P/'includes/class-sc-workspace-cross-device-production.php').read_text();J=(P/'assets/js/sc-workspace-cross-device-production-v1.js').read_text();APP=CUR.script_path.read_text();DEP=(P/'includes/class-sc-workspace-deployment.php').read_text();PROD=(P/'includes/class-sc-workspace-production-certification.php').read_text();REGPHP=(P/'includes/class-sc-workspace-registry.php').read_text()
def check(x,l):
 if not x: raise SystemExit('FAIL - v1.7.0 cross-device production gate: '+l)
lineage=validate_current_release_lineage(R);check(lineage['ok'],'current release lineage: '+('; '.join(lineage['errors']) if lineage['errors'] else 'unknown'))
check((MAN['version'],MAN['previous_version'],MAN['release_name'])==('1.7.0','1.6.0','Cross-Device Continuity & Account Sync Productionization'),'release identity')
check((REG['public_version'],REG['previous_version'],REG['release_name'])==('1.7.0','1.6.0','Cross-Device Continuity & Account Sync Productionization'),'registry identity')
for k in ['storage_schema_version','project_schema','export_schema','object_schema','research_schema']:check(MAN[k]==OLD[k],'frozen '+k)
check(set(MAN['rest_routes'])-set(OLD['rest_routes'])=={'/wp-json/sc-workspace/v1/cross-device-production-contract'},'only production continuity route added')
g=MAN['cross_device_production'];check(g['schema']=='sc-workspace-cross-device-production/1.0','contract schema');check(g['plan_schema']=='sc-workspace-cross-device-sync-plan/1.0','plan schema');check(g['receipt_schema']=='sc-workspace-cross-device-sync-receipt/1.0','receipt schema');check(len(g['plan_actions'])==8,'plan action count')
for k in ['guest_workspace_first_class','account_required_for_sync','explicit_project_enrollment','manual_sync_now','local_project_canonical_on_device','cloud_head_is_continuity_copy','deterministic_continuity_plan','revision_precondition_required','conflict_preserves_both_sides','safe_pull_requires_unchanged_local_baseline','sync_operation_journal','idempotent_operation_retry','interrupted_operation_reconciliation','production_receipt_export']:check(g.get(k) is True,k)
for k in ['automatic_enrollment_on_sign_in','background_sync','automatic_upload','silent_last_write_wins','receipt_contains_project_content','receipt_contains_query_text','receipt_contains_source_urls','receipt_contains_device_identifier','device_fingerprinting','account_profile_in_receipt','team_sync','institutional_sync','automatic_ai','behavioral_telemetry','query_telemetry','schema_migration_required']:check(g.get(k) is False,k)
check(f'Version: {CUR.version}' in MAIN and f"SC_WORKSPACE_VERSION', '{CUR.version}'" in MAIN and 'class-sc-workspace-cross-device-production.php' in MAIN,'WordPress bootstrap')
check("'/cross-device-production-contract'" in PHP and 'cross_device_production_contract' in PHP and 'sc-workspace-cross-device-production-v1' in PHP,'REST/enqueue');check('data-release-stage="connected-intelligence"' in PHP and CUR.script_name in PHP and CUR.style_name in PHP,'stage/assets')
for t in ['sc-workspace-cross-device-production/1.0','sc-workspace-cross-device-sync-plan/1.0','sc-workspace-cross-device-sync-receipt/1.0','conflictPreservesBothSides']:check(t in H or t in J,'contract/helper '+t)
for t in ['Production continuity plan','Export continuity receipt','Local-first continuity, not cloud-first storage']:check(t in PHP,'visible UI '+t)
check(f"PREVIOUS_RELEASE = '{CUR.previous_version}'" in DEP and f"ROLLBACK_RELEASE = '{CUR.previous_version}'" in DEP and CUR.script_name in DEP and 'class-sc-workspace-cross-device-production.php' in DEP,'deployment predecessor/preflight');check(f"PREVIOUS_RELEASE = '{CUR.previous_version}'" in PROD and f"ROLLBACK_RELEASE = '{CUR.previous_version}'" in PROD,'production predecessor');check('LEGACY_PENDING_KEY_V170' in REGPHP and 'LEGACY_PENDING_KEY_V160' in REGPHP,'registry retry lineage')
for f in ['docs/CROSS_DEVICE_CONTINUITY_ACCOUNT_SYNC_PRODUCTIONIZATION_V170.md','RELEASE_NOTES_1.7.0.md','schemas/sc-workspace-cross-device-sync-plan-v1.schema.json','schemas/sc-workspace-cross-device-sync-receipt-v1.schema.json','tests/test_cross_device_production_contract.py','tests/test_cross_device_production_runtime.js','tests/test_cross_device_production_runtime.php']:check((R/f).exists(),f)
subprocess.run([sys.executable,str(R/'scripts/validate_workbench_decision_roundtrip.py')],check=True,cwd=R)
print('PASS - v1.7.0 Cross-Device Continuity & Account Sync Productionization source gate')
