from pathlib import Path
import subprocess,sys
from release_lineage import current_release,load_manifest,load_registry,validate_current_release_lineage
R=Path(__file__).resolve().parents[1];CUR=current_release(R);P=R/'wordpress/sustainable-catalyst-workspace';MAN=load_manifest(R,'1.10.0');OLD=load_manifest(R,'1.9.0');REG=load_registry(R,'1.10.0');MAIN=(P/'sustainable-catalyst-workspace.php').read_text();PHP=(P/'includes/class-sc-workspace.php').read_text();H=(P/'includes/class-sc-workspace-research-operations.php').read_text();J=(P/'assets/js/sc-workspace-research-operations-v1.js').read_text();DEP=(P/'includes/class-sc-workspace-deployment.php').read_text();PROD=(P/'includes/class-sc-workspace-production-certification.php').read_text();REGPHP=(P/'includes/class-sc-workspace-registry.php').read_text()
def check(x,l):
 if not x: raise SystemExit('FAIL - v1.10.0 Research Operations gate: '+l)
lineage=validate_current_release_lineage(R);check(lineage['ok'],'current release lineage: '+('; '.join(lineage['errors']) if lineage['errors'] else 'unknown'))
check((MAN['version'],MAN['previous_version'],MAN['release_name'])==('1.10.0','1.9.0','Workspace Automation & Research Operations'),'release identity');check((REG['public_version'],REG['previous_version'],REG['release_name'])==('1.10.0','1.9.0','Workspace Automation & Research Operations'),'registry identity')
for k in ['storage_schema_version','project_schema','export_schema','object_schema','research_schema']:check(MAN[k]==OLD[k],'frozen '+k)
check(set(MAN['rest_routes'])-set(OLD['rest_routes'])=={'/wp-json/sc-workspace/v1/research-operations-contract'},'only Research Operations route added');g=MAN['research_operations'];check(len(g['operation_types'])==8,'eight operation types');check(g['receipt_integrity_algorithm']=='SHA-256','SHA-256 receipts')
for k in ['legacy_research_automation_retained','legacy_routine_import_supported','deterministic_due_planning','blocked_targets_visible','explicit_run_queue','manual_execution_only','schedule_is_declaration','external_freshness_requires_user_action','review_required','receipts_metadata_only','portable_operations_export']:check(g.get(k) is True,k)
for k in ['legacy_routine_auto_migration','background_execution','automatic_network_request','automatic_canonical_mutation','automatic_task_creation','automatic_ai','receipts_contain_project_content','receipts_contain_query_text','receipts_contain_source_urls','behavioral_telemetry','query_telemetry','schema_migration_required']:check(g.get(k) is False,k)
check(f'Version: {CUR.version}' in MAIN and f"SC_WORKSPACE_VERSION', '{CUR.version}'" in MAIN and 'class-sc-workspace-research-operations.php' in MAIN,'WordPress bootstrap');check("'/research-operations-contract'" in PHP and 'research_operations_contract' in PHP and 'sc-workspace-research-operations-v1' in PHP and 'sc-workspace-research-operations-ui-v1' in PHP,'REST/enqueue');check('data-release-stage="institutional-scale-hardening"' in PHP and CUR.script_name in PHP and CUR.style_name in PHP,'current stage/assets preserve historical Research Operations')
for tok in ['sc-workspace-research-operations/1.0','sc-workspace-research-operation-receipt/1.0','manualExecutionOnly','receiptsMetadataOnly']:check(tok in H or tok in J,'contract/helper '+tok)
for tok in ['Research Operations','Run due operations','Import legacy routines','Schedules are declarations, not a daemon']:check(tok in PHP,'visible UI '+tok)
check(f"PREVIOUS_RELEASE = '{CUR.previous_version}'" in DEP and f"ROLLBACK_RELEASE = '{CUR.previous_version}'" in DEP and CUR.script_name in DEP and 'class-sc-workspace-research-operations.php' in DEP,'deployment predecessor/preflight');check(f"PREVIOUS_RELEASE = '{CUR.previous_version}'" in PROD and f"ROLLBACK_RELEASE = '{CUR.previous_version}'" in PROD,'production predecessor');check("BACKUP_KEY = 'sc_workspace_registry_backup_v1120'" in REGPHP and 'LEGACY_PENDING_KEY_V1110' in REGPHP and 'LEGACY_PENDING_KEY_V1100' in REGPHP and 'LEGACY_PENDING_KEY_V190' in REGPHP,'registry retry lineage')
for f in ['docs/WORKSPACE_AUTOMATION_RESEARCH_OPERATIONS_V1100.md','RELEASE_NOTES_1.10.0.md','schemas/sc-workspace-research-operation-v1.schema.json','schemas/sc-workspace-research-operation-run-v1.schema.json','schemas/sc-workspace-research-operation-receipt-v1.schema.json','schemas/sc-workspace-research-operations-export-v1.schema.json','tests/test_research_operations_contract.py','tests/test_research_operations_runtime.js','tests/test_research_operations_runtime.php']:check((R/f).exists(),f)
subprocess.run([sys.executable,str(R/'scripts/validate_institutional_governance_provenance_audit_studio.py')],check=True,cwd=R)
print('PASS - v1.10.0 Workspace Automation & Research Operations source gate')
