from pathlib import Path
import subprocess,sys
from release_lineage import current_release,load_manifest,load_registry
R=Path(__file__).resolve().parents[1];CUR=current_release(R);P=R/'wordpress/sustainable-catalyst-workspace';MAN=load_manifest(R,'1.6.0');OLD=load_manifest(R,'1.5.0');REG=load_registry(R,'1.6.0');MAIN=(P/'sustainable-catalyst-workspace.php').read_text();PHP=(P/'includes/class-sc-workspace.php').read_text();H=(P/'includes/class-sc-workspace-workbench-decision-roundtrip.php').read_text();J=(P/'assets/js/sc-workspace-workbench-decision-roundtrip-v1.js').read_text();APP=CUR.script_path.read_text();DEP=(P/'includes/class-sc-workspace-deployment.php').read_text();PROD=(P/'includes/class-sc-workspace-production-certification.php').read_text();REGPHP=(P/'includes/class-sc-workspace-registry.php').read_text()
def check(x,l):
 if not x: raise SystemExit('FAIL - v1.6.0 Workbench/Decision Studio round-trip gate: '+l)
check((MAN['version'],MAN['previous_version'],MAN['release_name'])==('1.6.0','1.5.0','Workbench & Decision Studio Round-Trip Workflows'),'release identity')
check((REG['public_version'],REG['previous_version'],REG['release_name'])==('1.6.0','1.5.0','Workbench & Decision Studio Round-Trip Workflows'),'registry identity')
for k in ['storage_schema_version','project_schema','export_schema','object_schema','research_schema']:check(MAN[k]==OLD[k],'frozen '+k)
check(set(MAN['rest_routes'])-set(OLD['rest_routes'])=={'/wp-json/sc-workspace/v1/workbench-decision-roundtrip-contract'},'only round-trip route added')
g=MAN['tool_roundtrip_integration'];check(g['schema']=='sc-workspace-workbench-decision-roundtrip/1.0','contract schema');check(g['canonical_workbench_route']=='/lab/workbench/' and g['canonical_decision_studio_route']=='/lab/decision-studio/','canonical routes');check(len(g['workbench_workflows'])==6 and len(g['decision_studio_workflows'])==6,'workflow counts');check(len(g['workbench_return_families'])==6 and len(g['decision_studio_return_families'])==6,'return families')
for k in ['explicit_context_selection','portable_context_packages','round_trip_handoff_identity_required','project_and_handoff_match_required','destination_match_required','source_object_ids_preserved','provenance_preserved','method_parameters_preserved','constraints_assumptions_preserved','scenario_metadata_preserved','explicit_return_import_required','explicit_workspace_materialization_required','traceability_edges_from_selected_context']:check(g.get(k) is True,k)
for k in ['outbound_url_carries_content','specialized_execution_automatic','automatic_context_upload','automatic_return_commit','automatic_ai','behavioral_telemetry','query_telemetry','canonical_tool_records_mutated','schema_migration_required']:check(g.get(k) is False,k)
check('Version: 1.7.0' in MAIN and "SC_WORKSPACE_VERSION', '1.7.0'" in MAIN and 'class-sc-workspace-workbench-decision-roundtrip.php' in MAIN,'historical helper preserved/current runtime advanced')
check("'/workbench-decision-roundtrip-contract'" in PHP and 'workbench_decision_roundtrip_contract' in PHP and 'sc-workspace-workbench-decision-roundtrip-v1' in PHP,'REST/enqueue preserved');check(CUR.script_name in PHP and CUR.style_name in PHP,'current assets')
for t in ['sc-workspace-workbench-decision-roundtrip/1.0','sc-workspace-workbench-context/1.0','sc-workspace-decision-studio-return/1.0','destinationMatchRequired']:check(t in H,'PHP contract '+t)
for t in ['buildContextPackage','normalizeReturn','toWorkspaceReturnPacket','returnTemplate','roundtrip-return','automaticReturnCommit:false']:check(t in J,'JS bridge '+t)
for t in ['WORKBENCH / DECISION STUDIO ROUND TRIP','Open tool with IDs','Export context package','Import returned work','Explicit Workbench round trip','Explicit Decision Studio round trip']:check(t in (PHP+APP),'visible/runtime '+t)
check('class-sc-workspace-workbench-decision-roundtrip.php' in DEP,'historical deployment preflight preserved')
for f in ['docs/WORKBENCH_DECISION_STUDIO_ROUNDTRIP_V160.md','RELEASE_NOTES_1.6.0.md','schemas/sc-workspace-workbench-context-v1.schema.json','schemas/sc-workspace-workbench-return-v1.schema.json','schemas/sc-workspace-decision-studio-context-v1.schema.json','schemas/sc-workspace-decision-studio-return-v1.schema.json','tests/test_workbench_decision_roundtrip_contract.py','tests/test_workbench_decision_roundtrip_runtime.js','tests/test_workbench_decision_roundtrip_runtime.php']:check((R/f).exists(),f)
subprocess.run([sys.executable,str(R/'scripts/validate_lab_scientific_workspace_integration.py')],check=True,cwd=R)
print('PASS - inherited v1.6.0 Workbench & Decision Studio Round-Trip Workflows source gate under current v'+CUR.version)
