#!/usr/bin/env python3
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[1];P=ROOT/'wordpress/sustainable-catalyst-workspace'
def check(ok,msg):
 if not ok: print('FAIL - '+msg);sys.exit(1)
 print('PASS - '+msg)
main=(P/'sustainable-catalyst-workspace.php').read_text();php=(P/'includes/class-sc-workspace.php').read_text();js=(P/'assets/js/workspace-v0.14.0.js').read_text();css=(P/'assets/css/workspace-v0.14.0.css').read_text();reg=(P/'includes/class-sc-workspace-registry.php').read_text()
check('Version: 0.14.0' in main,'plugin version');check("define('SC_WORKSPACE_VERSION', '0.14.0')" in main,'runtime version');check("'/interoperability-contract'" in php,'interoperability REST contract');check('IMPORT &amp; INTEROPERABILITY' in php,'interoperability UI');check('const STORAGE_VERSION = 15' in js,'storage schema 15');check("const PROJECT_SCHEMA = 'sc-workspace-project/11.0'" in js,'project schema unchanged');check("const INTEROPERABILITY_SCHEMA = 'sc-workspace-interoperability/1.0'" in js,'interoperability schema');check('function migrateV14(raw)' in js,'v0.13 storage migration');check("digest('SHA-256'" in js,'SHA-256 file fingerprint');check("sourceType:'imported'" in js,'imported provenance');check("const finalId=id('scwo')" in js,'collision-safe remap');check('function interchangePackage(project)' in js,'portable interchange export');check('.scw-interoperability{' in css,'interoperability styling');check("home_url('/knowledge-libraries/')" in php,'canonical Knowledge Library route')
m=json.loads((ROOT/'release-manifest-v0.14.0.json').read_text());check(m['version']=='0.14.0','manifest version');check(m['previous_version']=='0.13.0','previous version');check(m['storage_schema_version']==15,'storage schema');check(m['project_schema']=='sc-workspace-project/11.0','project schema');check(m['interoperability_schema']=='sc-workspace-interoperability/1.0','interoperability manifest');check(not m['interoperability']['automatic_overwrite'],'no silent overwrite');check(m['interoperability']['staged_review_required'],'staged review required');check(not m['interoperability']['server_import_pipeline'],'no server import pipeline')
r=json.loads((ROOT/'registry/workspace-product-record-v0.14.0.json').read_text());check(r['public_version']=='0.14.0','registry version');check(r['previous_version']=='0.13.0','registry previous version');json.loads((ROOT/'schemas/sc-workspace-interoperability-v1.schema.json').read_text());check(True,'schema JSON');check('const LEGACY_PENDING_KEY_V0130' in reg,'registry retry lineage')
print('VALIDATION PASSED: Sustainable Catalyst Workspace v0.14.0 — Import & Interoperability')
