#!/usr/bin/env python3
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
MAN=json.loads((ROOT/'release-manifest-v0.59.1.json').read_text())
REG=json.loads((ROOT/'registry/workspace-product-record-v0.59.1.json').read_text())
MAIN=(ROOT/'wordpress/sustainable-catalyst-workspace/sustainable-catalyst-workspace.php').read_text()
PHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace.php').read_text()
REGPHP=(ROOT/'wordpress/sustainable-catalyst-workspace/includes/class-sc-workspace-registry.php').read_text()
SHELL=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/sc-workspace-focused-shell-v1.js').read_text()
APP=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/js/workspace-v0.59.1.js').read_text()
CSS=(ROOT/'wordpress/sustainable-catalyst-workspace/assets/css/workspace-v0.59.1.css').read_text()
def check(ok,label):
 if not ok: raise SystemExit('FAIL - '+label)
 print('PASS - '+label)
check('Version: 0.59.1' in MAIN,'plugin version')
check((MAN['version'],MAN['previous_version'],MAN['release_name'])==('0.59.1','0.59.0','Focused Application Shell & Route Isolation'),'release lineage')
check(MAN['storage_schema_version']==35 and MAN['project_schema']=='sc-workspace-project/20.0' and not MAN['focused_application_shell']['schema_migration'],'schema stable')
check('data-scw-focused-shell="1"' in PHP and 'sc-workspace-focused-shell-v1.js' in PHP,'focused shell integration')
check('[data-scw-workspace-section][hidden]' in CSS and 'display:none!important' in CSS,'inactive route force-hide')
check('data-scw-research-tool-nav' in PHP and all(f'data-scw-research-surface="{x}"' in PHP for x in MAN['focused_application_shell']['research_surfaces']),'research tool navigation')
check(all(f'data-scw-research-surface-panel="{x}"' in PHP for x in MAN['focused_application_shell']['research_surfaces']),'research panels isolated')
check(MAN['focused_application_shell']['one_research_surface_visible_at_a_time'] and 'visibilityPlan' in SHELL,'single research surface contract')
check(MAN['focused_application_shell']['selected_research_context_preserved'] and not MAN['focused_application_shell']['canonical_mutation'],'presentation-only boundary')
check("BACKUP_KEY = 'sc_workspace_registry_backup_v0591'" in REGPHP and 'LEGACY_PENDING_KEY_V0590' in REGPHP,'registry lineage')
check(REG['public_version']=='0.59.1' and REG['previous_version']=='0.59.0' and REG['installed_version']=='0.59.1','registry record')
check('border-top:4px solid #000' in CSS and MAN['focused_application_shell']['four_px_editorial_header_retained'],'4px editorial rule retained')
check((ROOT/'history/release-manifest-v0.59.0.json').exists() and (ROOT/'history/workspace-product-record-v0.59.0.json').exists(),'v0.59.0 history retained')
check('workspace-v0.59.1.js' in PHP and 'workspace-v0.59.1.css' in PHP and len(APP)>100000,'current app assets')
print('PASS - v0.59.1 release validator')
